import { AuthService } from '@skylabs-monorepo/shared-auth/angular';
import { provideRouter } from '@angular/router';
import { TestBed } from '@angular/core/testing';
import { of, Subject } from 'rxjs';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { PillReviewComponent } from './pill-review';
import { PillReviewApi, PillReview } from '../../../core/drivers/pill-review-api.service';

const snapshot:PillReview={driverId:'driver-a',pills:[],checked:0,total:1,issues:0,status:'In review'};
describe('deliberate assigned-review licence check',()=>{
  let api:{getAssigned:ReturnType<typeof vi.fn>;getOwn:ReturnType<typeof vi.fn>;getStaff:ReturnType<typeof vi.fn>;verifyDl:ReturnType<typeof vi.fn>;save:ReturnType<typeof vi.fn>};
  beforeEach(()=>{api={getAssigned:vi.fn(()=>of(snapshot)),getOwn:vi.fn(()=>of(snapshot)),getStaff:vi.fn(()=>of(snapshot)),verifyDl:vi.fn(()=>of(snapshot)),save:vi.fn()};TestBed.configureTestingModule({imports:[PillReviewComponent],providers:[provideRouter([]),{provide:AuthService,useValue:{can:()=>false}},{provide:PillReviewApi,useValue:api}]});});
  function create(){const f=TestBed.createComponent(PillReviewComponent);f.componentRef.setInput('driverId','driver-a');f.detectChanges();TestBed.tick();return f;}
  it('never checks while opening, navigating or reviewing a pill; explicit action uses only the saved record ID',()=>{const f=create();f.componentInstance.selectTab(3);expect(api.verifyDl).not.toHaveBeenCalled();f.componentInstance.verifyDl();expect(api.verifyDl).toHaveBeenCalledWith('driver-a',false);expect(api.save).not.toHaveBeenCalled();expect(f.componentInstance.review()?.checked).toBe(0);});
  it('prevents concurrent clicks and ignores results for a previously opened driver',()=>{const pending=new Subject<PillReview>();api.verifyDl.mockReturnValue(pending);const f=create();f.componentInstance.verifyDl();f.componentInstance.verifyDl();expect(api.verifyDl).toHaveBeenCalledTimes(1);f.componentRef.setInput('driverId','driver-b');f.detectChanges();TestBed.tick();pending.next({...snapshot,status:'old result'});expect(f.componentInstance.review()?.status).not.toBe('old result');});
  it('denies own and ordinary read-only staff actions and allows the explicit administrative review context',()=>{const f=create();f.componentRef.setInput('own',true);f.detectChanges();f.componentInstance.verifyDl();expect(api.verifyDl).not.toHaveBeenCalled();f.componentRef.setInput('own',false);f.componentRef.setInput('staff',true);f.detectChanges();f.componentInstance.verifyDl();expect(api.verifyDl).not.toHaveBeenCalled();f.componentRef.setInput('administrativeDl',true);f.detectChanges();f.componentInstance.verifyDl(true);expect(api.verifyDl).toHaveBeenCalledWith('driver-a',true);});
  it('shows a reason editor only after Raise Issue and immediately persists a reasoned decision',()=>{const item={key:'field:firstName',field:'firstName',label:'First Name',value:'Saved name',hash:'hash',status:'Pending' as const,reason:null,checkable:true,changedSinceReview:false};const submitted={...snapshot,pills:[{tab:1,pill:0,label:'Identity',tabLabel:'Personal Details',completed:true,items:[item]}]};api.getAssigned.mockReturnValue(of(submitted));api.save.mockReturnValue(of({...submitted,issues:1}));const f=create();expect(f.nativeElement.querySelector('.issue-editor')).toBeNull();f.componentInstance.raiseIssue(item);f.detectChanges();expect(f.nativeElement.querySelector('.issue-editor')).not.toBeNull();f.componentInstance.save(item,'Issue');expect(api.save).not.toHaveBeenCalled();f.componentInstance.setReason(item.key,'Please correct the name');f.componentInstance.save(item,'Issue');expect(api.save).toHaveBeenCalledWith('driver-a',item,'Issue','Please correct the name');f.detectChanges();expect(f.nativeElement.querySelector('.issue-editor')).toBeNull();expect(f.nativeElement.textContent).toContain('saved as Issue');f.destroy();});
  it('shows an enabled explicit review action without login, consent, phone or OTP',()=>{const submitted={...snapshot,profile:{name:'Saved Driver',photo:null,assignedReviewer:'Reviewer',loginLinked:false},dl:{enabled:true,status:'Not checked',reason:'Verify the saved driving licence.',inputs:{dlNo:'UP53 20260001705',dob:'2004-04-24'},history:[]}};api.getAssigned.mockReturnValue(of(submitted));const f=create();f.componentInstance.selectTab(3);f.detectChanges();const button=[...f.nativeElement.querySelectorAll('md-outlined-button')].find((b:any)=>b.textContent.trim()==='Verify DL') as any;expect(button).toBeTruthy();expect(button.disabled).toBe(false);expect(f.nativeElement.textContent).not.toContain('Get Driver Consent');expect(f.nativeElement.querySelector('input[type=checkbox]')).toBeNull();expect(api.verifyDl).not.toHaveBeenCalled();button.click();expect(api.verifyDl).toHaveBeenCalledWith('driver-a',false);f.destroy();});
});
