/**
 * Seeds mera-driver-api's independent `mera_driver` database with:
 *  - 6 system roles (super_admin, admin, customer, vendor, marketing, sales) — the same
 *    six role keys as msd-api, since RBAC role *names* are shared vocabulary even though
 *    the two databases are fully independent.
 *  - One Permission row per (menuKey, action) pair, generated by walking the static
 *    mera-driver menu tree from `@skylabs-monorepo/shared-menu` — never hand-typed, so the
 *    permission catalog can never drift from the menu.
 *  - Every Permission auto-granted to `super_admin` (the ONLY place `Role.isSuperAdmin`
 *    drives behavior in this file — a boolean flag check, never a string role-name compare).
 *  - A couple of DashboardWidget rows assigned differently across admin/sales/marketing.
 *
 * Run with: `npx prisma db seed` (schema points here via `prisma.seed` — see package.json).
 */

import path from 'path';
import dotenv from 'dotenv';

// Load this app's own .env.local — mera-driver-api never shares env/config with msd-api,
// and this script may be run standalone (`npx tsx apps/mera-driver-api/prisma/seed.ts`)
// rather than through `npx prisma db seed`, which is why we load explicitly instead of
// relying on Prisma CLI's own env discovery.
dotenv.config({ path: path.join(__dirname, '..', '.env.local') });

import { PrismaClient } from '../src/generated/prisma-client';
import { getMenuForApp } from '@skylabs-monorepo/shared-menu';
import { permissionKeyFor } from '@skylabs-monorepo/shared-permissions';
import type { MenuNode, PermissionAction } from '@skylabs-monorepo/shared-types';

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Roles
// ---------------------------------------------------------------------------

interface RoleSeed {
  key: string;
  name: string;
  description: string;
  isSuperAdmin: boolean;
}

const ROLES: RoleSeed[] = [
  { key: 'super_admin', name: 'Super Admin', description: 'Full access to every module — auto-granted every permission.', isSuperAdmin: true },
  { key: 'admin', name: 'Admin', description: 'Operational administrator for the mera-driver console.', isSuperAdmin: false },
  { key: 'customer', name: 'Customer', description: 'Rider booking trips through the mera-driver app.', isSuperAdmin: false },
  { key: 'vendor', name: 'Vendor', description: 'Fleet/vendor partner managing drivers and vehicles.', isSuperAdmin: false },
  { key: 'marketing', name: 'Marketing', description: 'Marketing team — promotions, dashboards, reports.', isSuperAdmin: false },
  { key: 'sales', name: 'Sales', description: 'Sales team — leads, conversions, reports.', isSuperAdmin: false },
];

async function seedRoles() {
  const roles = new Map<string, { id: string; key: string; isSuperAdmin: boolean }>();
  for (const seed of ROLES) {
    const role = await prisma.role.upsert({
      where: { key: seed.key },
      create: { key: seed.key, name: seed.name, description: seed.description, isSystem: true, isSuperAdmin: seed.isSuperAdmin },
      update: { name: seed.name, description: seed.description, isSystem: true, isSuperAdmin: seed.isSuperAdmin },
    });
    roles.set(role.key, role);
  }
  return roles;
}

// ---------------------------------------------------------------------------
// Permissions — generated from the static menu, not hand-typed.
// ---------------------------------------------------------------------------

const RBAC_ROLES_ACTIONS: PermissionAction[] = ['view', 'create', 'edit', 'delete', 'status_change'];
const RBAC_USERS_ACTIONS: PermissionAction[] = ['view', 'create', 'edit', 'delete', 'assign', 'status_change'];
const RBAC_AUDIT_ACTIONS: PermissionAction[] = ['view'];
const GROUP_ACTIONS: PermissionAction[] = ['view']; // parent menu groups with no route of their own
const LEAF_ACTIONS: PermissionAction[] = ['view', 'create', 'edit', 'delete'];

function actionsForNode(node: MenuNode): PermissionAction[] {
  if (node.children && node.children.length > 0) return GROUP_ACTIONS;
  switch (node.permissionKey) {
    case 'rbac.roles':
      return RBAC_ROLES_ACTIONS;
    case 'rbac.users':
      return RBAC_USERS_ACTIONS;
    case 'rbac.audit-logs':
      return RBAC_AUDIT_ACTIONS;
    default:
      return LEAF_ACTIONS;
  }
}

function flattenMenu(nodes: MenuNode[]): MenuNode[] {
  return nodes.flatMap((node) => [node, ...(node.children ? flattenMenu(node.children) : [])]);
}

async function seedPermissions() {
  const nodes = flattenMenu(getMenuForApp('mera-driver'));
  const permissionIds: string[] = [];

  for (const node of nodes) {
    for (const action of actionsForNode(node)) {
      const key = permissionKeyFor(node.permissionKey, action);
      const permission = await prisma.permission.upsert({
        where: { key },
        create: { menuKey: node.permissionKey, action, key, label: `${node.title} — ${action}` },
        update: { menuKey: node.permissionKey, action, label: `${node.title} — ${action}` },
      });
      permissionIds.push(permission.id);
    }
  }

  return permissionIds;
}

async function grantAllPermissionsToSuperAdmin(superAdminRoleId: string, permissionIds: string[]) {
  // The ONLY place `isSuperAdmin` drives behavior in application logic: auto-grant every
  // Permission to any role flagged `isSuperAdmin: true`. Never a `role.key === 'super_admin'`
  // string comparison — this reads the boolean column on the Role row.
  await prisma.rolePermission.deleteMany({ where: { roleId: superAdminRoleId } });
  await prisma.rolePermission.createMany({
    data: permissionIds.map((permissionId) => ({ roleId: superAdminRoleId, permissionId })),
    skipDuplicates: true,
  });
}

async function grantBaselinePermissions(roles: Map<string, { id: string }>) {
  // A modest starter grant so `admin`/`marketing`/`sales` aren't locked out of everything
  // on a fresh seed — real deployments manage this via `PUT /rbac/roles/:id/permissions`.
  const grantViewOf = async (roleKey: string, menuKeys: string[]) => {
    const role = roles.get(roleKey);
    if (!role) return;
    const permissions = await prisma.permission.findMany({
      where: { menuKey: { in: menuKeys }, action: 'view' },
    });
    await prisma.rolePermission.createMany({
      data: permissions.map((p) => ({ roleId: role.id, permissionId: p.id })),
      skipDuplicates: true,
    });
  };

  await grantViewOf('admin', ['dashboard', 'drivers', 'vehicles', 'trips', 'attendance', 'payments', 'reports', 'masters', 'masters.vehicle-types', 'masters.zones', 'administration', 'rbac.roles', 'rbac.users', 'rbac.audit-logs', 'settings']);
  await grantViewOf('marketing', ['dashboard', 'reports', 'settings']);
  await grantViewOf('sales', ['dashboard', 'trips', 'payments', 'reports', 'settings']);
  await grantViewOf('vendor', ['dashboard', 'drivers', 'vehicles', 'trips']);
  await grantViewOf('customer', ['dashboard']);
}

// ---------------------------------------------------------------------------
// Dashboard widgets
// ---------------------------------------------------------------------------

interface WidgetSeed {
  key: string;
  title: string;
  module: string;
  description: string;
}

const WIDGETS: WidgetSeed[] = [
  { key: 'drivers-active', title: 'Active Drivers', module: 'drivers', description: 'Count of drivers currently online.' },
  { key: 'trips-today', title: "Today's Trips", module: 'trips', description: 'Trips started or completed today.' },
  { key: 'payments-summary', title: 'Payments Summary', module: 'payments', description: 'Revenue collected this period.' },
];

async function seedDashboardWidgets() {
  const widgets = new Map<string, { id: string; key: string }>();
  for (const seed of WIDGETS) {
    const widget = await prisma.dashboardWidget.upsert({
      where: { key: seed.key },
      create: seed,
      update: seed,
    });
    widgets.set(widget.key, widget);
  }
  return widgets;
}

async function assignDashboardWidgets(
  roles: Map<string, { id: string; isSuperAdmin: boolean }>,
  widgets: Map<string, { id: string; key: string }>,
) {
  const assign = async (roleKey: string, widgetKey: string, order: number) => {
    const role = roles.get(roleKey);
    const widget = widgets.get(widgetKey);
    if (!role || !widget) return;
    await prisma.roleDashboardWidget.upsert({
      where: { roleId_widgetId: { roleId: role.id, widgetId: widget.id } },
      create: { roleId: role.id, widgetId: widget.id, order },
      update: { order },
    });
  };

  // SuperAdmin sees every widget, same principle as grantAllPermissionsToSuperAdmin above.
  for (const [key, role] of roles.entries()) {
    if (!role.isSuperAdmin) continue;
    let order = 1;
    for (const widgetKey of widgets.keys()) {
      await assign(key, widgetKey, order);
      order += 1;
    }
  }

  // admin sees everything
  await assign('admin', 'drivers-active', 1);
  await assign('admin', 'trips-today', 2);
  await assign('admin', 'payments-summary', 3);

  // sales cares about trips + payments, not driver headcount
  await assign('sales', 'trips-today', 1);
  await assign('sales', 'payments-summary', 2);

  // marketing only cares about trip volume as a proxy for demand
  await assign('marketing', 'trips-today', 1);
}

/**
 * Pre-creates the SuperAdmin user (with the super_admin role already attached) so their
 * *first* OTP login doesn't fall through to whatever default-role logic applies to a
 * roles.length===0 user. Identifier comes from SUPERADMIN_PHONE/SUPERADMIN_EMAIL in
 * .env.local — skipped (not guessed) if neither is set.
 */
async function seedSuperAdminUser(roles: Map<string, { id: string; isSuperAdmin: boolean }>) {
  const phone = process.env.SUPERADMIN_PHONE || undefined;
  const email = process.env.SUPERADMIN_EMAIL || undefined;
  if (!phone && !email) {
    console.log('SUPERADMIN_PHONE/SUPERADMIN_EMAIL not set — skipping SuperAdmin user seed.');
    return;
  }

  const superAdminRole = roles.get('super_admin');
  if (!superAdminRole) return;

  const user = await prisma.user.upsert({
    where: phone ? { phone } : { email: email! },
    update: {},
    create: { name: 'Super Admin', phone, email },
  });

  await prisma.userRole.upsert({
    where: { userId_roleId: { userId: user.id, roleId: superAdminRole.id } },
    update: {},
    create: { userId: user.id, roleId: superAdminRole.id },
  });

  console.log(`Seeded SuperAdmin user (${phone ?? email}).`);
}

async function main() {
  console.log('Seeding mera-driver-api...');

  const roles = await seedRoles();
  const permissionIds = await seedPermissions();

  const superAdmin = roles.get('super_admin');
  if (superAdmin) {
    await grantAllPermissionsToSuperAdmin(superAdmin.id, permissionIds);
  }
  await grantBaselinePermissions(roles);

  const widgets = await seedDashboardWidgets();
  await assignDashboardWidgets(roles, widgets);

  await seedSuperAdminUser(roles);

  console.log(`Seeded ${roles.size} roles, ${permissionIds.length} permissions, ${widgets.size} dashboard widgets.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
