/**
 * Seeds: 6 system roles, Permission rows generated by walking shared-menu's msd-menu.json,
 * every Permission auto-linked to the `super_admin` role (the ONLY place the isSuperAdmin
 * flag drives any logic — application/route code must never check it directly), and a
 * couple of DashboardWidget rows assigned differently per role.
 *
 * Run with: npx prisma db seed --schema=apps/msd-api/prisma/schema.prisma
 * (wired via the root package.json "prisma.seed" script — see package.json).
 */
import * as path from 'path';
import * as dotenv from 'dotenv';

// seed.ts is run standalone (tsx), not through main.ts's bootstrap, so it needs its own
// env load. Prisma's CLI only auto-loads a file literally named `.env`; this repo's
// convention is `.env.local`, hence the explicit dotenv.config() here.
dotenv.config({ path: path.join(__dirname, '../.env.local') });

import { PrismaClient } from '../src/generated/prisma-client';
import type { PermissionAction, MenuNode } from '@skylabs-monorepo/shared-types';
import { permissionKeyFor } from '@skylabs-monorepo/shared-permissions';
import { getMenuForApp } from '@skylabs-monorepo/shared-menu';

const prisma = new PrismaClient();

interface RoleSeed {
  key: string;
  name: string;
  description: string;
  isSystem: boolean;
  isSuperAdmin: boolean;
}

const ROLES: RoleSeed[] = [
  { key: 'super_admin', name: 'Super Admin', description: 'Full unrestricted access to every module.', isSystem: true, isSuperAdmin: true },
  { key: 'admin', name: 'Admin', description: 'MSD staff — full moderation and CRUD.', isSystem: true, isSuperAdmin: false },
  { key: 'customer', name: 'Customer', description: 'Consumer-facing base role.', isSystem: true, isSuperAdmin: false },
  { key: 'vendor', name: 'Vendor', description: 'Company/vendor owner or manager.', isSystem: true, isSuperAdmin: false },
  { key: 'marketing', name: 'Marketing', description: 'Content, promotions, categories.', isSystem: true, isSuperAdmin: false },
  { key: 'sales', name: 'Sales', description: 'Vendor accounts and reporting.', isSystem: true, isSuperAdmin: false },
];

/** Per-menuKey action subset. Every node gets 'view' at minimum (added below); this map adds the rest. */
const EXTRA_ACTIONS_BY_MENU_KEY: Record<string, PermissionAction[]> = {
  customers: ['create', 'edit', 'delete', 'export'],
  // 'custom' gates the vendor's own `/vendors/me*` self-service surface — granted only to the
  // `vendor` role (never `view`, which would leak the admin "list every vendor" endpoint).
  vendors: ['create', 'edit', 'delete', 'export', 'approve', 'reject', 'status_change', 'custom'],
  orders: ['create', 'edit', 'delete', 'export', 'status_change'],
  products: ['create', 'edit', 'delete', 'export'],
  services: ['create', 'edit', 'delete', 'export'],
  inventory: ['create', 'edit', 'delete', 'export'],
  reports: ['export'],
  // Categories and Sub Categories are the same underlying Category table (parentId null vs
  // set) — the backend gates all of it on 'masters.categories' (see categories.routes.ts);
  // 'masters.sub-categories' only needs its own Permission rows so the *second* sidebar item
  // (a distinct menu node) has something to grant :view on for visibility.
  'masters.categories': ['create', 'edit', 'delete'],
  'masters.sub-categories': ['create', 'edit', 'delete'],
  'masters.tags': ['create', 'edit', 'delete'],
  'rbac.roles': ['create', 'edit', 'delete', 'status_change'],
  'rbac.users': ['create', 'edit', 'delete', 'assign', 'status_change', 'custom'],
  'rbac.audit-logs': [],
  settings: ['edit'],
};

function flattenMenu(nodes: readonly MenuNode[]): MenuNode[] {
  const out: MenuNode[] = [];
  for (const node of nodes) {
    out.push(node);
    if (node.children) out.push(...flattenMenu(node.children));
  }
  return out;
}

function actionsForMenuKey(menuKey: string): PermissionAction[] {
  const extra = EXTRA_ACTIONS_BY_MENU_KEY[menuKey] ?? [];
  return ['view' as PermissionAction, ...extra.filter((a) => a !== 'view')];
}

async function seedRoles() {
  const roles = new Map<string, { id: string; isSuperAdmin: boolean }>();
  for (const roleSeed of ROLES) {
    const role = await prisma.role.upsert({
      where: { key: roleSeed.key },
      update: {
        name: roleSeed.name,
        description: roleSeed.description,
        isSystem: roleSeed.isSystem,
        isSuperAdmin: roleSeed.isSuperAdmin,
      },
      create: roleSeed,
    });
    roles.set(role.key, { id: role.id, isSuperAdmin: role.isSuperAdmin });
  }
  return roles;
}

async function seedPermissions(): Promise<Map<string, string>> {
  const menu = flattenMenu(getMenuForApp('msd'));
  const permissionIdByKey = new Map<string, string>();

  for (const node of menu) {
    for (const action of actionsForMenuKey(node.permissionKey)) {
      const key = permissionKeyFor(node.permissionKey, action);
      const permission = await prisma.permission.upsert({
        where: { key },
        update: { label: `${node.title} — ${action}` },
        create: { menuKey: node.permissionKey, action, key, label: `${node.title} — ${action}` },
      });
      permissionIdByKey.set(key, permission.id);
    }
  }

  return permissionIdByKey;
}

async function grantAllPermissionsToSuperAdmins(
  roles: Map<string, { id: string; isSuperAdmin: boolean }>,
  permissionIdByKey: Map<string, string>,
) {
  const allPermissionIds = [...permissionIdByKey.values()];
  for (const role of roles.values()) {
    if (!role.isSuperAdmin) continue;
    await prisma.rolePermission.deleteMany({ where: { roleId: role.id } });
    await prisma.rolePermission.createMany({
      data: allPermissionIds.map((permissionId) => ({ roleId: role.id, permissionId })),
      skipDuplicates: true,
    });
  }
}

/** A reasonable starter grant for the non-super-admin staff roles, so the app isn't empty on first login. */
async function grantStarterPermissions(
  roles: Map<string, { id: string; isSuperAdmin: boolean }>,
  permissionIdByKey: Map<string, string>,
) {
  const grant = async (roleKey: string, keys: string[]) => {
    const role = roles.get(roleKey);
    if (!role) return;
    const ids = keys.map((k) => permissionIdByKey.get(k)).filter((v): v is string => Boolean(v));
    await prisma.rolePermission.createMany({
      data: ids.map((permissionId) => ({ roleId: role.id, permissionId })),
      skipDuplicates: true,
    });
  };

  await grant('admin', [
    'dashboard:view',
    'customers:view', 'customers:create', 'customers:edit', 'customers:delete',
    'vendors:view', 'vendors:create', 'vendors:edit', 'vendors:delete',
    'vendors:approve', 'vendors:reject', 'vendors:status_change',
    'orders:view', 'orders:edit', 'orders:status_change',
    'products:view', 'products:create', 'products:edit', 'products:delete',
    'services:view', 'services:create', 'services:edit', 'services:delete',
    'inventory:view', 'inventory:create', 'inventory:edit', 'inventory:delete',
    'reports:view',
    'masters:view', 'masters.categories:view', 'masters.categories:create', 'masters.categories:edit', 'masters.categories:delete',
    'masters.sub-categories:view', 'masters.sub-categories:create', 'masters.sub-categories:edit', 'masters.sub-categories:delete',
    'masters.tags:view', 'masters.tags:create', 'masters.tags:edit', 'masters.tags:delete',
    'settings:view', 'settings:edit',
  ]);

  await grant('marketing', [
    'dashboard:view',
    'masters:view', 'masters.categories:view', 'masters.categories:create', 'masters.categories:edit',
    'masters.sub-categories:view', 'masters.sub-categories:create', 'masters.sub-categories:edit',
    'masters.tags:view', 'masters.tags:create', 'masters.tags:edit', 'masters.tags:delete',
    'reports:view',
  ]);

  await grant('sales', [
    'dashboard:view',
    'vendors:view', 'vendors:edit',
    'orders:view', 'orders:export',
    'reports:view', 'reports:export',
  ]);

  await grant('customer', ['dashboard:view']);
  // Deliberately NOT 'vendors:view' — that would also unlock the admin "list every vendor"
  // endpoint (requirePermission only checks the boolean grant, not who's asking). 'custom'
  // gates only the ownership-scoped `/vendors/me*` self-service surface. 'vendor-portal:view'
  // is a separate, narrower menu key that only surfaces the "My Business" sidebar item —
  // never granted to admin/customer/etc., so it can't leak the admin Vendors/Branches/Deals nav.
  await grant('vendor', ['dashboard:view', 'orders:view', 'products:view', 'services:view', 'vendors:custom', 'vendor-portal:view']);
}

async function seedDashboardWidgets(roles: Map<string, { id: string; isSuperAdmin: boolean }>) {
  const widgets = [
    { key: 'customers-count', title: 'Total Customers', module: 'customers', description: 'Count of active customers.' },
    { key: 'orders-recent', title: 'Recent Orders', module: 'orders', description: 'Latest orders across all vendors.' },
    { key: 'revenue-summary', title: 'Revenue Summary', module: 'reports', description: 'Revenue rollup for the current period.' },
    { key: 'vendor-profile', title: 'My Business', module: 'vendors', description: "Entry point to the vendor's own business profile, branches, and deals." },
  ];

  const widgetIdByKey = new Map<string, string>();
  for (const widget of widgets) {
    const row = await prisma.dashboardWidget.upsert({
      where: { key: widget.key },
      update: widget,
      create: widget,
    });
    widgetIdByKey.set(widget.key, row.id);
  }

  const assign = async (roleKey: string, keysInOrder: string[]) => {
    const role = roles.get(roleKey);
    if (!role) return;
    await prisma.roleDashboardWidget.deleteMany({ where: { roleId: role.id } });
    await prisma.roleDashboardWidget.createMany({
      data: keysInOrder.map((key, order) => ({
        roleId: role.id,
        widgetId: widgetIdByKey.get(key)!,
        order,
      })),
    });
  };

  // SuperAdmin sees every widget, same principle as grantAllPermissionsToSuperAdmins above.
  for (const [key, role] of roles.entries()) {
    if (role.isSuperAdmin) await assign(key, widgets.map((w) => w.key));
  }

  await assign('admin', ['customers-count', 'orders-recent', 'revenue-summary']);
  await assign('sales', ['revenue-summary', 'orders-recent']);
  await assign('marketing', ['customers-count']);
  // Vendor's own entry point to /account/vendors — the sidebar item itself is admin-only
  // (see the `vendors:custom` note above), so this widget is how a vendor user reaches it.
  await assign('vendor', ['vendor-profile']);
}

/**
 * Pre-creates the SuperAdmin user (with the super_admin role already attached) so their
 * *first* OTP login doesn't fall through `loginWithIdentifier`'s "no roles yet -> default to
 * customer" path (see auth.service.ts). Identifier comes from SUPERADMIN_PHONE/
 * SUPERADMIN_EMAIL in .env.local — skipped (not guessed) if neither is set.
 */
async function seedSuperAdminUser(roles: Map<string, { id: string; isSuperAdmin: boolean }>) {
  const phone = process.env.SUPERADMIN_PHONE || undefined;
  const email = process.env.SUPERADMIN_EMAIL || undefined;
  if (!phone && !email) {
    console.log('SUPERADMIN_PHONE/SUPERADMIN_EMAIL not set — skipping SuperAdmin user seed.');
    return;
  }

  const superAdminRole = roles.get('super_admin');
  if (!superAdminRole) return;

  const user = await prisma.user.upsert({
    where: phone ? { phone } : { email: email! },
    update: {},
    create: { name: 'Super Admin', phone, email },
  });

  await prisma.userRole.upsert({
    where: { userId_roleId: { userId: user.id, roleId: superAdminRole.id } },
    update: {},
    create: { userId: user.id, roleId: superAdminRole.id },
  });

  console.log(`Seeded SuperAdmin user (${phone ?? email}).`);
}

/**
 * A starter handful of categories/subcategories — real admin CRUD (`masters.categories`/
 * `masters.sub-categories`) manages the rest from here; this just seeds enough rows so the
 * Deal form and the Category/Sub-category admin lists aren't empty on first run.
 */
async function seedCategories() {
  const parents = [
    { name: 'Spa & Wellness', slug: 'spa-wellness' },
    { name: 'Salon & Grooming', slug: 'salon-grooming' },
  ];
  const parentIdBySlug = new Map<string, string>();
  for (const parent of parents) {
    const row = await prisma.category.upsert({ where: { slug: parent.slug }, update: parent, create: parent });
    parentIdBySlug.set(parent.slug, row.id);
  }

  const children = [
    { name: 'Massage Therapy', slug: 'massage-therapy', parentSlug: 'spa-wellness' },
    { name: 'Facial & Skincare', slug: 'facial-skincare', parentSlug: 'salon-grooming' },
  ];
  for (const child of children) {
    const parentId = parentIdBySlug.get(child.parentSlug)!;
    await prisma.category.upsert({
      where: { slug: child.slug },
      update: { name: child.name, parentId },
      create: { name: child.name, slug: child.slug, parentId },
    });
  }
}

async function main() {
  const roles = await seedRoles();
  const permissionIdByKey = await seedPermissions();
  await grantAllPermissionsToSuperAdmins(roles, permissionIdByKey);
  await grantStarterPermissions(roles, permissionIdByKey);
  await seedDashboardWidgets(roles);
  await seedSuperAdminUser(roles);
  await seedCategories();
  console.log(`Seeded ${roles.size} roles and ${permissionIdByKey.size} permissions.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
