import {TestBed} from '@angular/core/testing';
import {provideHttpClient} from '@angular/common/http';
import {HttpTestingController,provideHttpClientTesting} from '@angular/common/http/testing';
import {provideRouter} from '@angular/router';
import {AuthService,provideSharedAuth} from '@skylabs-monorepo/shared-auth/angular';
import {Customers} from './customers';
describe('customer status and server list',()=>{
 let http:HttpTestingController;let component:Customers;
 beforeEach(async()=>{await TestBed.configureTestingModule({imports:[Customers],providers:[provideRouter([]),provideHttpClient(),provideHttpClientTesting(),provideSharedAuth({appPrefix:'test_customer',apiBaseUrl:'http://localhost/api'})]}).compileComponents();const fixture=TestBed.createComponent(Customers);component=fixture.componentInstance;http=TestBed.inject(HttpTestingController);fixture.detectChanges();http.expectOne(request=>request.url.endsWith('/customers')).flush({data:[],meta:{total:10000,counts:{Active:8000,Inactive:2000}}});});
 afterEach(()=>{http.verify();vi.restoreAllMocks();TestBed.resetTestingModule();});
 it('shows database status counts and combines server search/filter/sort',()=>{expect(component.total()).toBe(10000);expect(component.counts()['Inactive']).toBe(2000);component.filterStatus('Inactive');http.expectOne(request=>request.url.endsWith('/customers')).flush({data:[],meta:{total:2000,counts:{}}});component.tableParams(new CustomEvent('params',{detail:{page:2,pageSize:50,search:'Ravi',sortKey:'first_name',sortDir:'asc'}}));const request=http.expectOne(request=>request.url.endsWith('/customers'));expect(request.request.params.get('status')).toBe('Inactive');expect(request.request.params.get('pageSize')).toBe('50');expect(request.request.params.get('sort')).toBe('firstName');request.flush({data:[],meta:{total:3,counts:{}}});});
 it('requires permission and sends the impact acknowledgement plus audit reason',()=>{const row={customer_uid:'customer',first_name:'Ravi',mobile_number:'123',account_status:'Active',active_booking_count:2} as any;component.toggleStatus(row);http.expectNone(request=>request.method==='PATCH');vi.spyOn(TestBed.inject(AuthService),'can').mockReturnValue(true);const prompt=vi.spyOn(window,'prompt').mockReturnValue('Customer requested suspension');component.toggleStatus(row);expect(prompt.mock.calls[0][0]).toContain('2 active bookings remain unchanged');const request=http.expectOne(request=>request.method==='PATCH');expect(request.request.body).toMatchObject({accountStatus:'Inactive',statusReason:'Customer requested suspension',acknowledgeActiveBookings:true});expect(request.request.body).not.toHaveProperty('bookingStatus');request.flush({data:{id:'customer',firstName:'Ravi',mobileNumber:'123',accountStatus:'Inactive'}});http.expectOne(request=>request.url.endsWith('/customers')).flush({data:[],meta:{total:10000,counts:{}}});});
});
