import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
const {createTransport,sendMail}=vi.hoisted(()=>({createTransport:vi.fn(),sendMail:vi.fn()}));
vi.mock('nodemailer',()=>({default:{createTransport}}));
beforeEach(()=>{vi.stubEnv('SMTP_HOST','smtp.example.invalid');vi.stubEnv('SMTP_PORT','587');vi.stubEnv('SMTP_USER','user-fixture');vi.stubEnv('SMTP_PASS','secret-fixture');vi.stubEnv('EMAIL_FROM','sender@example.invalid');createTransport.mockReset().mockReturnValue({sendMail});sendMail.mockReset();vi.spyOn(console,'info').mockImplementation(()=>{});vi.spyOn(console,'error').mockImplementation(()=>{});});
afterEach(()=>{vi.unstubAllEnvs();vi.restoreAllMocks();});
async function provider(){vi.resetModules();return import('./smtp.provider');}
describe('SMTP OTP delivery',()=>{
 it('accepts the intended recipient with bounded SMTP timeouts',async()=>{sendMail.mockResolvedValue({accepted:['recipient@example.invalid'],rejected:[]});const {sendOtpEmail}=await provider();await expect(sendOtpEmail('recipient@example.invalid','123456')).resolves.toBe(true);expect(createTransport).toHaveBeenCalledWith(expect.objectContaining({connectionTimeout:5000,greetingTimeout:5000,socketTimeout:10000,secure:false}));});
 it('does not report success when SMTP rejects the intended recipient',async()=>{sendMail.mockResolvedValue({accepted:[],rejected:['recipient@example.invalid']});const {sendOtpEmail}=await provider();await expect(sendOtpEmail('recipient@example.invalid','123456')).rejects.toMatchObject({code:'OTP_PROVIDER_REJECTED'});});
 it('rejects missing configuration without creating a transporter',async()=>{vi.stubEnv('SMTP_PASS','');const {sendOtpEmail}=await provider();await expect(sendOtpEmail('recipient@example.invalid','123456')).rejects.toMatchObject({code:'OTP_PROVIDER_NOT_CONFIGURED'});expect(createTransport).not.toHaveBeenCalled();});
 it.each(['0','NaN','70000'])('rejects invalid SMTP port %s',async port=>{vi.stubEnv('SMTP_PORT',port);const {sendOtpEmail}=await provider();await expect(sendOtpEmail('recipient@example.invalid','123456')).rejects.toMatchObject({code:'OTP_PROVIDER_NOT_CONFIGURED'});});
 it.each([['EAUTH','OTP_PROVIDER_AUTH_FAILED'],['EACCES','OTP_NETWORK_BLOCKED'],['ETIMEDOUT','OTP_PROVIDER_TIMEOUT']])('classifies %s without logging secrets',async(code,expected)=>{sendMail.mockRejectedValue({code,message:'secret-fixture OTP 123456 recipient@example.invalid'});const {sendOtpEmail}=await provider();await expect(sendOtpEmail('recipient@example.invalid','123456')).rejects.toMatchObject({code:expected});expect(JSON.stringify(vi.mocked(console.error).mock.calls)).not.toMatch(/secret-fixture|123456|recipient@example.invalid/);});
 it('reuses the transport but rebuilds it after a credential change',async()=>{sendMail.mockResolvedValue({accepted:['recipient@example.invalid']});const {sendOtpEmail}=await provider();await sendOtpEmail('recipient@example.invalid','123456');await sendOtpEmail('recipient@example.invalid','123456');expect(createTransport).toHaveBeenCalledTimes(1);vi.stubEnv('SMTP_PASS','changed-secret-fixture');await sendOtpEmail('recipient@example.invalid','123456');expect(createTransport).toHaveBeenCalledTimes(2);});
});
