import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { of } from 'rxjs';
import { AuthService } from '@skylabs-monorepo/shared-auth/angular';
import { Workflow } from './workflow';
import { environment } from '../../../environments/environment';
const booking={id:'booking',bookingCode:'MD-TEST',customerName:'Customer',status:'requested',driverId:undefined as string|undefined,updatedAt:'2026-10-08T00:00:00.000Z'};
const candidate={id:'replacement',name:'Replacement',phone:'9000000000',reasons:[] as string[]};
describe('compact dispatch dialog',()=>{
  let http:HttpTestingController;
  async function mount(can=true){await TestBed.configureTestingModule({imports:[Workflow],providers:[provideRouter([]),provideHttpClient(),provideHttpClientTesting(),{provide:ActivatedRoute,useValue:{data:of({mode:'dispatch'})}},{provide:AuthService,useValue:{can:()=>can}}]}).compileComponents();const f=TestBed.createComponent(Workflow);http=TestBed.inject(HttpTestingController);f.detectChanges();http.expectOne(r=>r.url.endsWith('/workflow/dispatch')).flush({data:[booking],meta:{total:1}});return f;}
  function details(b=booking){const detail=http.expectOne(`${environment.apiUrl}/workflow/dispatch/booking`);expect(detail.request.method).toBe('GET');detail.flush({data:b});const candidates=http.expectOne(r=>r.url===`${environment.apiUrl}/workflow/dispatch/booking/candidates`);expect(candidates.request.method).toBe('GET');candidates.flush({data:[candidate]});}
  afterEach(()=>{http?.verify();TestBed.resetTestingModule();});
  it('reassigns through the existing POST assignment endpoint without changing the detail URL',async()=>{
    const f=await mount(),c=f.componentInstance,b={...booking,driverId:'current',status:'confirmed'};
    c.openAssignment(b);details(b);c.selectCandidate(candidate);c.assignment.reason='Reviewed replacement';c.submitAssignment();
    const request=http.expectOne(`${environment.apiUrl}/workflow/dispatch/booking/assign`);
    expect(request.request.method).toBe('POST');expect(request.request.body.expectedDriverId).toBe('current');
    request.flush({data:{...b,driverId:'replacement'}});
    http.expectOne(r=>r.url===`${environment.apiUrl}/workflow/dispatch`).flush({data:[b],meta:{total:1}});f.destroy();
  });
  it('sends quick/search/date/sort/page filters to the API and ignores stale list responses',async()=>{const f=await mount();const c=f.componentInstance;c.dispatchParams(new CustomEvent('params',{detail:{page:2,pageSize:25,search:'Alice',sortKey:'scheduleLabel',sortDir:'asc'}}));const stale=http.expectOne(r=>r.url.endsWith('/dispatch'));expect(stale.request.params.get('page')).toBe('2');expect(stale.request.params.get('sort')).toBe('startsAt');c.quickFilter('needs_assignment');const current=http.expectOne(r=>r.url.endsWith('/dispatch'));expect(current.request.params.get('quick')).toBe('needs_assignment');expect(current.request.params.get('search')).toBe('Alice');expect(current.request.params.get('page')).toBe('1');current.flush({data:[{...booking,bookingCode:'LATEST'}],meta:{total:1}});stale.flush({data:[booking],meta:{total:51}});expect(c.trips()[0].bookingCode).toBe('LATEST');f.destroy();});
  it('opens existing booking details without loading candidates or changing anything',async()=>{const f=await mount();f.componentInstance.openTrip(booking);http.expectOne(r=>r.url.endsWith('/dispatch/booking')).flush({data:booking});http.expectNone(r=>r.url.endsWith('/candidates'));expect(f.componentInstance.selected()?.id).toBe('booking');expect(f.componentInstance.pickerOpen()).toBe(false);f.destroy();});
  it('prefills the current driver independently of the candidate page and requires a different eligible replacement and reason',async()=>{const f=await mount();const c=f.componentInstance,b={...booking,driverId:'current',driverName:'Current Driver',status:'confirmed'};c.openAssignment(b);details(b);expect(c.assignment.driverId).toBe('current');expect(c.assignmentReady()).toBe(false);c.selectCandidate({...candidate,reasons:['Driver is offline']});expect(c.assignment.driverId).toBe('current');c.selectCandidate(candidate);expect(c.assignmentReady()).toBe(false);c.assignment.reason='Replacement requested';expect(c.assignmentReady()).toBe(true);f.detectChanges();expect(f.nativeElement.textContent).toContain('Current Driver');c.closeAssignment();expect(c.assignment.driverId).toBe('');http.expectNone(r=>r.method==='POST');f.destroy();});
  it('ignores stale candidate results and discards state on cancellation',async()=>{const f=await mount();const c=f.componentInstance;c.openAssignment(booking);http.expectOne(r=>r.url.endsWith('/dispatch/booking')).flush({data:booking});const old=http.expectOne(r=>r.url.endsWith('/candidates'));c.candidateSearch.set('Alice');c.findDispatchCandidates(true);const fresh=http.expectOne(r=>r.url.endsWith('/candidates'));expect(fresh.request.params.get('search')).toBe('Alice');fresh.flush({data:[candidate]});old.flush({data:[{...candidate,id:'stale'}]});expect(c.candidates()[0].id).toBe('replacement');c.closeAssignment();expect(c.candidates()).toEqual([]);f.destroy();});
  it('submits a versioned request once, closes only after success and preserves filters/page',async()=>{const f=await mount();const c=f.componentInstance;c.dispatchPage.set(3);c.dispatchSearch.set('Alice');c.openAssignment(booking);details();c.selectCandidate(candidate);c.assignment.reason='Dispatch reviewed';c.submitAssignment();c.submitAssignment();const req=http.expectOne(r=>r.url.endsWith('/assign'));expect(req.request.body).toMatchObject({driverId:'replacement',expectedDriverId:null,expectedUpdatedAt:booking.updatedAt,reason:'Dispatch reviewed'});expect(req.request.body.clientRequestId).toBeTruthy();expect(c.pickerOpen()).toBe(true);req.flush({data:{...booking,driverId:'replacement',status:'confirmed'}});expect(c.pickerOpen()).toBe(false);expect(c.assignmentSuccess()).toBe('Driver assigned.');const refresh=http.expectOne(r=>r.url.endsWith('/dispatch'));expect(refresh.request.params.get('page')).toBe('3');expect(refresh.request.params.get('search')).toBe('Alice');refresh.flush({data:[booking],meta:{total:51}});f.destroy();});
  it('a conflict shows no success and refreshes booking/candidates before another selection',async()=>{const f=await mount();const c=f.componentInstance;c.openAssignment(booking);details();c.selectCandidate(candidate);c.assignment.reason='Dispatch reviewed';c.submitAssignment();http.expectOne(r=>r.url.endsWith('/assign')).flush({error:{message:'Another dispatcher assigned this booking'}},{status:409,statusText:'Conflict'});await Promise.resolve();await Promise.resolve();expect(c.pickerOpen()).toBe(true);expect(c.assignmentSuccess()).toBe('');http.expectOne(r=>r.url.endsWith('/dispatch')).flush({data:[],meta:{total:0}});details({...booking,driverId:'winner',status:'confirmed'});expect(c.assignment.driverId).toBe('winner');expect(c.assignmentReady()).toBe(false);expect(c.assignmentError()).toContain('Another dispatcher');f.destroy();});
  it('does not label an automatic or historical request as customer preferred',async()=>{const f=await mount();const c=f.componentInstance;const automatic={...booking,offers:[{status:'pending',driver:{firstName:'Automatic'}}]};expect(c.preferenceLabel(automatic)).toBe('No recorded customer preference');expect(c.preferenceLabel({...automatic,offers:[{...automatic.offers[0],isCustomerPreference:true}]})).toContain('Preferred: Automatic');f.destroy();});
  it('denies mutation controls for read-only staff and terminal bookings',async()=>{const f=await mount(false);const c=f.componentInstance;c.openAssignment(booking);expect(c.pickerOpen()).toBe(false);expect(JSON.parse(c.dispatchActions).map((a:{event:string})=>a.event)).toEqual(['view']);http.expectNone(r=>r.method==='POST');f.destroy();});
  it.each(['completed','cancelled','in_progress'])('does not open assignment for %s',async status=>{const f=await mount();f.componentInstance.openAssignment({...booking,status});expect(f.componentInstance.pickerOpen()).toBe(false);http.expectNone(r=>r.url.endsWith('/dispatch/booking'));f.destroy();});
});
