import { Component, CUSTOM_ELEMENTS_SCHEMA, Injector, inject, signal, OnInit, input, output, DestroyRef } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { interval } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { DatePipe } from '@angular/common';
import { AuthService } from '@skylabs-monorepo/shared-auth/angular';
import { environment } from '../../../environments/environment';
import { AdminPage } from '../../admin/admin-page/admin-page';
import { httpErrorMessage } from '../../core/http-error';
import './dispatch-table';
import { BookingService } from '../../core/booking/booking.service';

interface Candidate {id:string;name:string;phone?:string;city?:string;driverType?:string;reasons:string[]}
interface Trip {updatedAt?:string;startsAt?:string|null;customerName?:string;driverName?:string;waitingFor?:{firstName:string;lastName?:string};offers?:{id?:string;driverId?:string;isCustomerPreference?:boolean|null;status:string;createdAt?:string;respondedAt?:string|null;expiresAt?:string|null;driver:{id?:string;firstName:string;lastName?:string}}[]; id:string; bookingCode:string; status:string; pickupAddress?:string; dropAddress?:string; scheduledAt?:string; tripTypeName?:string; farePaise?:number;estimatedFare?:number;finalFare?:number; paymentStatus?:string;paymentMode?:string; driverSharePaise?:number; driverId?:string; otp?:string; driver?:{id?:string;firstName:string;lastName?:string;phone?:string;city?:string;driverType?:string;languages:string[]}; events?:{id:string;status:string;reason?:string;createdAt:string}[]; commissionBps?:number; commissionPaise?:number; collected?:number; commission?:number; earned?:number; paid?:number; payable?:number; payoutStatus?:string; driverLocation?:{lat:number;lng:number;updatedAt:string}|null; city?:string|null; vehicleCategory?:string|null; pickupLat?:number|null; pickupLng?:number|null; dropLat?:number|null; dropLng?:number|null }
interface Movement { booking?:{bookingCode:string};driver?:{firstName:string;lastName?:string};actor?:{name:string}; id:string; reference:string; kind:string; amountPaise:number; createdAt:string; reason:string; bookingId?:string; driverId?:string; method:string }
interface Message { id:string;kind:string;subject:string;body:string;createdAt:string }
interface Overview { driver:{id:string;online:boolean;registrationFeePaise:number;registrationFeeRequired:boolean}; fee:string;reasons:string[];trips:Trip[];offers:{id:string;expiresAt:string|null;booking:Trip}[];movements:Movement[] }
interface Accounts {pendingActions?:Trip[];meta?:{total:number;page:number;pageSize:number}; totals:Record<string,number>;bookings:Trip[];movements:Movement[];dateRule:string;drivers:{id:string;firstName:string;registrationFeePaise:number;registrationFeeRequired:boolean;feeStatus:string}[];registrationSummary:Record<string,{count:number;amountPaise:number}>;activity?:{id:string;actor?:{name:string};actorUserId:string;action:string;targetId:string;createdAt:string;after:unknown}[] }
interface Fare {requiredDriverJobType?:string|null;requiredDriverJobChoice?:string|null;requiredDriverSkill?:string|null; id:string; zoneName:string;tripTypeName:string;vehicleCategoryName:string;commissionBps?:number|null }
@Component({ selector:'md-workflow', imports:[AdminPage,FormsModule,DatePipe], schemas:[CUSTOM_ELEMENTS_SCHEMA], templateUrl:'./workflow.html',
  styles:[`:host{display:block}.workflow-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.workflow-form{display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));align-items:end}label{display:grid;gap:6px;min-width:0}input,select,textarea{min-width:0;max-width:100%;box-sizing:border-box;font:inherit;padding:10px;border:1px solid var(--md-sys-color-outline,#aaa);border-radius:8px;background:var(--md-sys-color-surface,#fff);color:inherit}table{width:100%;border-collapse:collapse}td,th{padding:10px;text-align:left;border-bottom:1px solid #ddd}.table-wrap{overflow:auto}.error{color:var(--md-sys-color-error,#a00)}.actions{display:flex;gap:10px;flex-wrap:wrap}.card-link{border:0;text-align:left;cursor:pointer}.dispatch-dialog{width:min(760px,calc(100vw - 32px));max-height:90dvh}.dispatch-dialog [slot=content]{display:grid;gap:16px}.candidate-row{display:flex;align-items:flex-start;gap:12px;padding:12px;border:1px solid var(--md-sys-color-outline-variant);border-radius:8px}.candidate-row input{width:20px;height:20px;margin:3px 0}.candidate-row span{display:grid;gap:4px;min-width:0;overflow-wrap:anywhere}.candidate-row:has(input:checked){border-color:var(--md-sys-color-primary);background:var(--md-sys-color-primary-container)}.candidate-row:has(input:disabled){opacity:.75}.candidate-list{display:grid;gap:8px}.dispatch-summary p{margin:6px 0}.dispatch-filters{margin:12px 0}.dispatch-dialog md-outlined-text-field{width:100%}@media(max-width:600px){.dispatch-dialog{width:calc(100vw - 16px)}.workflow-form{grid-template-columns:1fr}}`] })
export class Workflow implements OnInit {
  readonly Math=Math;readonly dispatchPage=signal(1);readonly dispatchPageSize=signal(25);readonly dispatchSort=signal('createdAt');readonly dispatchDirection=signal<'asc'|'desc'>('desc');readonly dispatchSearch=signal('');readonly dispatchTotal=signal(0);readonly dispatchStatus=signal('');readonly dispatchFrom=signal('');readonly dispatchTo=signal('');readonly pickerOpen=signal(false);readonly dispatchFiltersOpen=signal(false);readonly dispatchQuick=signal('all');readonly dispatchLoading=signal(false);readonly candidateLoading=signal(false);readonly candidateError=signal('');readonly assignmentError=signal('');readonly assignmentSuccess=signal('');readonly dialogBooking=signal<Trip|null>(null);readonly dialogLoading=signal(false);readonly pickedCandidate=signal<Candidate|null>(null);private dispatchSequence=0;private candidateSequence=0;private dialogSequence=0;private assignmentRequestId='';readonly jobMasters=signal<Partial<Record<string,{name:string;status:string}[]>>>({});
  private readonly destroyRef=inject(DestroyRef);
  private readonly http=inject(HttpClient);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);readonly auth=inject(AuthService);private readonly injector=inject(Injector);
  readonly changed=output<void>();
  readonly embedded=input<string>(); readonly mode=signal('');readonly title=signal('');readonly error=signal('');readonly busy=signal(false);
  readonly staffDriverId=input<string>();
  readonly preset=input<{fareId?:string;pickupAddress?:string;dropAddress?:string;startsAt?:string;preferredDriverId?:string;pickupLat?:number;pickupLng?:number;dropLat?:number;dropLng?:number}>();readonly selectedFare=signal('');
  readonly trips=signal<Trip[]>([]);readonly overview=signal<Overview|null>(null);readonly accounts=signal<Accounts|null>(null);readonly movements=signal<Movement[]>([]);readonly messages=signal<Message[]>([]);readonly fares=signal<Fare[]>([]);readonly selected=signal<Trip|null>(null);
  readonly view=signal('Upcoming');readonly drilldown=signal('Overview');readonly accountPage=signal(1);readonly accountSearch=signal('');readonly candidatePage=signal(1);readonly candidateSearch=signal('');readonly preferredDriverId=signal('');readonly financeConfirmed=signal(false);readonly base=`${environment.apiUrl}/workflow`;
  readonly candidates=signal<Candidate[]>([]);
  readonly selectedFeeDriver=signal('');feePolicy={amountRupees:0,driverId:'',registrationFeeRequired:false,registrationFeePaise:0,reason:''};
  commissionPolicy={requiredDriverJobType:'',requiredDriverJobChoice:'',requiredDriverSkill:'',rate:0,fareId:'',commissionBps:0,reason:''};
  booking:{city:string;service:string;vehicleCategory:string;pickupAddress:string;dropAddress:string;startsAt:string;durationMinutes:number;distanceKm:number;requiredSkill:string;paymentMode:string;pickupLat?:number;pickupLng?:number;dropLat?:number;dropLng?:number}={city:'',service:'',vehicleCategory:'',pickupAddress:'',dropAddress:'',startsAt:'',durationMinutes:60,distanceKm:0,requiredSkill:'',paymentMode:'cash'};
  quote=signal<number|null>(null);support={subject:'',body:''};filters={from:'',to:'',city:'',service:'',paymentStatus:''};
  finance={amountRupees:0,reference:'',bookingId:'',driverId:'',kind:'booking_payment',amountPaise:0,method:'cash',reason:''};assignment={driverId:'',reason:''};otp='';cancelReason='';
  ngOnInit(){this.route.data.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(data=>{this.mode.set(this.embedded()??data['mode']??'bookings');this.title.set(this.embedded()?this.heading(this.mode()):data['section']?'Accounts · '+data['section']:data['title']??this.heading(this.mode()));this.drilldown.set(data['section']??'Overview');if(data['section']==='Commissions'&&this.auth.can('payments.overview','edit'))this.loadJobMasters();this.accountPage.set(1);this.selected.set(null);this.finance.kind=this.allowedKinds()[0]??'booking_payment';const view=this.route.snapshot?.queryParamMap?.get('view');if(view&&['Upcoming','Completed','Ongoing','Cancelled'].includes(view))this.view.set(view);this.load();});interval(15000).pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>{if(!this.busy()&&['bookings','customerSummary','trips','requests','driverSummary','dispatch','notifications'].includes(this.mode()))this.load();});}
  heading(mode:string){return ({book:'Book a Driver',bookings:'My Bookings',customerSummary:'Your trips & recent activity',payments:'Payments & Invoices',availability:'Availability',requests:'Trip Requests',trips:'My Trips',earnings:'Earnings',fee:'Registration Fee',notifications:'Notifications',support:'Help & Support',dispatch:'Admin Dispatch',accounts:'Accounts',driverSummary:'Trip readiness & requests'} as Record<string,string>)[mode]??'Accounts';}
  private get<T>(path:string,next:(data:T)=>void,params?:HttpParams){this.http.get<{data:T}>(`${this.base}/${path}`,{params}).subscribe({next:r=>next(r.data),error:e=>this.error.set(e.error?.error?.message??'Unable to load data')});}
  load(){this.error.set('');const mode=this.mode();
    if(['bookings','customerSummary'].includes(mode))this.get<Trip[]>('customer/bookings',rows=>this.trips.set(rows));
    if(mode==='book')this.get<Fare[]>('customer/pricing',rows=>{this.fares.set(rows);const preset=this.preset();if(preset){this.booking.pickupAddress=preset.pickupAddress??'';this.booking.dropAddress=preset.dropAddress??'';this.booking.startsAt=preset.startsAt??'';this.booking.pickupLat=preset.pickupLat;this.booking.pickupLng=preset.pickupLng;this.booking.dropLat=preset.dropLat;this.booking.dropLng=preset.dropLng;if(preset.fareId)this.setFare(preset.fareId);if(preset.preferredDriverId)this.preferredDriverId.set(preset.preferredDriverId);}});
    if(mode==='payments'){this.get<Movement[]>('customer/payments',rows=>this.movements.set(rows));this.get<Trip[]>('customer/bookings',rows=>this.trips.set(rows));}
    if(['availability','requests','trips','earnings','fee','driverSummary'].includes(mode))this.get<Overview>('driver/overview',data=>{this.overview.set(data);this.trips.set(data.trips);this.movements.set(data.movements);});
    if(mode==='driverDetail'&&this.staffDriverId())this.get<Overview>(`drivers/${this.staffDriverId()}/overview`,data=>{this.overview.set(data);this.trips.set(data.trips);this.movements.set(data.movements);});
    if(['notifications','support'].includes(mode))this.get<Message[]>('messages',rows=>this.messages.set(rows.filter(m=>m.kind===(mode==='support'?'support':'notification'))));
    if(mode==='dispatch'){const sequence=++this.dispatchSequence;this.dispatchLoading.set(true);let params=new HttpParams().set('page',this.dispatchPage()).set('pageSize',this.dispatchPageSize()).set('sort',this.dispatchSort()).set('direction',this.dispatchDirection()).set('search',this.dispatchSearch()).set('quick',this.dispatchQuick());for(const[key,value]of Object.entries({status:this.dispatchStatus(),from:this.dispatchFrom(),to:this.dispatchTo()}))if(value)params=params.set(key,value);this.http.get<{data:Trip[];meta:{total:number}}>(this.base+'/dispatch',{params}).subscribe({next:response=>{if(sequence!==this.dispatchSequence)return;this.dispatchLoading.set(false);this.trips.set(response.data);this.dispatchTotal.set(response.meta.total);if(this.dispatchPage()>1&&!response.data.length&&response.meta.total<(this.dispatchPage()-1)*this.dispatchPageSize()+1){this.dispatchPage.set(Math.max(1,Math.ceil(response.meta.total/this.dispatchPageSize())));this.load();}},error:async error=>{const message=await httpErrorMessage(error);if(sequence===this.dispatchSequence){this.dispatchLoading.set(false);this.error.set(message);}}});}
    if(mode==='accounts'){let params=new HttpParams();for(const [key,value]of Object.entries(this.filters))if(value)params=params.set(key,value);params=params.set('section',this.drilldown()).set('page',this.accountPage()).set('pageSize',25).set('search',this.accountSearch());this.get<Accounts>('accounts',data=>{this.accounts.set(data);this.trips.set(data.bookings);this.movements.set(data.movements);},params);if(this.drilldown()==='Commissions'&&this.auth.can('payments.overview','edit'))this.get<Fare[]>('accounts/pricing',rows=>this.fares.set(rows));}
  }
  resendOtp(bookingId:string){if(this.busy())return;this.busy.set(true);this.error.set('');this.http.post<{data:Trip}>(`${this.base}/customer/bookings/${bookingId}/otp/resend`,{}).subscribe({next:r=>{this.busy.set(false);this.selected.set(r.data);this.load();},error:async e=>{this.busy.set(false);this.error.set(await httpErrorMessage(e));}});}
  act(path:string,body:unknown,method:'post'|'patch'='post',done?:()=>void){if(this.busy())return;this.busy.set(true);this.error.set('');this.http.request<{data:unknown}>(method,`${this.base}/${path}`,{body}).subscribe({next:()=>{this.busy.set(false);this.selected.set(null);if(this.mode()==='trips'&&path.endsWith('/status')){const status=(body as {status:string}).status;this.view.set(status==='completed'?'Completed':status==='cancelled'?'Cancelled':'Ongoing');}this.load();done?.();this.changed.emit();},error:e=>{this.busy.set(false);this.error.set(e.error?.error?.message??'Action failed');}});}
  selectCommissionRule(id:string){this.commissionPolicy.fareId=id;const fare=this.fares().find(rule=>rule.id===id);if(fare){this.commissionPolicy.rate=(fare.commissionBps??0)/100;this.commissionPolicy.requiredDriverSkill=fare.requiredDriverSkill??'';this.commissionPolicy.requiredDriverJobType=fare.requiredDriverJobType??'';this.commissionPolicy.requiredDriverJobChoice=fare.requiredDriverJobChoice??'';}}
  setFare(id:string){this.selectedFare.set(id);const fare=this.fares().find(f=>f.id===id);if(fare){this.booking.city=fare.zoneName;this.booking.service=fare.tripTypeName;this.booking.vehicleCategory=fare.vehicleCategoryName;}this.quote.set(null);this.preferredDriverId.set('');this.candidates.set([]);this.bookingRequestId='';}
  bookInput(){return {...this.booking,startsAt:new Date(this.booking.startsAt).toISOString(),preferredDriverId:this.preferredDriverId()||undefined,requiredSkill:this.booking.requiredSkill||undefined};}
  /** Stable per-attempt key: the same value survives a retry (network error, "try again")
   *  so the backend's idempotency check can return the already-created booking instead of a
   *  duplicate; a genuinely new attempt (new fare picked, or a prior booking succeeded) gets
   *  a fresh one. Only `/customer/bookings` accepts this field — `/customer/quote` and
   *  `/customer/candidates` use the plain `.strict()` schema and would reject an extra key. */
  private bookingRequestId='';
  private createInput(){if(!this.bookingRequestId)this.bookingRequestId=crypto.randomUUID();return {...this.bookInput(),clientRequestId:this.bookingRequestId};}
  price(){try{this.http.post<{data:{farePaise:number}}>(`${this.base}/customer/quote`,this.bookInput()).subscribe({next:r=>{this.quote.set(r.data.farePaise);this.preferredDriverId.set('');this.findCandidates(true);},error:e=>this.error.set(e.error?.error?.message??'Unable to calculate price')});}catch{this.error.set('Choose a valid pickup time');}}
  create(){if(this.busy())return;try{const input=this.createInput();this.busy.set(true);this.http.post<{data:Trip}>(`${this.base}/customer/bookings`,input).subscribe({next:r=>{this.busy.set(false);this.quote.set(null);this.bookingRequestId='';if(input.paymentMode==='razorpay')void this.pay(r.data.id);else this.error.set('Booking saved. Cash on Delivery collection pending. Open My Bookings to follow assignment.');},error:async e=>{this.busy.set(false);this.error.set(await httpErrorMessage(e));}});}catch{this.error.set('Choose a valid pickup time');}}
  paymentMethod(b:Trip){return b.paymentMode==='cash'?'Cash on Delivery (COD)':b.paymentMode==='razorpay'?'Razorpay':b.paymentMode??'Not specified';}
  money(value:number|undefined){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format((value??0)/100);}
  status(status:string){return ({accepted:'Accepted',driver_arrived:'Driver arrived',ongoing:'Ongoing',requested:'Finding a driver',confirmed:'Confirmed',on_the_way:'On the way',arrived:'Arrived',in_progress:'In progress',completed:'Completed',cancelled:'Cancelled'} as Record<string,string>)[status]??status;}
  /** COD only ever reaches "Paid" through a staff-recorded collection, and online payment
   *  only through the server-verified Razorpay flow — this just labels whatever state the
   *  backend already settled on, never implies a payment the backend hasn't confirmed. */
  paymentStatusLabel(status?:string){return ({unpaid:'Unpaid',pending:'Payment pending',paid:'Paid',partial:'Partially paid',refunded:'Refunded',failed:'Payment failed'} as Record<string,string>)[status??'']??status??'Unknown';}
  /** Honest freshness, never presented as "live" without a real recent timestamp. */
  locationFreshness(location:{updatedAt:string}|null|undefined){if(!location)return null;const ageMs=Date.now()-new Date(location.updatedAt).getTime();if(!Number.isFinite(ageMs))return null;const minutes=Math.round(ageMs/60000);return minutes<1?'just now':minutes===1?'1 min ago':minutes<60?`${minutes} min ago`:'over an hour ago';}
  /** Opens the real public booking flow prefilled with this past trip's pickup/drop — the
   *  flow from there re-runs quote/candidates/serviceability fresh, exactly like a new
   *  booking; nothing here is treated as already-validated or auto-confirmed. Older bookings
   *  made before coordinates were captured have none to prefill — those start fresh rather
   *  than inventing a location. */
  bookAgain(trip:Trip){
    // Resolved lazily (not a field-level `inject`) so instantiating `Workflow` in any other
    // mode (admin dispatch/accounts, driver trips) never pulls in the rider booking
    // singleton's own HTTP call / auth effect — only an actual "Book again" click does.
    const rideBooking=this.injector.get(BookingService);
    if(trip.pickupLat!=null&&trip.pickupLng!=null&&trip.dropLat!=null&&trip.dropLng!=null){
      rideBooking.setPickup({id:'repeat-pickup',label:trip.pickupAddress??'Pickup',address:trip.pickupAddress??'',coord:{lat:trip.pickupLat,lng:trip.pickupLng},kind:'recent'});
      rideBooking.setDrop({id:'repeat-drop',label:trip.dropAddress??'Drop',address:trip.dropAddress??'',coord:{lat:trip.dropLat,lng:trip.dropLng},kind:'recent'});
      void this.router.navigate(['/ride/options']);
    } else {
      void this.router.navigate(['/ride']);
    }
  }
  fare(b:Trip){const value=b.farePaise??(b.finalFare!=null?Math.round(b.finalFare*100):b.estimatedFare!=null?Math.round(b.estimatedFare*100):undefined);return value==null?'Not provided':this.money(value);}
  visibleTrips(){if(this.mode()==='customerSummary')return [...this.trips()].sort((a,b)=>Number(['requested','confirmed','on_the_way','arrived','in_progress'].includes(b.status))-Number(['requested','confirmed','on_the_way','arrived','in_progress'].includes(a.status))).slice(0,5);return this.trips().filter(b=>this.route.snapshot?.queryParamMap?.get('timing')!=='upcoming'||this.view()!=='Upcoming'||(b.startsAt&&Date.parse(b.startsAt)>=Date.now()&&(this.mode()==='trips'?['confirmed','on_the_way','arrived']:['requested','confirmed','on_the_way','arrived']).includes(b.status))).filter(b=>(this.route.snapshot?.queryParamMap?.get('timing')==='upcoming'&&this.view()==='Upcoming')||this.mode()==='dispatch'||this.mode()==='accounts'||(this.view()==='Completed'?b.status==='completed':this.view()==='Cancelled'?b.status==='cancelled':this.view()==='Ongoing'?['on_the_way','arrived','in_progress'].includes(b.status):['requested','confirmed'].includes(b.status)));}
  nextStatus(b:Trip){return ({confirmed:'on_the_way',on_the_way:'arrived',arrived:'in_progress',in_progress:'completed'} as Record<string,string>)[b.status];}
  financialAction(){if(!this.financeConfirmed()){this.error.set('Confirm the actual collection or completed transfer first');return;}const {amountRupees,...values}=this.finance;const body={confirmed:true,...values,amountPaise:Math.round(amountRupees*100),bookingId:this.finance.bookingId||undefined,driverId:this.finance.driverId||undefined};this.act('accounts/movements',body);}

  openTrip(b:Trip){this.selected.set(b);if(this.mode()==='dispatch'){const sequence=++this.dialogSequence;this.http.get<{data:Trip}>(`${this.base}/dispatch/${b.id}`).subscribe({next:r=>{if(sequence===this.dialogSequence&&this.selected()?.id===b.id)this.selected.set(r.data);},error:async e=>{if(sequence===this.dialogSequence)this.error.set(await httpErrorMessage(e));}});}}
  canAssign(b:Trip){return this.auth.can('trips.bookings','edit')&&['requested','confirmed','on_the_way','arrived'].includes(b.status);}
  preferred(b:Trip){return b.offers?.find(offer=>offer.isCustomerPreference===true);}
  preferenceLabel(b:Trip){const offer=this.preferred(b);return offer?`Preferred: ${offer.driver.firstName} ${offer.driver.lastName??''} · ${offer.status}`:'No recorded customer preference';}
  quickFilter(value:string){this.dispatchQuick.set(value);this.dispatchPage.set(1);this.load();}
  applyDispatchFilters(){if(this.dispatchFrom()&&this.dispatchTo()&&this.dispatchFrom()>this.dispatchTo()){this.error.set('Schedule From must not be after Schedule To');return;}this.dispatchPage.set(1);this.load();}
  clearDispatchFilters(){this.dispatchStatus.set('');this.dispatchFrom.set('');this.dispatchTo.set('');this.dispatchPage.set(1);this.load();}
  openAssignment(b:Trip){if(!this.canAssign(b)||this.busy())return;this.selected.set(null);this.dialogBooking.set(b);this.assignment={driverId:b.driverId??'',reason:''};this.pickedCandidate.set(null);this.candidates.set([]);this.candidatePage.set(1);this.candidateSearch.set('');this.assignmentError.set('');this.candidateError.set('');this.assignmentRequestId=crypto.randomUUID();this.pickerOpen.set(true);this.refreshDialog();}
  closeAssignment(){if(this.busy())return;this.pickerOpen.set(false);++this.dialogSequence;++this.candidateSequence;this.dialogBooking.set(null);this.assignment={driverId:'',reason:''};this.pickedCandidate.set(null);this.candidates.set([]);this.assignmentError.set('');this.candidateError.set('');this.candidateLoading.set(false);this.dialogLoading.set(false);}
  cancelAssignment(event:Event){if(this.busy())event.preventDefault();else this.closeAssignment();}
  refreshDialog(){const b=this.dialogBooking();if(!b)return;const sequence=++this.dialogSequence;this.dialogLoading.set(true);this.http.get<{data:Trip}>(`${this.base}/dispatch/${b.id}`).subscribe({next:r=>{if(sequence!==this.dialogSequence||!this.pickerOpen())return;this.dialogLoading.set(false);this.dialogBooking.set(r.data);this.assignment.driverId=r.data.driverId??'';this.pickedCandidate.set(null);this.findDispatchCandidates();},error:async e=>{const message=await httpErrorMessage(e);if(sequence===this.dialogSequence){this.dialogLoading.set(false);this.assignmentError.set(message);}}});}
  findDispatchCandidates(reset=false){if(reset)this.candidatePage.set(1);const b=this.dialogBooking();if(!b||!this.pickerOpen())return;const sequence=++this.candidateSequence;this.candidateLoading.set(true);this.candidateError.set('');this.candidates.set([]);this.http.get<{data:Candidate[]}>(`${this.base}/dispatch/${b.id}/candidates`,{params:new HttpParams().set('search',this.candidateSearch()).set('page',this.candidatePage()).set('pageSize',10)}).subscribe({next:r=>{if(sequence!==this.candidateSequence||!this.pickerOpen())return;this.candidates.set(r.data);this.candidateLoading.set(false);const picked=this.pickedCandidate();if(picked){const refreshed=r.data.find(c=>c.id===picked.id);if(refreshed)this.pickedCandidate.set(refreshed);}},error:async e=>{const message=await httpErrorMessage(e);if(sequence===this.candidateSequence){this.candidateError.set(message);this.candidateLoading.set(false);}}});}
  candidateOnPage(id:string){return this.candidates().some(candidate=>candidate.id===id);}
  selectCandidate(candidate:Candidate){if(candidate.reasons.length||this.busy())return;this.assignment.driverId=candidate.id;this.pickedCandidate.set(candidate);this.assignmentRequestId=crypto.randomUUID();}
  assignmentReady(){const b=this.dialogBooking(),picked=this.pickedCandidate();return !!b&&this.canAssign(b)&&!!b.updatedAt&&!this.dialogLoading()&&!this.candidateLoading()&&!this.candidateError()&&!this.busy()&&!!picked&&!picked.reasons.length&&picked.id===this.assignment.driverId&&picked.id!==b.driverId&&!!this.assignment.reason.trim()&&this.assignment.reason.trim().length<=2000;}
  submitAssignment(){if(!this.assignmentReady())return;const b=this.dialogBooking()!;this.busy.set(true);this.assignmentError.set('');this.assignmentSuccess.set('');this.http.post<{data:Trip}>(`${this.base}/dispatch/${b.id}/assign`,{...this.assignment,reason:this.assignment.reason.trim(),expectedDriverId:b.driverId??null,expectedUpdatedAt:b.updatedAt,clientRequestId:this.assignmentRequestId}).subscribe({next:()=>{this.busy.set(false);this.closeAssignment();this.assignmentSuccess.set(b.driverId?'Driver reassigned.':'Driver assigned.');this.load();this.changed.emit();},error:async e=>{this.busy.set(false);this.assignmentError.set(await httpErrorMessage(e));this.load();this.refreshDialog();}});}

  downloadInvoice(b:Trip){this.download(`customer/bookings/${b.id}/invoice.pdf`,`invoice-${b.bookingCode}.pdf`);}
  downloadReport(){let query=new URLSearchParams();for(const[key,value]of Object.entries(this.filters))if(value)query.set(key,value);this.download(`accounts/report.csv?${query.toString()}`,'accounts-report.csv');}
  private download(path:string,name:string){this.http.get(`${this.base}/${path}`,{responseType:'blob'}).subscribe({next:blob=>{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);},error:async e=>this.error.set(await httpErrorMessage(e))});}
  allowedKinds(){return this.drilldown()==='Registration Fees'?['registration_payment','registration_refund','registration_waiver']:this.drilldown()==='Driver Payouts'?['driver_payout']:this.drilldown()==='Commissions'?['commission_settlement']:this.drilldown()==='Refunds & Adjustments'?['booking_refund','driver_cod_refund','commission_refund','driver_recovery','registration_refund','registration_waiver']:this.drilldown()==='Booking Payments'?['booking_payment','driver_cod_collection']:[];}
  goAccount(label:string){const path=({'Total Bookings':'booking-payments','Total Collected':'booking-payments','Total Commission':'commissions','Platform Income':'reports','Driver Payable':'driver-payouts','Driver Paid':'driver-payouts','Registration Fees':'registration-fees','Commission Receivable':'commissions','Driver Share Retained':'driver-payouts'} as Record<string,string>)[label];void this.router.navigate(['/account/accounts',path??'overview']);}
  accountParams(event:Event){const detail=(event as CustomEvent).detail;this.accountPage.set(detail.page);this.accountSearch.set(detail.search??'');this.load();}
  readonly accountColumns=JSON.stringify([{key:'bookingCode',sortable:true,label:'Booking'},{key:'customerName',sortable:true,label:'Customer'},{key:'fareLabel',label:'Customer amount'},{key:'rateLabel',label:'Commission rate'},{key:'commissionLabel',label:'Commission'},{key:'earnedLabel',label:'Driver share'},{key:'collectorLabel',label:'Collected by'},{key:'collectedLabel',label:'Platform received'},{key:'codLabel',label:'Driver COD collected'},{key:'receivableLabel',label:'Commission receivable'},{key:'paymentLabel',label:'Payment'},{key:'payoutStatus',label:'Settlement'}]);
  accountRows(){return JSON.stringify(this.accountBookings().map(b=>({...b,fareLabel:this.fare(b),rateLabel:((b as any).commissionBps??0)/100+'%',commissionLabel:this.money(b.commission),earnedLabel:this.money(b.earned),collectorLabel:(b as any).driverCollected>0?'Driver '+((b as any).driverName??''):(b.collected??0)>0?'Platform':'Collection pending',codLabel:this.money((b as any).driverCollected),collectedLabel:this.money(b.collected),receivableLabel:this.money((b as any).commissionReceivable),paymentLabel:this.paymentMethod(b)+' / '+b.paymentStatus})));}
  accountRowAction(event:Event){const row=(event as CustomEvent).detail.row;if(this.drilldown()==='Registration Fees'){this.feePolicy.driverId=row.id;this.finance.driverId=row.id;this.feePolicy.registrationFeeRequired=row.registrationFeeRequired;this.feePolicy.amountRupees=row.registrationFeePaise/100;this.selectedFeeDriver.set(row.name);return;}const booking=this.trips().find(b=>b.id===row.id);if(booking){this.finance.bookingId=booking.id;this.finance.driverId=booking.driverId??'';this.openTrip(booking);}}
  readonly feeActions=JSON.stringify([{icon:'visibility',label:'Select fee record',event:'fee'}]);
  readonly feeColumns=JSON.stringify([{key:'name',label:'Driver'},{key:'feeStatus',label:'Fee status'},{key:'amountLabel',label:'Configured fee'},{key:'policy',label:'Trip requirement'}]);
  feeRows(){return JSON.stringify((this.accounts()?.drivers??[]).map(driver=>({...driver,name:driver.firstName+' '+((driver as any).lastName??''),amountLabel:this.money(driver.registrationFeePaise),policy:driver.registrationFeeRequired?'Required':'Optional'})));}
  feePage(direction:number){this.accountPage.update(page=>Math.max(1,page+direction));this.load();}
  readonly accountActions=JSON.stringify([{icon:'visibility',label:'View booking',event:'view'}]);
  findCandidates(reset=false){if(reset)this.candidatePage.set(1);this.error.set('');if(this.mode()==='book'){try{this.http.post<{data:{id:string;name:string;reasons:string[]}[]}>(this.base+'/customer/candidates',{...this.bookInput(),page:this.candidatePage()}).subscribe({next:r=>this.candidates.set(r.data),error:async e=>this.error.set(await httpErrorMessage(e))});}catch{this.error.set('Choose a valid pickup schedule');}}else if(this.selected()){let params=new HttpParams().set('search',this.candidateSearch()).set('page',this.candidatePage());this.get<{id:string;name:string;reasons:string[]}[]>('dispatch/'+this.selected()!.id+'/candidates',rows=>this.candidates.set(rows),params);}}
  nextCandidates(direction:number){this.candidatePage.update(page=>Math.max(1,page+direction));this.findCandidates();}
  shownMovements(){const section=this.drilldown();const kinds=section==='Booking Payments'||section==='Total Collected'?['booking_payment','driver_cod_collection']:section==='Driver Payouts'||section==='Driver Paid'?['driver_payout']:section==='Refunds & Adjustments'?['booking_refund','driver_cod_refund','commission_refund','driver_recovery','registration_refund','registration_waiver']:section==='Registration Fees'?['registration_payment','registration_refund','registration_waiver']:null;return kinds?this.movements().filter(m=>kinds.includes(m.kind)):this.movements();}
  accountBookings(){const section=this.drilldown();return this.trips().filter(b=>section==='Total Commission'||section==='Commissions'?(b.commission??0)>0:section==='Driver Payable'?(b.payable??0)>0:section==='Driver Paid'||section==='Driver Payouts'?(b.earned??0)>0:section==='Registration Fees'?false:true);}
  auditDetails(value:unknown){const data=value as {reason?:string;reference?:string};return [data?.reference,data?.reason].filter(Boolean).join(' / ');}
  async pay(bookingId?:string){
    if(this.busy())return;this.busy.set(true);this.error.set('');
    try{
      const providerWindow=window as unknown as {Razorpay?:new(options:Record<string,unknown>)=>{open():void;on(event:string,handler:()=>void):void}};
      if(!providerWindow.Razorpay)await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=()=>resolve();script.onerror=()=>reject(new Error('Unable to load the payment gateway'));document.head.appendChild(script);});
      this.http.post<{data:{orderId:string;keyId:string;amountPaise:number}}>(`${this.base}/${bookingId?'customer':'driver'}/payment-order`,bookingId?{bookingId}:{}).subscribe({next:r=>{
        const checkout=new providerWindow.Razorpay!({key:r.data.keyId,order_id:r.data.orderId,amount:r.data.amountPaise,currency:'INR',name:'Mera Driver',
          handler:(result:{razorpay_payment_id:string;razorpay_order_id:string;razorpay_signature:string})=>{this.busy.set(false);this.act('payment-confirm',{paymentId:result.razorpay_payment_id,orderId:result.razorpay_order_id,signature:result.razorpay_signature});},modal:{ondismiss:()=>{this.busy.set(false);this.error.set('Payment cancelled. Booking remains unpaid until backend confirmation.');}}});checkout.on('payment.failed',()=>{this.busy.set(false);this.error.set('Payment failed. No collection recorded. Retry or contact support if money was debited.');});checkout.open();
      },error:e=>{this.busy.set(false);this.error.set(e.error?.error?.message??'Unable to start payment');}});
    }catch(e){this.busy.set(false);this.error.set(e instanceof Error?e.message:'Unable to start payment');}
  }
  financialKind(kind:string){return ({booking_payment:'Customer payment received by platform',driver_cod_collection:'COD collected by driver',commission_settlement:'COD commission received',driver_payout:'Driver payout confirmed',commission_refund:'COD commission returned to driver',driver_recovery:'Driver funds recovered',booking_refund:'Customer refund confirmed',driver_cod_refund:'Driver COD refund confirmed',registration_payment:'Registration fee received',registration_refund:'Registration fee refunded',registration_waiver:'Registration fee waived'} as Record<string,string>)[kind]??kind;}
  readonly dispatchColumns=JSON.stringify([{key:'bookingLabel',sortable:true,label:'Booking / Customer'},{key:'routeLabel',label:'Pickup → Drop'},{key:'scheduleLabel',sortable:true,label:'Schedule / Service'},{key:'fareLabel',label:'Fare / Payment'},{key:'driverLabel',sortable:true,label:'Driver / Status'},{key:'customerName',sortable:true,label:'Customer',hidden:true}]);
  get dispatchActions(){return JSON.stringify([{icon:'visibility',label:'View',event:'view'},...(this.auth.can('trips.bookings','edit')?[{icon:'person_add',label:'Assign',event:'assign'},{icon:'sync',label:'Reassign',event:'reassign'}]:[])]);}
  dispatchRows(){return JSON.stringify(this.trips().map(b=>({...b,assignable:this.canAssign(b),bookingLabel:`${b.bookingCode}\n${b.customerName??'Customer unavailable'}`,routeLabel:`Pickup: ${b.pickupAddress??'Not provided'}\nDrop: ${b.dropAddress??'Not provided'}`,scheduleLabel:`${(b.startsAt??b.scheduledAt)&&!Number.isNaN(Date.parse((b.startsAt??b.scheduledAt)!))?new Date((b.startsAt??b.scheduledAt)!).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Not scheduled'}\n${b.tripTypeName??'Service not provided'}`,fareLabel:`${this.fare(b)}\n${this.paymentMethod(b)} · ${this.paymentStatusLabel(b.paymentStatus)}`,driverLabel:`${b.driverName||(b.driverId?'Assigned driver':'Unassigned')} · ${this.status(b.status)}${this.preferred(b)?'\n'+this.preferenceLabel(b):''}`})));}
  dispatchParams(event:Event){const detail=(event as CustomEvent).detail;this.dispatchPage.set(detail.page??1);this.dispatchPageSize.set(detail.pageSize??25);const fields:Record<string,string>={bookingLabel:'bookingCode',bookingCode:'bookingCode',customerName:'customerName',driverLabel:'status',statusLabel:'status',scheduleLabel:'startsAt'};this.dispatchSort.set(fields[detail.sortKey]??'createdAt');this.dispatchDirection.set(detail.sortDir==='asc'?'asc':'desc');this.dispatchSearch.set(detail.search??'');this.load();}
  dispatchRowAction(event:Event){const detail=(event as CustomEvent).detail;const b=this.trips().find(row=>row.id===detail.row.id);if(b){if(detail.action==='view')this.openTrip(b);else if(['assign','reassign'].includes(detail.action))this.openAssignment(b);}}

  loadJobMasters(){this.http.get<{data:Record<string,{name:string;status:string}[]>}>(environment.apiUrl+'/masters/onboarding-options').subscribe({next:response=>this.jobMasters.set(response.data),error:async error=>this.error.set(await httpErrorMessage(error))});}
  changeDispatchPage(direction:number){this.dispatchPage.update(page=>Math.max(1,page+direction));this.load();}
  earnings(){const rows=this.overview()?.trips??[];return rows.filter(b=>b.status==='completed'&&b.paymentStatus==='paid').reduce((s,b)=>s+(b.driverSharePaise??0),0);}
}
