import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { of } from 'rxjs';
import { AuthService } from '@skylabs-monorepo/shared-auth/angular';
import { Workflow } from './workflow';
import { DRIVER_NAV_ITEMS } from '../../layouts/driver-layout/driver-layout';
import { CUSTOMER_NAV_ITEMS } from '../../layouts/customer-layout/customer-layout';

describe('connected portal workflow',()=>{
 let http:HttpTestingController;
 async function mount(mode:string,section?:string){await TestBed.configureTestingModule({imports:[Workflow],providers:[provideRouter([]),provideHttpClient(),provideHttpClientTesting(),{provide:ActivatedRoute,useValue:{data:of({mode,section})}},{provide:AuthService,useValue:{can:()=>false}}]}).compileComponents();const fixture=TestBed.createComponent(Workflow);http=TestBed.inject(HttpTestingController);fixture.detectChanges();return fixture;}
 afterEach(()=>{http?.verify();TestBed.resetTestingModule();});
 it('includes each requested portal menu without staff routes',()=>{expect(CUSTOMER_NAV_ITEMS.map(n=>n.label)).toEqual(['My Dashboard','Book a Driver','My Bookings','Payments & Invoices','My Profile','Help & Support']);expect(DRIVER_NAV_ITEMS.map(n=>n.label)).toContain('Trip Requests');expect(DRIVER_NAV_ITEMS.map(n=>n.label)).toContain('Registration Fee');expect([...DRIVER_NAV_ITEMS,...CUSTOMER_NAV_ITEMS].every(n=>!n.path.startsWith('/account'))).toBe(true);});
 it('reads own bookings and separates completed from ongoing',async()=>{const fixture=await mount('bookings');http.expectOne(r=>r.url.endsWith('/workflow/customer/bookings')).flush({data:[{id:'b1',status:'completed',bookingCode:'DONE'},{id:'b2',status:'arrived',bookingCode:'ACTIVE'}]});fixture.componentInstance.view.set('Ongoing');expect(fixture.componentInstance.visibleTrips().map(b=>b.id)).toEqual(['b2']);fixture.componentInstance.view.set('Completed');expect(fixture.componentInstance.visibleTrips().map(b=>b.id)).toEqual(['b1']);fixture.destroy();});
 it('dashboard includes ongoing work and displays actual legacy fare',async()=>{const fixture=await mount('customerSummary');http.expectOne(r=>r.url.endsWith('/workflow/customer/bookings')).flush({data:[{id:'old',status:'completed'},{id:'active',status:'in_progress',estimatedFare:1000}]});expect(fixture.componentInstance.visibleTrips()[0].id).toBe('active');expect(fixture.componentInstance.fare(fixture.componentInstance.visibleTrips()[0])).toBe('₹1,000.00');fixture.destroy();});
 it('Payments & Invoices loads owned bookings and real receipt records',async()=>{const fixture=await mount('payments');http.expectOne(r=>r.url.endsWith('/workflow/customer/bookings')).flush({data:[{id:'mine',bookingCode:'MY-INVOICE',status:'completed',paymentStatus:'paid'}]});http.expectOne(r=>r.url.endsWith('/workflow/customer/payments')).flush({data:[]});fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('MY-INVOICE');expect(fixture.nativeElement.textContent).toContain('Download invoice');expect(fixture.nativeElement.textContent).not.toContain('Pay booking');fixture.destroy();});
 it('cannot infer a paid registration fee from a saved profile amount',async()=>{const fixture=await mount('fee');http.expectOne(r=>r.url.endsWith('/workflow/driver/overview')).flush({data:{driver:{id:'d',online:false,registrationFeePaise:20000,registrationFeeRequired:true},fee:'Unpaid',reasons:['Required registration fee is not settled'],trips:[],offers:[],movements:[]}});fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Unpaid');expect(fixture.nativeElement.textContent).toContain('₹200.00');http.expectNone(r=>r.method!=='GET');fixture.destroy();});
 it('accepts a real offer by ID without trusting caller-supplied driver identity',async()=>{const fixture=await mount('requests');const overview={driver:{id:'d',online:true},fee:'Paid',reasons:[],trips:[],offers:[],movements:[]};http.expectOne(r=>r.url.endsWith('/workflow/driver/overview')).flush({data:overview});fixture.componentInstance.act('driver/offers/offer-id',{accept:true});const request=http.expectOne(r=>r.url.endsWith('/workflow/driver/offers/offer-id'));expect(request.request.body).toEqual({accept:true});request.flush({data:{status:'confirmed'}});http.expectOne(r=>r.url.endsWith('/workflow/driver/overview')).flush({data:overview});fixture.destroy();});
 it('displays backend Accounts amounts and hides financial writes without permission',async()=>{const fixture=await mount('accounts');http.expectOne(r=>r.url.endsWith('/workflow/accounts')).flush({data:{totals:{bookings:1,collected:100000,commission:15000,platformIncome:35000,driverPayable:85000,driverPaid:0,registrationFees:20000},bookings:[],movements:[],drivers:[],registrationSummary:Object.fromEntries(['Unpaid','Pending','Paid','Failed','Waived','Refunded'].map(k=>[k,{count:0,amountPaise:0}])),dateRule:'Fixture cohort'}});fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('₹350.00');expect(fixture.nativeElement.textContent).toContain('₹850.00');expect(fixture.nativeElement.textContent).not.toContain('Record confirmation');fixture.destroy();});

 it('offers COD and Razorpay and saves COD unpaid without a gateway call',async()=>{const f=await mount('book');http.expectOne(r=>r.url.endsWith('/workflow/customer/pricing')).flush({data:[]});f.detectChanges();expect(f.nativeElement.textContent).toContain('Cash on Delivery (COD)');expect(f.nativeElement.textContent).toContain('Razorpay');f.componentInstance.booking.startsAt='2090-01-01T10:00';f.componentInstance.create();const req=http.expectOne(r=>r.url.endsWith('/workflow/customer/bookings'));expect(req.request.body.paymentMode).toBe('cash');expect(req.request.body.farePaise).toBeUndefined();req.flush({data:{id:'booking',paymentStatus:'unpaid',paymentMode:'cash'}});expect(f.componentInstance.error()).toContain('collection pending');http.expectNone(r=>r.url.endsWith('/payment-order'));f.destroy();});
 it('starts Razorpay only for the saved booking ID and preserves callback signature fields',async()=>{const f=await mount('book');http.expectOne(r=>r.url.endsWith('/workflow/customer/pricing')).flush({data:[]});f.componentInstance.booking.startsAt='2090-01-01T10:00';f.componentInstance.booking.paymentMode='razorpay';const pay=vi.spyOn(f.componentInstance,'pay').mockResolvedValue();f.componentInstance.create();http.expectOne(r=>r.url.endsWith('/workflow/customer/bookings')).flush({data:{id:'saved-booking',paymentStatus:'unpaid'}});expect(pay).toHaveBeenCalledWith('saved-booking');pay.mockRestore();f.destroy();});

 it('sends Razorpay signature and order ID to backend and never marks Paid locally',async()=>{const f=await mount('fee');const overview={driver:{id:'d',registrationFeePaise:20000},fee:'Unpaid',reasons:[],offers:[],trips:[],movements:[]};http.expectOne(r=>r.url.endsWith('/workflow/driver/overview')).flush({data:overview});let options:Record<string,any>={};class Checkout {constructor(value:Record<string,any>){options=value;}open(){}on(){}}vi.stubGlobal('Razorpay',Checkout);await f.componentInstance.pay();http.expectOne(r=>r.url.endsWith('/workflow/driver/payment-order')).flush({data:{orderId:'order_fixture',keyId:'rzp_test_fixture',amountPaise:20000}});options['handler']({razorpay_payment_id:'pay_fixture',razorpay_order_id:'order_fixture',razorpay_signature:'signed-fixture'});const confirm=http.expectOne(r=>r.url.endsWith('/workflow/payment-confirm'));expect(confirm.request.body).toEqual({paymentId:'pay_fixture',orderId:'order_fixture',signature:'signed-fixture'});confirm.flush({error:{message:'Payment is not captured'}},{status:422,statusText:'Unprocessable Entity'});expect(f.componentInstance.overview()?.fee).toBe('Unpaid');vi.unstubAllGlobals();f.destroy();});
 it('checkout dismissal does not confirm or collect payment',async()=>{const f=await mount('fee');http.expectOne(r=>r.url.endsWith('/workflow/driver/overview')).flush({data:{driver:{id:'d'},fee:'Unpaid',reasons:[],offers:[],trips:[],movements:[]}});let options:Record<string,any>={};class Checkout {constructor(value:Record<string,any>){options=value;}open(){}on(){}}vi.stubGlobal('Razorpay',Checkout);await f.componentInstance.pay();http.expectOne(r=>r.url.endsWith('/workflow/driver/payment-order')).flush({data:{orderId:'order_fixture',keyId:'rzp_test_fixture',amountPaise:20000}});options['modal'].ondismiss();expect(f.componentInstance.error()).toContain('cancelled');expect(f.componentInstance.busy()).toBe(false);http.expectNone(r=>r.url.endsWith('/payment-confirm'));vi.unstubAllGlobals();f.destroy();});
});

describe('Accounts detail boundaries and preferred driver requests',()=>{
 let http:HttpTestingController;
 async function page(section:string,can=false){await TestBed.configureTestingModule({imports:[Workflow],providers:[provideRouter([]),provideHttpClient(),provideHttpClientTesting(),{provide:ActivatedRoute,useValue:{data:of({mode:'accounts',section})}},{provide:AuthService,useValue:{can:()=>can}}]}).compileComponents();const f=TestBed.createComponent(Workflow);http=TestBed.inject(HttpTestingController);f.detectChanges();http.expectOne(r=>r.url.endsWith('/workflow/accounts')).flush({data:{totals:{bookings:1,collected:100000,commission:15000,platformIncome:65000},bookings:[],drivers:[],movements:[],registrationSummary:Object.fromEntries(['Unpaid','Pending','Paid','Failed','Waived','Refunded'].map(k=>[k,{count:0,amountPaise:0}])),meta:{total:0,page:1,pageSize:25},dateRule:'Saved rules'}});if(section==='Commissions'&&can)http.expectOne(r=>r.url.endsWith('/masters/onboarding-options')).flush({data:{}});if(section==='Commissions'&&can)http.expectOne(r=>r.url.endsWith('/accounts/pricing')).flush({data:[]});f.detectChanges();return f;}
 afterEach(()=>{http?.verify();TestBed.resetTestingModule();});
 it.each(['Booking Payments','Registration Fees','Commissions','Driver Payouts','Refunds & Adjustments','Reports'])('keeps %s free of overview cards and seven-tab navigation',async section=>{const f=await page(section);expect(f.nativeElement.textContent).not.toContain('Total Collected');expect(f.nativeElement.querySelectorAll('sky-data-table').length).toBe(1);expect(f.nativeElement.querySelectorAll('md-filter-chip').length).toBe(0);expect(f.nativeElement.textContent).not.toContain('Confirm financial movement');f.destroy();});
 it('overview only offers summaries and pending/recent records, not financial forms',async()=>{const f=await page('Overview',true);expect(f.nativeElement.textContent).toContain('Total Collected');expect(f.nativeElement.textContent).toContain('Pending actions');expect(f.nativeElement.textContent).not.toContain('Record confirmation');expect(f.nativeElement.textContent).not.toContain('Registration fee policy');expect(f.nativeElement.querySelectorAll('sky-data-table').length).toBe(0);f.destroy();});
 it('requires explicit actual-transfer confirmation and sends rupees as backend paise',async()=>{const f=await page('Booking Payments',true);f.componentInstance.finance.reference='receipt-fixture';f.componentInstance.finance.bookingId='booking';f.componentInstance.finance.amountRupees=1000;f.componentInstance.finance.reason='Actual platform collection';f.componentInstance.financialAction();http.expectNone(r=>r.url.endsWith('/accounts/movements'));f.componentInstance.financeConfirmed.set(true);f.componentInstance.financialAction();const req=http.expectOne(r=>r.url.endsWith('/accounts/movements'));expect(req.request.body).toMatchObject({confirmed:true,amountPaise:100000,kind:'booking_payment'});expect(req.request.body.amountRupees).toBeUndefined();req.flush({error:{message:'Fixture rejected'}},{status:422,statusText:'Unprocessable'});f.destroy();});
});
