/** Browser integration: real app/router/password/binary files; isolated in-memory Prisma
 * delegates. Never connects to or mutates the configured database, uses injected sessions,
 * calls providers, or changes an existing account. Live-account checks remain separate. */
import {it,expect,vi} from 'vitest';
import {mockPrisma,resetPrismaMock} from '../test-utils/prisma-mock';
import fs from 'node:fs';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import bcrypt from 'bcryptjs';import {chromium} from 'playwright';import multer from 'multer';
vi.mock('../lib/prisma',()=>({prisma:mockPrisma}));
vi.mock('../lib/upload',()=>{const root=path.resolve('apps/mera-driver-api/verification/continuation-binary-store');return {UPLOAD_ROOT:root,diskStorageFor:(folder:any)=>multer.diskStorage({destination:(req,file,cb)=>{const directory=path.join(root,folder(req));fs.mkdirSync(directory,{recursive:true});cb(null,directory);},filename:(req,file,cb)=>cb(null,randomUUID()+'-'+file.originalname)})};});
import {createApp} from '../app';import {invalidatePermissionCache} from '../services/permission.service';
const output=path.resolve('apps/mera-driver-api/verification/artifacts');
const password='Isolated browser fixture only 2026';
const sha=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
it.skipIf(process.env.MERA_BROWSER_VERIFY!=='1')('verifies password login, final navigation and binary document workflows on isolated browser fixtures',async()=>{
 resetPrismaMock();invalidatePermissionCache();fs.mkdirSync(output,{recursive:true});
 const admin={id:randomUUID(),name:'TEST Browser Admin',email:'test-browser-admin@example.invalid',phone:null,status:'active',deletedAt:null,passwordHash:await bcrypt.hash(password,10)};
 const owner={...admin,id:randomUUID(),name:'TEST Browser Driver',email:'test-browser-driver@example.invalid'};
 const role={id:randomUUID(),key:'super_admin',name:'Super Admin',isSuperAdmin:true,isActive:true};
 const driverRole={...role,id:randomUUID(),key:'driver',name:'Driver',isSuperAdmin:false};
 const drivers=[{id:randomUUID(),firstName:'TEST Binary',lastName:'Driver',phone:'9000000001',email:'test-driver@example.invalid',gender:'Male',vehicle:'',city:'Pune',state:'Maharashtra',driverType:'Car Driver',status:'Non-Verified',accountStatus:'Active',onboardingStatus:'in_progress',completedSteps:[],completedSubSteps:[],currentStep:1,currentSubStep:0,completionPercentage:0,userId:owner.id,avatar:null,online:false,assignedVerifierId:null},{id:randomUUID(),firstName:'TEST Another',lastName:'Driver',phone:'9000000002',vehicle:'',city:'Pune',status:'Non-Verified',accountStatus:'Active',completedSteps:[],completedSubSteps:[],userId:null,online:true}];
 const docs:any[]=[];const master=[{id:randomUUID(),category:'eye-visions',name:'Normal Vision',status:'Active'},{id:randomUUID(),category:'personal-docs',name:'Passport',status:'Active'},{id:randomUUID(),category:'personal-docs',name:'Aadhaar',status:'Active'},{id:randomUUID(),category:'health-docs',name:'Medical Certificate',status:'Active'},{id:randomUUID(),category:'health-docs',name:'Insurance',status:'Active'},{id:randomUUID(),category:'police-docs',name:'Police Certificate',status:'Active'},{id:randomUUID(),category:'police-docs',name:'Police NOC',status:'Active'}];
 const user=(id:string)=>id===admin.id?admin:id===owner.id?owner:null;
 const enrich=(driver:any)=>driver?{...driver,documents:docs.filter(d=>d.driverId===driver.id),user:driver.userId?user(driver.userId):null,assignedVerifier:null,driverStatusMaster:null}:null;
 mockPrisma.user.findFirst.mockImplementation(async({where}:any)=>where.id?user(where.id):where.OR?.some((option:any)=>option.email===admin.email)?admin:where.OR?.some((option:any)=>option.email===owner.email)?owner:null);
 mockPrisma.user.update.mockResolvedValue(admin);mockPrisma.user.findUnique.mockImplementation(async({where}:any)=>user(where.id));
 mockPrisma.userRole.findMany.mockImplementation(async({where}:any)=>[{role:where.userId===admin.id?role:driverRole}]);
 mockPrisma.role.findMany.mockImplementation(async({where}:any)=>where?.key?.in?.includes('super_admin')?[role]:where?.key?.in?.includes('driver')?[driverRole]:[]);
 mockPrisma.rolePermission.findMany.mockResolvedValue([]);mockPrisma.roleDashboardWidget.findMany.mockResolvedValue([]);mockPrisma.userPermissionOverride.findMany.mockResolvedValue([]);
 mockPrisma.customer.findUnique.mockResolvedValue(null);mockPrisma.customer.findFirst.mockResolvedValue(null);mockPrisma.auditLog.findMany.mockResolvedValue([]);mockPrisma.vehicleType.findMany.mockResolvedValue([]);mockPrisma.driverKycCheck.findMany.mockResolvedValue([]);mockPrisma.driverKycDecision.findMany.mockResolvedValue([]);mockPrisma.booking.count.mockResolvedValue(0);mockPrisma.moneyMovement.findMany.mockResolvedValue([]);
 mockPrisma.masterListItem.findMany.mockImplementation(async({where}:any)=>master.filter(item=>!where?.category||typeof where.category!=='string'||item.category===where.category));
 mockPrisma.driver.findUnique.mockImplementation(async({where}:any)=>enrich(drivers.find(d=>where.id?d.id===where.id:d.userId===where.userId)));
 mockPrisma.driver.findFirst.mockImplementation(async({where}:any)=>enrich(drivers.find(d=>where.userId?d.userId===where.userId:d.id===where.id)));
 mockPrisma.driver.findMany.mockImplementation(async({where}:any)=>drivers.filter(d=>!where?.id?.in||where.id.in.includes(d.id)).map(enrich));
 mockPrisma.driver.update.mockImplementation(async({where,data}:any)=>{const driver=drivers.find(d=>d.id===where.id)!;Object.assign(driver,data);return enrich(driver);});
 mockPrisma.$queryRaw.mockImplementation(async(query:any)=>{
  if(!query?.sql)return [];
  let selected=drivers;
  if(query.sql.includes('d.online=')){const online=query.values.find((value:any)=>typeof value==='boolean');selected=selected.filter(driver=>driver.online===online);}
  const search=query.values.find((value:any)=>typeof value==='string'&&value.startsWith('%')&&value.endsWith('%'));
  if(search){const text=search.slice(1,-1).toLowerCase();selected=selected.filter(driver=>(driver.firstName+' '+driver.lastName+' '+driver.id+' '+driver.phone).toLowerCase().includes(text));}
  if(query.sql.includes('COUNT(*)'))return [{totalDrivers:selected.length,driverUsers:selected.filter(driver=>driver.userId).length,kycPending:selected.filter(driver=>driver.id===drivers[0].id).length,readyForTrips:0,feeUnpaid:selected.length}];
  if(query.sql.includes('LIMIT')){if(query.sql.includes('WHERE p."userId" IS NOT NULL'))selected=selected.filter(driver=>driver.userId);if(query.sql.includes('WHERE p."readyForTrips"'))selected=[];if(query.sql.includes('WHERE p."needsKycReview"'))selected=selected.filter(driver=>driver.id===drivers[0].id);return selected.map(driver=>({id:driver.id,feeStatus:'Unpaid',readyForTrips:false,registrationFeeRequired:false}));}
  return [];
 });
 mockPrisma.driverDocument.findMany.mockImplementation(async({where}:any)=>docs.filter(d=>d.driverId===where.driverId&&(!where.category||d.category===where.category)).sort((a,b)=>b.version-a.version));
 mockPrisma.driverDocument.findFirst.mockImplementation(async({where,include}:any)=>{const d=docs.find(d=>Object.entries(where).every(([k,v])=>d[k]===v));return d&&include?{...d,driver:enrich(drivers.find(driver=>driver.id===d.driverId))}:d??null;});
 mockPrisma.driverDocument.create.mockImplementation(async({data}:any)=>{const d={...data,id:randomUUID(),createdAt:new Date(),archivedAt:null};docs.push(d);return d;});
 mockPrisma.driverDocument.update.mockImplementation(async({where,data}:any)=>{const d=docs.find(d=>d.id===where.id);Object.assign(d,data);return d;});
 const previousCors=process.env.CORS_ORIGINS;process.env.CORS_ORIGINS='http://localhost:4401';const app=createApp();const server=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));const address=server.address() as any;const api='http://127.0.0.1:'+address.port;
 const browser=await chromium.launch({headless:true});const errors:string[]=[];const results:string[]=[];
 const pdf=async(text:string)=>{const page=await browser.newPage();await page.setContent('<h1>'+text+'</h1>');const bytes=await page.pdf({format:'A6'});await page.close();return bytes;};
 const original=await pdf('TEST ONLY original document');const replacement=await pdf('TEST ONLY replacement document');
 const first=path.join(output,'continuation-original.pdf'),second=path.join(output,'continuation-replacement.pdf');fs.writeFileSync(first,original);fs.writeFileSync(second,replacement);
 const imagePage=await browser.newPage({viewport:{width:32,height:32}});await imagePage.setContent('<body style="margin:0;background:#336699">TEST</body>');const png=await imagePage.screenshot();await imagePage.close();const imageFile=path.join(output,'continuation-pixel.png');fs.writeFileSync(imageFile,png);
 const pageFor=async()=>{const context=await browser.newContext({viewport:{width:1440,height:1100}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>console.log('Failed fixture request',new URL(r.url()).pathname,r.failure()?.errorText));page.on('response',async r=>{if(r.status()>=400)console.log('Rejected fixture request',r.request().method(),new URL(r.url()).pathname,r.status(),(await r.text().catch(()=>'' )).slice(0,400));});await page.route('http://localhost:3334/**',route=>route.continue({url:route.request().url().replace('http://localhost:3334',api)}));return page;};
 const input=async(page:any,selector:string,value:string)=>page.locator(selector).first().evaluate((el:any,value:string)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true,composed:true}));},value);
 const login=async(page:any,account:any,portal:string,target:string)=>{await page.goto('http://localhost:4401/sign-in?redirectTo='+encodeURIComponent(target));await page.getByRole('button',{name:portal==='staff'?'Staff':'Driver',exact:true}).click();await page.getByRole('button',{name:'Sign in with password instead',exact:true}).click();await input(page,'md-outlined-text-field.auth-field',account.email);await input(page,'md-outlined-text-field[label="Password"]',password);const done=page.waitForResponse((r:any)=>r.url().endsWith('/auth/password/login'));await page.getByRole('button',{name:'Log in',exact:true}).click();const response=await done;expect(response.status()).toBe(200);await page.waitForURL((url:any)=>url.pathname!=='/sign-in');return (await response.json()).data.accessToken;};
 const section=async(page:any,category:string)=>{await page.locator('md-primary-tab').filter({hasText:['education','health'].includes(category)?'Education & Health Details':'Documents Details'}).click();if(category==='health')await page.waitForFunction(()=>Array.from(document.querySelectorAll('md-filter-chip')).some((el:any)=>el.label?.includes('Health & Medical')));if(category==='health')await page.locator('md-filter-chip').evaluateAll((els:any[])=>els.find(el=>el.label.includes('Health & Medical'))?.click());if(category==='personal'||category==='police')await page.waitForFunction(()=>Array.from(document.querySelectorAll('md-filter-chip')).some((el:any)=>el.label?.includes('Personal & Category')));if(category==='personal'||category==='police')await page.locator('md-filter-chip').evaluateAll((els:any[],value:string)=>els.find(el=>el.label.includes(value==='police'?'Police Verification':'Personal & Category'))?.click(),category);if(category==='police'){const status=page.locator('md-outlined-select[label="Police Verified Status"]');await status.click();await status.locator('md-select-option').filter({hasText:'Yes'}).click();}await page.locator('md-outlined-select[label="Document Type"]').first().waitFor();};
 const reopen=async(page:any,category:string)=>{await page.goto('http://localhost:4401/account/drivers?edit='+drivers[0].id);await page.locator('md-primary-tab').first().waitFor();await section(page,category);};
 try{
  const page=await pageFor();const token=await login(page,admin,'staff','/account/drivers');await page.goto('http://localhost:4401/account/drivers?edit='+drivers[0].id);await page.locator('md-primary-tab').first().waitFor();await page.waitForFunction(()=>Array.from(document.querySelectorAll('md-filter-chip')).some((el:any)=>el.label?.includes('Account & Lead')));await page.locator('md-filter-chip').evaluateAll((els:any[])=>els.find(el=>el.label.includes('Account & Lead'))?.click());await page.locator('input[type="file"][accept="image/*"]').setInputFiles(imageFile);const photo=page.waitForResponse(r=>r.url().endsWith('/documents')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save draft',exact:true}).click();expect((await photo).status()).toBe(201);await page.getByRole('button',{name:'Save draft',exact:true}).waitFor({state:'visible'});await page.waitForTimeout(200);await page.goto('http://localhost:4401/account/drivers');await page.getByRole('heading',{name:'Driver Registry',exact:true}).waitFor();await page.getByRole('img',{name:'Profile photo of TEST Binary Driver',exact:true}).waitFor();await page.waitForFunction(()=>Array.from(document.querySelector('sky-data-table')?.shadowRoot?.querySelectorAll('img')??[]).some(img=>img.complete&&img.naturalWidth>0));await page.screenshot({path:path.join(output,'continuation-final-registry-desktop.png'),fullPage:true});await page.locator('.admin-sidebar__search').fill('');await page.screenshot({path:path.join(output,'continuation-final-sidebar.png'),fullPage:true});expect(await page.getByRole('link',{name:'Vehicles',exact:true}).count()).toBe(0);expect(await page.getByRole('link',{name:'Attendance',exact:true}).count()).toBe(0);await page.locator('.admin-sidebar__search').fill('Vehicle Types');await page.getByRole('link',{name:'Vehicle Types',exact:true}).waitFor();await page.locator('.admin-sidebar__search').fill('');results.push('Normal password login and staff redirect; removed menus and nested Vehicle Types search');
  await page.reload();await page.getByRole('heading',{name:'Driver Registry',exact:true}).waitFor();for(const label of ['Driver Users','Need KYC Review','Ready for Trip','All Drivers']){await page.getByRole('button',{name:label,exact:true}).click();await page.waitForTimeout(100);}expect(await page.locator('sky-card').filter({hasText:'All Drivers'}).evaluate((el:any)=>el.style.outline.includes('2px'))).toBe(true);
  const available=page.locator('md-outlined-select[label="Availability"]');await available.click();await available.locator('md-select-option').filter({hasText:'Online',exact:true} as any).first().click();await page.getByRole('button',{name:'Hide filters',exact:true}).click();expect(await available.count()).toBe(0);await page.getByRole('button',{name:'Show filters',exact:true}).click();expect(await available.evaluate((el:any)=>el.value)).toBe('online');await page.getByRole('button',{name:'Clear Filters',exact:true}).click();await page.locator('sky-data-table').getByRole('button',{name:/column/i}).first().click();await page.keyboard.press('Escape');results.push('Four card filters, selected-card state, hide/show preserving Availability, clear and existing column selector');

  for(const category of ['education','health','personal','police']){
   await reopen(page,category);const fields=page.locator('md-outlined-select[label="Document Type"]');if(category==='personal')await page.getByRole('button',{name:'Add Personal Document',exact:true}).click();const field=fields.last();await field.click();const option=field.locator('md-select-option').filter({hasText:category==='education'?'10th Certificate':category==='health'?'Medical Certificate':category==='personal'?'Passport':'Police Certificate'});await option.click();const selectedKey=await field.evaluate((el:any)=>el.value);await page.locator('input[type="file"]').last().setInputFiles(first);await page.screenshot({path:path.join(output,'continuation-'+category+'-upload.png'),fullPage:true});
   const done=page.waitForResponse(r=>r.url().endsWith('/documents')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save draft',exact:true}).click();const uploaded=await done;expect(uploaded.status()).toBe(201);const stored=(await uploaded.json()).data;await reopen(page,category);await page.waitForFunction(key=>Array.from(document.querySelectorAll('md-outlined-select[label="Document Type"]')).some((el:any)=>el.value===key),selectedKey);const index=await fields.evaluateAll((els:any[],key:string)=>els.findIndex(el=>el.value===key),selectedKey);expect(await page.locator('md-outlined-text-field[label="Document File Upload"]').nth(index).evaluate((el:any)=>el.value)).toBe('continuation-original.pdf');await page.screenshot({path:path.join(output,'continuation-'+category+'-reload.png'),fullPage:true});
   const get=await fetch(api+'/uploads/'+stored.filePath,{headers:{Authorization:'Bearer '+token}});expect(get.status).toBe(200);expect(stored.sizeBytes).toBe(original.length);expect(sha(Buffer.from(await get.arrayBuffer()))).toBe(sha(original));
   await page.locator('input[type="file"]').nth(index).setInputFiles(category==='health'?imageFile:second);const changed=page.waitForResponse(r=>r.url().endsWith('/documents')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save draft',exact:true}).click();expect((await changed).status()).toBe(201);expect(docs.filter(d=>d.driverId===drivers[0].id&&d.category===category&&d.type===stored.type)).toHaveLength(2);expect(docs.find(d=>d.id===stored.id).archivedAt).toBeTruthy();await reopen(page,category);await page.screenshot({path:path.join(output,'continuation-'+category+'-replacement-history.png'),fullPage:true});
   page.once('dialog',dialog=>dialog.accept());const deleted=page.waitForResponse(r=>r.request().method()==='DELETE'&&r.url().includes('/documents/'));const deleteIndex=await fields.evaluateAll((els:any[],key:string)=>els.findIndex(el=>el.value===key),selectedKey);await page.locator('md-icon-button[title="Delete Document"]').nth(deleteIndex).click();expect((await deleted).status()).toBe(200);await page.screenshot({path:path.join(output,'continuation-'+category+'-deletion.png'),fullPage:true});results.push(category+': binary UI save, reopen, byte-identical protected download, replacement version and archive deletion');
  }
  await page.setViewportSize({width:1024,height:900});await page.getByRole('button',{name:'Save draft',exact:true}).waitFor({state:'visible'});await page.waitForTimeout(200);await page.goto('http://localhost:4401/account/drivers');await page.getByRole('heading',{name:'Driver Registry',exact:true}).waitFor();await page.screenshot({path:path.join(output,'continuation-final-registry-tablet.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.reload();await page.getByRole('button',{name:'Show sidebar',exact:true}).click();await page.waitForTimeout(300);expect((await page.locator('.admin-sidebar').boundingBox())!.x).toBeGreaterThanOrEqual(0);await page.screenshot({path:path.join(output,'continuation-final-sidebar-mobile.png'),fullPage:true});
  const ownPage=await pageFor();const ownToken=await login(ownPage,owner,'driver','/driver/documents');await ownPage.locator('md-outlined-select[label="Document Type"]').waitFor();const field=ownPage.locator('md-outlined-select[label="Document Type"]');await field.click();await field.locator('md-select-option').filter({hasText:'Passport',exact:true} as any).first().click();await ownPage.locator('input[type="file"]').setInputFiles(first);const submitted=ownPage.waitForResponse(r=>r.url().endsWith('/me/documents')&&r.request().method()==='POST');await ownPage.getByRole('button',{name:'Upload',exact:true}).click();expect((await submitted).status()).toBe(201);await ownPage.reload();const card=ownPage.locator('.driver-doc-card').filter({hasText:'Current'}).filter({hasText:'continuation-original.pdf'});await card.getByRole('button',{name:/Preview/}).click();await card.locator('iframe').waitFor();const download=ownPage.waitForEvent('download');await card.getByRole('link',{name:'Download original',exact:true}).click();const downloaded=await download;const file=await downloaded.path();expect(sha(fs.readFileSync(file!))).toBe(sha(original));await ownPage.screenshot({path:path.join(output,'continuation-driver-portal-preview-history.png'),fullPage:true});results.push('Driver password login, portal upload/reload, authenticated PDF preview and matching browser download');expect(errors).toEqual([]);
  // Supported archive flow only; retain identifiable fixture files/history, never erase uploads.
  for(const doc of docs.filter(d=>!d.archivedAt)){await fetch(api+'/drivers/'+doc.driverId+'/documents/'+doc.id,{method:'DELETE',headers:{Authorization:'Bearer '+token}});}
  fs.writeFileSync(path.join(output,'continuation-browser-results.json'),JSON.stringify({mode:'Automated browser integration: real running frontend + real Express auth/upload/download routes; in-memory Prisma fixtures; not configured-database/existing-account login',injectedSessions:false,externalServices:false,results,errors,fixtureFiles:'Retained under verification/continuation-binary-store; archived via supported document API',configuredAccountChecks:'Blocked: credentials/OTP access unavailable'},null,2));
 }finally{process.env.CORS_ORIGINS=previousCors;await browser.close();await new Promise<void>(resolve=>server.close(()=>resolve()));}
},180000);
