import { Router } from 'express';
import { z } from 'zod';
import { authenticate } from '../middleware/authenticate';
import { requirePermission } from '../middleware/requirePermission';
import { resolveOwnCustomer } from '../lib/resolveOwnCustomer';
import { resolveOwnDriver } from '../lib/resolveOwnDriver';
import { validateBody } from '../middleware/validate';
import { prisma } from '../lib/prisma';
import * as trips from '../services/trip-workflow.service';
import * as accounts from '../services/accounts.service';
import { createPayment, confirmPayment } from '../services/payment-provider.service';
import { HttpError } from '../middleware/errorHandler';
import { bookingInvoice } from '../services/booking-invoice.service';

const router = Router();
router.get('/catalog',async(_req,res,next)=>{try{const rules=await prisma.fareRule.findMany({where:{isActive:true},orderBy:{effectiveFrom:'desc'}});res.json({data:rules.filter(rule=>new Date(rule.effectiveFrom)<=new Date()).map(rule=>({id:rule.id,zoneName:rule.zoneName,tripTypeName:rule.tripTypeName,vehicleCategoryName:rule.vehicleCategoryName,minFare:rule.minFare,baseFare:rule.baseFare})),error:null});}catch(e){next(e);}});
router.use(authenticate);
router.post('/customer/payment-order', resolveOwnCustomer, validateBody(z.object({bookingId:z.string().uuid()}).strict()), async(req,res,next)=>{try{res.json({data:await createPayment(req.user!.sub,{customerId:req.customer!.id},req.body.bookingId),error:null});}catch(e){next(e);}});
router.post('/driver/payment-order', resolveOwnDriver, async(req,res,next)=>{try{res.json({data:await createPayment(req.user!.sub,{driverId:req.driver!.id}),error:null});}catch(e){next(e);}});
router.post('/payment-confirm', validateBody(z.object({paymentId:z.string().regex(/^pay_[A-Za-z0-9]+$/),orderId:z.string().regex(/^order_[A-Za-z0-9]+$/),signature:z.string().regex(/^[a-f0-9]{64}$/i)}).strict()), async(req,res,next)=>{try{res.json({data:await confirmPayment(req.user!.sub,req.body.paymentId,req.body.orderId,req.body.signature),error:null});}catch(e){next(e);}});
const book = z.object({ city: z.string().trim().min(1).max(100), service: z.string().min(1).max(100), vehicleCategory: z.string().min(1).max(100),
  pickupAddress: z.string().min(1).max(1000), dropAddress: z.string().min(1).max(1000), startsAt: z.string(), durationMinutes: z.number().int().positive().max(525600), distanceKm: z.number().min(0).max(100000), requiredSkill: z.string().max(100).optional(), preferredDriverId:z.string().uuid().optional(),paymentMode:z.enum(['cash','razorpay']).optional() }).strict();
const transition = z.object({ status: z.enum(['on_the_way','arrived','in_progress','completed','cancelled']), otp: z.string().optional(), reason: z.string().max(2000).optional() }).strict();
router.get('/customer/pricing', resolveOwnCustomer, async (_req,res,next) => { try { res.json({ data: await prisma.fareRule.findMany({ where: { isActive: true } }), error: null }); } catch(e){next(e);} });
router.post('/customer/quote', resolveOwnCustomer, validateBody(book), async(req,res,next)=>{try{res.json({data:await trips.quoteBooking(req.body),error:null});}catch(e){next(e);}});
router.post('/customer/candidates',resolveOwnCustomer,validateBody(book.extend({page:z.number().int().min(1).default(1)})),async(req,res,next)=>{try{res.json({data:await trips.customerCandidates(req.body,req.body.page),error:null});}catch(e){next(e);}});
router.post('/customer/bookings', resolveOwnCustomer, validateBody(book), async(req,res,next)=>{try{res.status(201).json({data:await trips.bookCustomer(req.customer!.id,req.user!.sub,req.body),error:null});}catch(e){next(e);}});
router.get('/customer/bookings', resolveOwnCustomer, async(req,res,next)=>{try{const rows=await prisma.booking.findMany({where:{customerId:req.customer!.id},orderBy:{createdAt:'desc'}});res.json({data:await Promise.all(rows.map(b=>trips.customerTrip(req.customer!.id,b.id))),error:null});}catch(e){next(e);}});
router.get('/customer/bookings/:id/invoice.pdf',resolveOwnCustomer,async(req,res,next)=>{try{const pdf=await bookingInvoice(req.customer!.id,req.params.id);res.setHeader('Cache-Control','private, no-store');res.setHeader('Content-Disposition','attachment; filename="booking-invoice.pdf"');res.type('application/pdf').send(pdf);}catch(e){next(e);}});
router.get('/customer/payments', resolveOwnCustomer, async(req,res,next)=>{try{const bookings=await prisma.booking.findMany({where:{customerId:req.customer!.id}});res.json({data:await prisma.moneyMovement.findMany({where:{bookingId:{in:bookings.map(b=>b.id)},kind:{in:['booking_payment','booking_refund','driver_cod_collection','driver_cod_refund']}},orderBy:{createdAt:'desc'}}),error:null});}catch(e){next(e);}});
router.get('/accounts/report.csv',requirePermission('payments.overview','export'),async(req,res,next)=>{try{const filters=z.object({from:z.string().optional(),to:z.string().optional(),city:z.string().optional(),service:z.string().optional(),paymentStatus:z.string().optional()}).parse(req.query);const bookings=await accounts.accountReportRows(filters);const cell=(value:unknown)=>{let s=String(value??'');if(/^[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const rows=[['Booking','Fare (paise)','Commission basis points','Earned commission (paise)','Driver earned (paise)','Platform received (paise)','Driver COD collected (paise)','Commission receivable (paise)','Refunded (paise)','Driver paid (paise)','Driver payable (paise)','Payment status','Payout status'],...bookings.map(b=>[b.bookingCode,b.farePaise,b.commissionBps,b.commission,b.earned,b.collected,b.driverCollected,b.commissionReceivable,b.refunded,b.paid,b.payable,b.paymentStatus,b.payoutStatus])];res.setHeader('Cache-Control','private, no-store');res.setHeader('Content-Disposition','attachment; filename="accounts-report.csv"');res.type('text/csv').send(rows.map(row=>row.map(cell).join(',')).join('\r\n'));}catch(e){next(e);}});
router.post('/customer/bookings/:id/status', resolveOwnCustomer, validateBody(transition), async(req,res,next)=>{try{res.json({data:await trips.transitionTrip(req.params.id,req.user!.sub,req.body,{customerId:req.customer!.id}),error:null});}catch(e){next(e);}});
router.get('/driver/overview', resolveOwnDriver, async(req,res,next)=>{try{const result=await trips.driverEligibility(req.driver!.id);res.json({data:{...result,trips:await trips.driverTrips(req.driver!.id),offers:await trips.driverOffers(req.driver!.id),movements:await prisma.moneyMovement.findMany({where:{driverId:req.driver!.id}})},error:null});}catch(e){next(e);}});
router.get('/drivers/:id/overview',requirePermission('drivers','view'),async(req,res,next)=>{try{const result=await trips.driverEligibility(req.params.id);res.json({data:{...result,trips:await trips.driverTrips(req.params.id),offers:[],movements:await prisma.moneyMovement.findMany({where:{OR:[{driverId:req.params.id},{booking:{driverId:req.params.id}}]}}),activity:await prisma.auditLog.findMany({where:{targetType:'Driver',targetId:req.params.id},orderBy:{createdAt:'desc'},take:500})},error:null});}catch(e){next(e);}});
router.patch('/driver/availability', resolveOwnDriver, validateBody(z.object({online:z.boolean()}).strict()), async(req,res,next)=>{try{await prisma.driver.update({where:{id:req.driver!.id},data:req.body});res.json({data:await trips.driverEligibility(req.driver!.id),error:null});}catch(e){next(e);}});
router.post('/driver/offers/:id', resolveOwnDriver, validateBody(z.object({accept:z.boolean()}).strict()), async(req,res,next)=>{try{res.json({data:await trips.respondOffer(req.driver!.id,req.params.id,req.user!.sub,req.body.accept),error:null});}catch(e){next(e);}});
router.post('/driver/trips/:id/status', resolveOwnDriver, validateBody(transition), async(req,res,next)=>{try{res.json({data:await trips.transitionTrip(req.params.id,req.user!.sub,req.body,{driverId:req.driver!.id}),error:null});}catch(e){next(e);}});
router.get('/messages', async(req,res,next)=>{try{res.json({data:await prisma.portalMessage.findMany({where:{userId:req.user!.sub},orderBy:{createdAt:'desc'}}),error:null});}catch(e){next(e);}});
router.post('/support', validateBody(z.object({subject:z.string().trim().min(1).max(200),body:z.string().trim().min(1).max(4000)}).strict()), async(req,res,next)=>{try{res.status(201).json({data:await prisma.portalMessage.create({data:{...req.body,userId:req.user!.sub,kind:'support'}}),error:null});}catch(e){next(e);}});
router.get('/dispatch',requirePermission('trips.bookings','view'),async(req,res,next)=>{try{
 const query=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),sort:z.enum(['bookingCode','customerName','status','startsAt','createdAt']).default('createdAt'),direction:z.enum(['asc','desc']).default('desc'),search:z.string().max(200).default(''),status:z.enum(['requested','confirmed','on_the_way','arrived','in_progress','completed','cancelled']).optional(),from:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),to:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional()}).parse(req.query);
 const boundary=(value:string|undefined,end=false)=>{if(!value)return undefined;const date=new Date(value+(end?'T23:59:59.999Z':'T00:00:00.000Z'));if(!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==value)throw new HttpError(422,'DATE_INVALID','Use a valid schedule date');return date;};
 const from=boundary(query.from),to=boundary(query.to,true);if(from&&to&&from>to)throw new HttpError(422,'DATE_INVALID','From date must not be after To date');
 const where={...(query.search?{OR:[{bookingCode:{contains:query.search,mode:'insensitive' as const}},{customerName:{contains:query.search,mode:'insensitive' as const}}]}:{}),...(query.status?{status:query.status}:{}),...(from||to?{startsAt:{gte:from,lte:to}}:{})};
 const [rows,total]=await Promise.all([prisma.booking.findMany({where,take:query.pageSize,skip:(query.page-1)*query.pageSize,include:{offers:{include:{driver:{select:{id:true,firstName:true,lastName:true}}},orderBy:{createdAt:'desc'}},events:true},orderBy:[{[query.sort]:query.direction},{id:'asc'}]}),prisma.booking.count({where})]);res.json({data:rows,error:null,meta:{total,page:query.page,pageSize:query.pageSize}});
 }catch(error){next(error);}});
router.get('/dispatch/:id/candidates',requirePermission('trips.bookings','view'),async(req,res,next)=>{try{res.json({data:await trips.dispatchCandidates(req.params.id,z.object({search:z.string().max(200).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(25).default(10)}).parse(req.query)),error:null});}catch(e){next(e);}});
router.patch('/accounts/drivers/:id/fee-policy',requirePermission('payments.overview','edit'),validateBody(z.object({registrationFeeRequired:z.boolean(),registrationFeePaise:z.number().int().min(0).max(100000000),reason:z.string().trim().min(1).max(2000)}).strict()),async(req,res,next)=>{try{
  if(req.body.registrationFeeRequired&&req.body.registrationFeePaise<=0)throw new HttpError(422,'FEE_POLICY_INVALID','Required fee must have a positive configured amount');
  const {reason,...policy}=req.body;
  const driver=await prisma.$transaction(async tx=>{
    await tx.$queryRaw`SELECT id FROM "Driver" WHERE id=${req.params.id} FOR UPDATE`;
    const before=await tx.driver.findUniqueOrThrow({where:{id:req.params.id}});
    const updated=await tx.driver.update({where:{id:req.params.id},data:policy});
    await tx.auditLog.create({data:{actorUserId:req.user!.sub,action:'finance.fee_policy',targetType:'Driver',targetId:updated.id,before:{registrationFeeRequired:before.registrationFeeRequired,registrationFeePaise:before.registrationFeePaise},after:req.body}});
    return updated;
  });
  res.json({data:{id:driver.id,...policy,reason},error:null});}catch(e){next(e);}});
router.post('/dispatch/:id/offers', requirePermission('trips.bookings','edit'), async(req,res,next)=>{try{res.json({data:await trips.offerBooking(req.params.id,req.user!.sub),error:null});}catch(e){next(e);}});
router.post('/dispatch/:id/assign', requirePermission('trips.bookings','edit'), validateBody(z.object({driverId:z.string().uuid(),reason:z.string().trim().min(1).max(2000)}).strict()), async(req,res,next)=>{try{res.json({data:await trips.assignTrip(req.params.id,req.body.driverId,req.user!.sub,req.body.reason),error:null});}catch(e){next(e);}});
router.get('/accounts', requirePermission('payments.overview','view'), async(req,res,next)=>{try{const filters=z.object({from:z.string().optional(),to:z.string().optional(),city:z.string().optional(),service:z.string().optional(),paymentStatus:z.string().optional(),section:z.enum(['Overview','Booking Payments','Registration Fees','Commissions','Driver Payouts','Refunds & Adjustments','Reports']).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),search:z.string().max(200).optional()}).parse(req.query);res.json({data:await accounts.accountsOverview(filters),error:null});}catch(e){next(e);}});
router.post('/accounts/movements', requirePermission('payments.overview','edit'), validateBody(z.object({reference:z.string().trim().min(1).max(200),bookingId:z.string().uuid().optional(),driverId:z.string().uuid().optional(),kind:z.enum(['booking_payment','booking_refund','driver_payout','driver_recovery','registration_payment','registration_refund','registration_waiver','driver_cod_collection','driver_cod_refund','commission_settlement','commission_refund']),amountPaise:z.number().int().min(0).max(1000000000),method:z.enum(['cash','bank_transfer','upi','waiver']),reason:z.string().trim().min(1).max(2000),confirmed:z.literal(true)}).strict()), async(req,res,next)=>{try{const {confirmed,...movement}=req.body;res.json({data:await accounts.recordMovement(req.user!.sub,movement),error:null});}catch(e){next(e);}});
router.get('/accounts/pricing',requirePermission('payments.overview','view'),async(_req,res,next)=>{try{res.json({data:await prisma.fareRule.findMany({where:{isActive:true}}),error:null});}catch(e){next(e);}});
router.patch('/accounts/pricing/:id/commission',requirePermission('payments.overview','edit'),validateBody(z.object({commissionBps:z.number().int().min(0).max(10000),requiredDriverSkill:z.string().trim().max(200).nullable().optional(),requiredDriverJobType:z.string().trim().max(150).nullable().optional(),requiredDriverJobChoice:z.string().trim().max(150).nullable().optional(),reason:z.string().trim().min(1).max(2000)}).strict()),async(req,res,next)=>{try{
  const row=await prisma.$transaction(async tx=>{const before=await tx.fareRule.findUniqueOrThrow({where:{id:req.params.id}});const preferences:Record<string,unknown>={...(req.body.requiredDriverJobType?{jobType:req.body.requiredDriverJobType}:{}),...(req.body.requiredDriverJobChoice?{jobChoices:[req.body.requiredDriverJobChoice]}:{})};await import('../services/driver-preferences.service').then(m=>m.validateDriverPreferences(preferences,{jobType:before.requiredDriverJobType,jobChoices:before.requiredDriverJobChoice?[before.requiredDriverJobChoice]:[]}));if(preferences.jobType)req.body.requiredDriverJobType=preferences.jobType;if(preferences.jobChoices)req.body.requiredDriverJobChoice=(preferences.jobChoices as string[])[0];const updated=await tx.fareRule.update({where:{id:req.params.id},data:{commissionBps:req.body.commissionBps,...(req.body.requiredDriverJobType!==undefined?{requiredDriverJobType:req.body.requiredDriverJobType||null}:{}),...(req.body.requiredDriverJobChoice!==undefined?{requiredDriverJobChoice:req.body.requiredDriverJobChoice||null}:{}),...(req.body.requiredDriverSkill!==undefined?{requiredDriverSkill:req.body.requiredDriverSkill||null}:{})}});await tx.auditLog.create({data:{actorUserId:req.user!.sub,action:'finance.commission_policy',targetType:'FareRule',targetId:updated.id,before:{commissionBps:before.commissionBps,requiredDriverSkill:before.requiredDriverSkill},after:req.body}});return updated;});res.json({data:row,error:null});}catch(e){next(e);}});
export default router;
