import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const {get}=vi.hoisted(()=>({get:vi.fn()}));
vi.mock('axios',()=>({default:{get,isAxiosError:(error:unknown)=>Boolean((error as {isAxiosError?:boolean})?.isAxiosError)}}));
import {sendOtp} from './connectExpress.provider';
beforeEach(()=>{vi.stubEnv('SMS_API_URL','https://example.invalid/api');vi.stubEnv('SMS_API_KEY','secret-key-fixture');vi.stubEnv('SMS_SENDER','FIXTUR');vi.stubEnv('SMS_OTP_TEMPLATE','Approved fixture {otp}');get.mockReset();vi.spyOn(console,'info').mockImplementation(()=>{});vi.spyOn(console,'error').mockImplementation(()=>{});});
afterEach(()=>{vi.unstubAllEnvs();vi.restoreAllMocks();});
describe('SMS OTP delivery',()=>{
  it('uses the existing configured request and accepts confirmed provider success',async()=>{get.mockResolvedValue({status:200,data:{status:'OK'}});await expect(sendOtp('+919999999999','123456')).resolves.toBe(true);expect(get).toHaveBeenCalledWith('https://example.invalid/api',{params:{method:'sms',api_key:'secret-key-fixture',to:'+919999999999',sender:'FIXTUR',unicode:'auto',message:'Approved fixture 123456',format:'json'},timeout:10000});});
  it.each(['SMS_API_URL','SMS_API_KEY','SMS_SENDER','SMS_OTP_TEMPLATE'])('fails clearly without %s and never calls a gateway',async key=>{vi.stubEnv(key,'');await expect(sendOtp('phone','123456')).rejects.toMatchObject({status:503,code:'OTP_PROVIDER_NOT_CONFIGURED'});expect(get).not.toHaveBeenCalled();});
  it('requires the existing template OTP placeholder',async()=>{vi.stubEnv('SMS_OTP_TEMPLATE','Missing placeholder');await expect(sendOtp('phone','123456')).rejects.toMatchObject({code:'OTP_PROVIDER_NOT_CONFIGURED'});expect(get).not.toHaveBeenCalled();});
  it.each([{},{status:'ERROR'},{status:'OK',error:'Invalid account'}])('rejects HTTP 200 with an unconfirmed/failed provider result %j',async data=>{get.mockResolvedValue({status:200,data});await expect(sendOtp('phone','123456')).rejects.toMatchObject({status:503,code:'OTP_PROVIDER_REJECTED'});expect(get).toHaveBeenCalledTimes(1);});
  it.each([['EACCES',undefined,'OTP_NETWORK_BLOCKED'],['EPERM',undefined,'OTP_NETWORK_BLOCKED'],['ECONNABORTED',undefined,'OTP_PROVIDER_TIMEOUT'],['ETIMEDOUT',undefined,'OTP_PROVIDER_TIMEOUT'],['ERR_BAD_REQUEST',401,'OTP_PROVIDER_AUTH_FAILED'],['ERR_BAD_REQUEST',429,'OTP_PROVIDER_RATE_LIMITED'],['ENOTFOUND',undefined,'OTP_DELIVERY_UNAVAILABLE']])('reports safe %s failure without retries',async(code,status,expected)=>{get.mockRejectedValue({isAxiosError:true,code,response:status?{status,data:{api_key:'secret-key-fixture',otp:'123456'}}:undefined,message:'secret-key-fixture 123456'});await expect(sendOtp('+919999999999','123456')).rejects.toMatchObject({code:expected});expect(get).toHaveBeenCalledTimes(1);expect(JSON.stringify(vi.mocked(console.error).mock.calls)).not.toMatch(/secret-key-fixture|123456|9999999999/);});
  it('never logs sensitive successful response fields',async()=>{get.mockResolvedValue({status:200,data:{status:'OK',api_key:'secret-key-fixture',message:'OTP 123456',recipient:'+919999999999'}});await sendOtp('+919999999999','123456');expect(JSON.stringify(vi.mocked(console.info).mock.calls)).not.toMatch(/secret-key-fixture|123456|9999999999/);});
});
