// Isolated real-DB fixtures only; no SMS, IDSPay, payment or Maps provider calls.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require('playwright'),jwt=require('jsonwebtoken');
require('dotenv').config({path:'apps/mera-driver-api/.env.local',quiet:true});
const {PrismaClient}=require('../src/generated/prisma-client');const db=new PrismaClient();
const api='http://localhost:3336',ui='http://localhost:4402',stamp=Date.now(),prefix='DISPATCH-'+stamp;
const ids={users:[],drivers:[],customers:[],bookings:[],roles:[]},checks=[],out=path.resolve('apps/mera-driver-api/verification/artifacts');let browser,lastPage;
const pass=x=>{checks.push(x);console.log('PASS',x);};
async function call(token,url,method='GET',body){const r=await fetch(api+url,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,...await r.json()};}
async function ok(token,url,method='GET',body){const r=await call(token,url,method,body);assert.equal(r.status,200,`${url}: ${r.error?.message}`);return r.data;}
const sign=(user,roles,portalContext='staff')=>jwt.sign({sub:user,roles,app:'mera-driver',portalContext},process.env.JWT_SECRET,{expiresIn:'20m'});
async function portal(token,viewport={width:1440,height:1000}){const context=await browser.newContext({viewport});await context.addInitScript(t=>localStorage.setItem('mera_driver_auth_token',t),token);await context.route(/^(http:\/\/localhost:3334|https:\/\/api\.mera-driver\.example\.com)\//,async route=>{const response=await route.fetch({url:route.request().url().replace(/^https?:\/\/[^/]+/,api)});await route.fulfill({response});});const page=await context.newPage();lastPage=page;return page;}
async function search(page,text){await page.locator('md-dispatch-table').evaluate(el=>el.updateComplete);const response=page.waitForResponse(r=>r.url().includes('/workflow/dispatch?')&&r.request().method()==='GET'&&new URL(r.url()).searchParams.get('search')===text);const field=page.locator('md-dispatch-table').getByRole('searchbox',{name:'Booking reference or customer'});await field.fill(text);await field.press('End');await field.press('Space');await field.press('Backspace');await response;await page.locator('md-dispatch-table').locator('table[aria-busy="false"]').waitFor();}
async function open(page,label){await page.locator('md-dispatch-table').getByRole('button',{name:new RegExp('^'+label+':')}).first().click();await page.getByText('Loading current booking…',{exact:true}).waitFor({state:'hidden'});await page.getByText('Loading candidates…',{exact:true}).waitFor({state:'hidden'});}
async function candidateSearch(page,text){await page.locator('md-outlined-text-field[label="Search drivers by name, phone or ID"]').locator('input').fill(text);const response=page.waitForResponse(r=>r.url().includes('/candidates?')&&new URL(r.url()).searchParams.get('search')===text);await page.getByRole('button',{name:'Search Drivers',exact:true}).click();await response;await page.getByText('Loading candidates…',{exact:true}).waitFor({state:'hidden'});}
async function reason(page,value,reassign=false){await page.getByRole('textbox',{name:reassign?'Reassignment reason':'Assignment note / reason',exact:true}).fill(value);}
(async()=>{try{
 assert.ok(['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL).hostname));fs.mkdirSync(out,{recursive:true});
 const actor=await db.user.findFirst({where:{status:'active',deletedAt:null,roles:{some:{role:{isSuperAdmin:true,isActive:true}}}},include:{roles:{include:{role:true}}}});assert.ok(actor);const admin=sign(actor.id,actor.roles.map(r=>r.role.key));
 const driverRole=await db.role.findUnique({where:{key:'driver'}}),customerRole=await db.role.findUnique({where:{key:'customer'}});
 async function user(role){const row=await db.user.create({data:{name:prefix,email:crypto.randomUUID()+'@example.invalid',roles:{create:{roleId:role.id}}}});ids.users.push(row.id);return row;}
 const cu=await user(customerRole),c=await db.customer.create({data:{userId:cu.id,firstName:prefix,mobileNumber:'fixture-'+stamp}});ids.customers.push(c.id);
 const city=prefix,drivers=[];for(let i=0;i<12;i++){const u=await user(driverRole);const d=await db.driver.create({data:{userId:u.id,firstName:prefix+' Driver '+String(i).padStart(2,'0'),phone:'fixture-'+stamp+'-'+i,city,accountStatus:'Active',status:'Verified',completedSubSteps:[10,11,12,13,20,21,30,31,32,40],dlNo:'FIXTURE-DL',dlExpiryDate:'2099-01-01',online:i!==11,driverType:'Automatic',registrationFeeRequired:false,languages:[]}});ids.drivers.push(d.id);drivers.push({...d,token:sign(u.id,['driver'],'driver')});}
 const startsAt=new Date('2090-01-02T10:00:00Z'),endsAt=new Date('2090-01-02T11:00:00Z');
 async function booking(n,status='requested',driverId=null){const row=await db.booking.create({data:{bookingCode:prefix+'-'+n,customerId:c.id,customerName:prefix,status,driverId,driverName:driverId?drivers.find(x=>x.id===driverId).firstName:null,city,pickupAddress:'Pickup, Central Station',dropAddress:'Drop, Business Park',startsAt,endsAt,scheduledAt:startsAt.toISOString(),tripTypeName:'Hourly',farePaise:100000,estimatedFare:1000,commissionBps:1500,commissionPaise:15000,driverSharePaise:85000,paymentMode:'cash',paymentStatus:'unpaid'}});ids.bookings.push(row.id);return row;}
 const main=await booking('MAIN'),done=await booking('DONE','completed',drivers[0].id),cancelled=await booking('CANCELLED','cancelled');await booking('ASSIGNED','confirmed',drivers[11].id);
 for(let i=0;i<27;i++)await booking(String(i).padStart(2,'0'));
 await db.tripOffer.create({data:{bookingId:main.id,driverId:drivers[1].id,isCustomerPreference:true}});await db.tripEvent.create({data:{bookingId:main.id,actorId:cu.id,status:'requested',reason:'Customer preference request'}});
 const list=await call(admin,'/workflow/dispatch?search='+prefix+'&quick=needs_assignment&pageSize=10&page=2');assert.equal(list.status,200);assert.equal(list.meta.total,28);assert.equal(list.data.length,10);
 assert.equal((await call(admin,'/workflow/dispatch?search='+prefix+'&quick=assigned')).meta.total,1);assert.equal((await call(admin,'/workflow/dispatch?search='+prefix+'&quick=completed')).meta.total,1);pass('Real API quick filters/counts apply before pagination across all fixture bookings');
 browser=await chromium.launch({headless:true});const page=await portal(admin);lastPage=page;const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(ui+'/account/dispatch');await page.locator('md-dispatch-table').waitFor();await search(page,main.bookingCode);await page.locator('md-dispatch-table').getByText(main.bookingCode,{exact:false}).waitFor();
 assert.equal(await page.locator('md-dispatch-table').getByRole('button',{name:/^Reassign:/}).count(),0);await open(page,'Assign');await page.getByText('Preferred: '+drivers[1].firstName+'  · pending',{exact:true}).waitFor();
 await candidateSearch(page,'no-such-driver-'+stamp);await page.getByText('No matching drivers. Try a different search.',{exact:true}).waitFor();
 let failOnce=true;await page.route('**/dispatch/*/candidates?**',async route=>{if(failOnce){failOnce=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Verification candidate transport failure'}})});}else await route.fallback();});await candidateSearch(page,prefix);await page.getByRole('alert').filter({hasText:'Verification candidate transport failure'}).waitFor();await page.getByRole('button',{name:'Retry candidates',exact:true}).click();await page.getByText('Loading candidates…',{exact:true}).waitFor({state:'hidden'});await page.unroute('**/dispatch/*/candidates?**');pass('Real empty candidate search and UI error/retry after a simulated transport failure');
 await candidateSearch(page,prefix);await page.getByRole('button',{name:'Next candidates',exact:true}).click();await page.getByText('Loading candidates…',{exact:true}).waitFor({state:'hidden'});const blocked=page.locator('label.candidate-row').filter({hasText:drivers[11].firstName});assert.equal(await blocked.locator('input[type=radio]').isDisabled(),true);assert.match(await blocked.textContent(),/Blocked: Driver is offline/);pass('Preferred request remains pending; blocked candidates show reasons and cannot be selected');
 await page.getByRole('button',{name:'Previous candidates',exact:true}).click();await page.getByText('Loading candidates…',{exact:true}).waitFor({state:'hidden'});await page.screenshot({path:path.join(out,'dispatch-dialog-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal((await db.booking.findUnique({where:{id:main.id}})).driverId,null);pass('Candidate search/pagination and cancel preserve the unassigned booking');
 await open(page,'Assign');await candidateSearch(page,drivers[0].firstName);await page.locator('label.candidate-row').filter({hasText:drivers[0].firstName}).locator('input[type=radio]').check();await reason(page,'Fixture initial dispatch');const firstResponse=page.waitForResponse(r=>r.url().endsWith('/dispatch/'+main.id+'/assign'));await page.getByRole('button',{name:'Assign Driver',exact:true}).click();assert.equal((await firstResponse).status(),200);await page.getByText('Driver assigned.',{exact:true}).waitFor();assert.equal((await db.booking.findUnique({where:{id:main.id}})).driverId,drivers[0].id);assert.equal((await db.tripOffer.findFirst({where:{bookingId:main.id}})).status,'superseded');pass('Successful eligible assignment closes the dialog and does not accept the preferred request or settle payment');
 await page.locator('md-dispatch-table').getByRole('button',{name:/^Reassign:/}).waitFor();await open(page,'Reassign');const current=page.locator('label.candidate-row').filter({hasText:'Current driver'});assert.equal(await current.locator('input').isChecked(),true);await candidateSearch(page,drivers[2].firstName);assert.equal(await current.count(),1);await page.locator('label.candidate-row').filter({hasText:drivers[2].firstName}).locator('input').check();assert.equal(await page.getByRole('button',{name:'Reassign Driver',exact:true}).isDisabled(),true);await reason(page,'Fixture replacement reason',true);
 // Eligibility changes after the candidate was returned: real server must reject.
 await db.driver.update({where:{id:drivers[2].id},data:{online:false}});const failed=page.waitForResponse(r=>r.url().endsWith('/assign'));await page.getByRole('button',{name:'Reassign Driver',exact:true}).click();assert.equal((await failed).status(),422);await page.getByRole('alert').filter({hasText:'Driver is offline'}).waitFor();await page.getByText('Loading candidates…',{exact:true}).waitFor({state:'hidden'});assert.equal((await db.booking.findUnique({where:{id:main.id}})).driverId,drivers[0].id);pass('Current driver remains visible off-page; required reason and stale-eligibility failure preserve booking');
 await db.driver.update({where:{id:drivers[2].id},data:{online:true}});await candidateSearch(page,drivers[2].firstName);await page.locator('label.candidate-row').filter({hasText:drivers[2].firstName}).locator('input').check();const reassigned=page.waitForResponse(r=>r.url().endsWith('/assign'));await page.getByRole('button',{name:'Reassign Driver',exact:true}).click();assert.equal((await reassigned).status(),200);await page.getByText('Driver reassigned.',{exact:true}).waitFor();assert.ok(await db.tripEvent.findFirst({where:{bookingId:main.id,reason:{contains:'Fixture replacement reason'}}}));pass('A different replacement succeeds and its required reason remains in trip history');
 const customerToken=sign(cu.id,['customer'],'customer');const customerRows=await ok(customerToken,'/workflow/customer/bookings'),driverRows=await ok(drivers[2].token,'/workflow/driver/overview');assert.equal(customerRows.find(x=>x.id===main.id).status,'confirmed');assert.equal(driverRows.trips.find(x=>x.id===main.id).status,'confirmed');assert.equal((await ok(admin,'/workflow/dispatch/'+main.id)).status,'confirmed');assert.equal((await db.booking.findUnique({where:{id:main.id}})).paymentStatus,'unpaid');pass('Customer, Driver and Admin read the same confirmed assignment and unpaid payment state');
 await search(page,done.bookingCode);assert.equal(await page.locator('md-dispatch-table').getByRole('button',{name:/^(Assign|Reassign):/}).count(),0);await page.locator('md-dispatch-table').getByRole('button',{name:/^View:/}).click();await page.getByRole('heading',{name:done.bookingCode+' · Completed'}).waitFor();assert.equal(await page.getByRole('button',{name:/^(Assign|Reassign) Driver$/}).count(),0);pass('View opens existing booking details; terminal rows and details hide assignment actions');
 await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Show Filters',exact:true}).click();await page.locator('input[name=dispatchFrom]').fill('2090-01-03');await page.getByRole('button',{name:'Apply',exact:true}).click();await page.locator('md-dispatch-table').getByText(/No .*found|No data|No records/).waitFor();await page.getByRole('button',{name:'Clear',exact:true}).click();await search(page,prefix);await page.locator('md-dispatch-table').getByRole('button',{name:'Next page',exact:true}).click();await page.locator('md-dispatch-table').getByRole('button',{name:'Previous page',exact:true}).waitFor();pass('Browser search, schedule filters, clear and full-dataset pagination work');
 const sorted=page.waitForResponse(r=>r.url().includes('/workflow/dispatch?')&&new URL(r.url()).searchParams.get('sort')==='startsAt');await page.locator('md-dispatch-table').getByRole('columnheader',{name:/Schedule \/ Service/}).click();await sorted;
 await page.locator('md-dispatch-table').getByRole('button',{name:'Select columns',exact:true}).click();const column=page.locator('md-dispatch-table').locator('label.col-option').filter({hasText:'Fare / Payment'});await column.click();assert.equal(await page.locator('md-dispatch-table').getByRole('columnheader',{name:'Fare / Payment',exact:true}).count(),0);await column.click();await page.locator('md-dispatch-table').getByRole('button',{name:'Select columns',exact:true}).click();
 const filtered=page.waitForResponse(r=>r.url().includes('/workflow/dispatch?')&&new URL(r.url()).searchParams.get('quick')==='needs_assignment');await page.locator('md-filter-chip').filter({hasText:'Needs Assignment'}).click();assert.equal((await (await filtered).json()).meta.total,27);await page.locator('md-filter-chip').filter({hasText:'All Bookings'}).click();pass('Browser sorting, column controls and quick filters retain the shared DataTable behavior');
 const race=await booking('RACE'),raceBody=d=>({driverId:d,reason:'Concurrent fixture',expectedDriverId:null,expectedUpdatedAt:race.updatedAt.toISOString(),clientRequestId:crypto.randomUUID()});const one=raceBody(drivers[3].id),two=raceBody(drivers[4].id);const raced=await Promise.all([call(admin,`/workflow/dispatch/${race.id}/assign`,'POST',one),call(admin,`/workflow/dispatch/${race.id}/assign`,'POST',two)]);assert.deepEqual(raced.map(x=>x.status).sort(),[200,409]);const winning=raced[0].status===200?one:two;assert.equal((await call(admin,`/workflow/dispatch/${race.id}/assign`,'POST',winning)).status,200);assert.equal(await db.auditLog.count({where:{targetId:race.id,action:'trip.assignment'}}),1);pass('Real concurrent assignment has one winner and one 409; duplicate retry creates no extra audit/history');
 const acceptBooking=await booking('DRIVER-ACCEPT'),offer=await db.tripOffer.create({data:{bookingId:acceptBooking.id,driverId:drivers[5].id,isCustomerPreference:true}});await ok(drivers[5].token,`/workflow/driver/offers/${offer.id}`,'POST',{accept:true});assert.equal((await db.tripOffer.findUnique({where:{id:offer.id}})).status,'accepted');assert.equal((await ok(customerToken,'/workflow/customer/bookings')).find(b=>b.id===acceptBooking.id).status,'confirmed');pass('Separate driver acceptance still confirms its own pending request and synchronizes customer status');
 const viewRole=await db.role.create({data:{key:'dispatch_verify_'+stamp,name:prefix+' View'}});ids.roles.push(viewRole.id);const perm=await db.permission.findUnique({where:{key:'trips.bookings:view'}});await db.rolePermission.create({data:{roleId:viewRole.id,permissionId:perm.id}});const staff=await user(viewRole),readToken=sign(staff.id,[viewRole.key]);const owned=await db.booking.update({where:{id:cancelled.id},data:{createdByUserId:staff.id}});assert.equal((await call(readToken,`/workflow/dispatch/${owned.id}/assign`,'POST',one)).status,403);const readPage=await portal(readToken);await readPage.goto(ui+'/account/dispatch');await readPage.locator('md-dispatch-table').waitFor();assert.equal(await readPage.locator('md-dispatch-table').getByRole('button',{name:/^(Assign|Reassign):/}).count(),0);pass('Custom view-only role keeps scoped dispatch readable; mutations are hidden and directly denied by API');
 lastPage=page;await page.setViewportSize({width:390,height:844});await search(page,main.bookingCode);await open(page,'Reassign');await page.screenshot({path:path.join(out,'dispatch-dialog-mobile.png'),fullPage:false});const box=await page.getByRole('dialog').boundingBox();assert.ok(box.width<=390);const focused=await page.evaluate(()=>!!document.activeElement?.closest('md-dialog'));assert.ok(focused);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>!!document.activeElement?.closest('md-dialog')),true);await page.keyboard.press('Escape');await page.locator('md-dialog').evaluate(el=>el.updateComplete);assert.equal(await page.locator('md-dialog').evaluate(el=>el.open),false);pass('Mobile dialog fits the viewport, receives focus and closes with Escape without mutation');
 assert.deepEqual(errors,[]);pass('No browser runtime errors');
}catch(e){console.error('FAIL',e.stack);checks.push('FAIL: '+e.message);process.exitCode=1;if(lastPage)await lastPage.screenshot({path:path.join(out,'dispatch-live-failure.png'),fullPage:true}).catch(()=>{});}finally{
 // Retain audit/history and every relationship; deactivate fixtures rather than deleting.
 for(const id of ids.bookings)await db.booking.update({where:{id},data:{status:'cancelled'}}).catch(()=>{});
 for(const id of ids.drivers)await db.driver.update({where:{id},data:{accountStatus:'Inactive',online:false}}).catch(()=>{});
 for(const id of ids.customers)await db.customer.update({where:{id},data:{accountStatus:'Inactive'}}).catch(()=>{});
 for(const id of ids.users)await db.user.update({where:{id},data:{status:'inactive'}}).catch(()=>{});
 for(const id of ids.roles)await db.role.update({where:{id},data:{isActive:false}}).catch(()=>{});
 if(browser)await browser.close();fs.writeFileSync(path.join(out,'dispatch-live-results.json'),JSON.stringify({checks,fixtures:ids,cleanup:'All fixtures retained inactive/cancelled with history. No existing records or role grants changed; no external provider calls.'},null,2));await db.$disconnect();}})();
