const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('playwright'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs');
require('dotenv').config({path:path.resolve('apps/mera-driver-api/.env.local'),quiet:true});
const {PrismaClient}=require('../src/generated/prisma-client');const db=new PrismaClient();
const api='http://localhost:3336',ui='http://localhost:4402',stamp=Date.now(),results=[],fixtures={roles:[],users:[],customers:[]};
const out=path.resolve('apps/mera-driver-api/verification/artifacts');let browser,adminToken,original,lastPage;
const check=(label)=>{results.push(label);console.log('PASS',label);};
async function call(token,url,method='GET',body){const response=await fetch(api+url,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});let payload;try{payload=await response.json();}catch{}return {status:response.status,data:payload?.data,error:payload?.error};}
async function ok(token,url,method='GET',body,status=200){const r=await call(token,url,method,body);assert.equal(r.status,status,`${method} ${url}: ${r.error?.message}`);return r.data;}
async function context(token,refresh){const ctx=await browser.newContext({viewport:{width:1440,height:1000}});await ctx.addInitScript(({token,refresh})=>{localStorage.setItem('mera_driver_auth_token',token);if(refresh)localStorage.setItem('mera_driver_auth_refresh_token',refresh);},{token,refresh});
 await ctx.route(/^(http:\/\/localhost:3334|https:\/\/api\.mera-driver\.example\.com)\//,async route=>{const r=await route.fetch({url:route.request().url().replace(/^https?:\/\/[^/]+/,api)});await route.fulfill({response:r,headers:{...r.headers(),'access-control-allow-origin':ui,'access-control-allow-credentials':'true'}});});return ctx;}
async function field(page,label,value){await page.locator(`md-outlined-text-field[label="${label}"]`).locator('input,textarea').fill(value);}
async function selectRole(page,name){await page.locator('button.admin-nav-item').filter({hasText:name}).click();await page.getByText('Loading saved permissions...',{exact:true}).waitFor({state:'hidden'});}
async function focus(page){await page.evaluate(()=>window.dispatchEvent(new Event('focus')));}
async function baseline(){return db.role.findMany({where:{key:{in:['super_admin','admin','vendor','marketing','sales','company','data_operator','support','kyc_verification','driver','customer']}},select:{id:true,key:true,name:true,description:true,permissions:{select:{permissionId:true},orderBy:{permissionId:'asc'}},users:{select:{userId:true},orderBy:{userId:'asc'}}},orderBy:{key:'asc'}});}
(async()=>{try{
 original=await baseline();const actor=await db.user.findFirst({where:{status:'active',deletedAt:null,roles:{some:{role:{isActive:true,isSuperAdmin:true}}}},include:{roles:{include:{role:true}}}});assert.ok(actor,'An existing Super Admin is needed');
 adminToken=jwt.sign({sub:actor.id,roles:actor.roles.map(x=>x.role.key),app:'mera-driver',portalContext:'staff'},process.env.JWT_SECRET,{expiresIn:'20m'});
 const initialBootstrap=await ok(adminToken,'/rbac/bootstrap');assert.ok(initialBootstrap.permissions.includes('rbac.roles:create'));
 const direct=await db.userPermissionOverride.findMany({where:{effect:'grant'},select:{userId:true,permission:{select:{key:true}}}});check(`Existing direct-grant conflicts inspected: ${direct.length}`);
 browser=await chromium.launch({headless:true});const admin=await context(adminToken),page=await admin.newPage();lastPage=page;const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('/rbac/')&&r.status()>=400)console.log('RBAC HTTP',r.status(),r.url().split('/').slice(-2).join('/'));});
 await page.goto(ui+'/account/administration/roles');await page.locator('button.admin-nav-item[aria-pressed="true"]').waitFor();assert.equal((await page.locator('button.admin-nav-item[aria-pressed="true"]').textContent()).trim(),initialBootstrap.roles.find(x=>x.isSuperAdmin).name);check('Super Admin selected and highlighted on initial entry');
 const name=`RBAC Verification ${stamp}`,key=`rbac_verify_${stamp}`;
 await page.getByRole('button',{name:'Add Role',exact:true}).click();await field(page,'Role name',name);await field(page,'Stable role key',key);await field(page,'Description','Temporary RBAC regression fixture');await page.getByRole('button',{name:'Save Role',exact:true}).click();await page.getByText('Role created. Configure its permissions below.',{exact:true}).waitFor();
 let role=await db.role.findUnique({where:{key}});assert.ok(role);fixtures.roles.push(role.id);assert.equal(await db.rolePermission.count({where:{roleId:role.id}}),0);assert.equal(await page.locator('button.admin-nav-item[aria-pressed="true"]').textContent(),name);check('Add Role creates, selects and loads a zero-grant custom role');
 await page.getByRole('button',{name:'Add Role',exact:true}).click();await field(page,'Role name',name);await field(page,'Stable role key',key+'_duplicate');await page.getByRole('button',{name:'Save Role',exact:true}).click();await page.getByText('A role with this name or key already exists.',{exact:true}).waitFor();await page.getByRole('button',{name:'Cancel',exact:true}).first().click();const duplicate=await call(adminToken,'/rbac/roles','POST',{key:key+'_dup',name:name.toLowerCase()});assert.equal(duplicate.status,409);check('Duplicate validation works in the form and API');
 const catalog=await ok(adminToken,'/rbac/permissions/catalog');const ids={};for(const node of catalog)for(const action of node.actions)if(action.permissionId)ids[action.key]=action.permissionId;
 await ok(adminToken,`/rbac/roles/${role.id}/permissions`,'PUT',{permissionIds:['dashboard:view','customers:view','customers:create'].map(k=>ids[k])});
 const email=`rbac-verification-${stamp}@example.invalid`,password=crypto.randomBytes(24).toString('base64url');const user=await ok(adminToken,'/rbac/users','POST',{name:`RBAC Test ${stamp}`,email,roleIds:[role.id]},201);fixtures.users.push(user.id);
 await db.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(password,10)}});
 const login=await ok(null,'/auth/password/login','POST',{identifier:email,password,portalContext:'staff'});const token=login.accessToken;
 const customer=await ok(token,'/customers','POST',{firstName:`RBAC Customer ${stamp}`,mobileNumber:String(stamp)},201);fixtures.customers.push(customer.id);assert.equal(customer.createdByUserId,user.id);check('Real password login and scoped customer creation use the assigned custom role');
 await page.reload();await selectRole(page,name);await page.getByRole('checkbox',{name:'Customers create',exact:true}).waitFor();assert.equal(await page.getByRole('checkbox',{name:'Customers create',exact:true}).evaluate(el=>el.checked),true);await page.getByRole('checkbox',{name:'Customers create',exact:true}).click();await page.getByRole('button',{name:'Save Permissions',exact:true}).click();await page.getByText('Permissions saved.',{exact:true}).waitFor();
 const saved=await ok(adminToken,`/rbac/roles/${role.id}/permissions`);assert.deepEqual(new Set(saved.permissionIds),new Set([ids['dashboard:view'],ids['customers:view']]));
 for(const [method,url,body]of [['POST','/customers',{firstName:'Denied',mobileNumber:'denied'}],['PATCH',`/customers/${customer.id}`,{firstName:'Denied'}],['DELETE',`/customers/${customer.id}`]])assert.equal((await call(token,url,method,body)).status,403);assert.equal((await db.customer.findUnique({where:{id:customer.id}})).firstName,`RBAC Customer ${stamp}`);check('View-only save persists; Create/Edit/Delete APIs return 403 and preserve records');
 const staff=await context(token,login.refreshToken),staffPage=await staff.newPage();await staffPage.goto(ui+'/account/customers');await staffPage.locator('sky-data-table').waitFor();await staffPage.getByText(`RBAC Customer ${stamp}`,{exact:true}).waitFor();assert.equal(await staffPage.getByRole('button',{name:'Add Customer',exact:true}).count(),0);assert.equal(await staffPage.getByRole('button',{name:/^Edit:/}).count(),0);assert.equal(await staffPage.getByRole('button',{name:/^Delete:/}).count(),0);check('Customer View-only UI retains the list and hides all mutation controls');
 await page.getByRole('checkbox',{name:'Customers edit',exact:true}).click();await page.getByRole('button',{name:'Save Permissions',exact:true}).click();await page.getByText('Permissions saved.',{exact:true}).waitFor();await focus(staffPage);await staffPage.getByRole('button',{name:/^Edit:/}).first().waitFor();assert.equal(await staffPage.getByRole('button',{name:'Add Customer',exact:true}).count(),0);assert.equal(await staffPage.getByRole('button',{name:/^Delete:/}).count(),0);
 await ok(token,`/customers/${customer.id}`,'PATCH',{firstName:`RBAC Edited ${stamp}`});check('Edit alone restores the already-open UI and same-token update API');
 await page.getByRole('checkbox',{name:'Customers edit',exact:true}).click();await page.getByRole('button',{name:'Save Permissions',exact:true}).click();await page.getByText('Permissions saved.',{exact:true}).waitFor();await focus(staffPage);await staffPage.getByRole('button',{name:/^Edit:/}).first().waitFor({state:'hidden'});assert.equal((await call(token,`/customers/${customer.id}`,'PATCH',{firstName:'Denied'})).status,403);check('Edit revocation removes controls in an open session and immediately denies its API');
 await page.reload();await selectRole(page,name);assert.equal(await page.getByRole('checkbox',{name:'Customers edit',exact:true}).evaluate(el=>el.checked),false);
 const fresh=await ok(null,'/auth/password/login','POST',{identifier:email,password,portalContext:'staff'});const freshBootstrap=await ok(fresh.accessToken,'/rbac/bootstrap');assert.ok(freshBootstrap.permissions.includes('customers:view'));assert.ok(!freshBootstrap.permissions.includes('customers:edit'));check('Revoked checkboxes remain revoked after reload and a fresh password login');
 const permissionBefore=(await ok(adminToken,`/rbac/roles/${role.id}/permissions`)).permissionIds;await page.getByRole('button',{name:'Edit Role',exact:true}).click();assert.equal(await page.locator('md-outlined-text-field[label="Role name"]').evaluate(el=>el.value),name);await field(page,'Role name',name+' Renamed');await page.getByRole('button',{name:'Save Role',exact:true}).click();await page.getByText('Role details saved.',{exact:true}).waitFor();assert.deepEqual((await ok(adminToken,`/rbac/roles/${role.id}/permissions`)).permissionIds,permissionBefore);assert.equal(await db.userRole.count({where:{userId:user.id,roleId:role.id}}),1);check('Edit Role preserves stable key, permission IDs and user assignments');
 const alt=await ok(adminToken,'/rbac/roles','POST',{key:key+'_alternate',name:name+' Alternate'},201);fixtures.roles.push(alt.id);await ok(adminToken,`/rbac/roles/${alt.id}/permissions`,'PUT',{permissionIds:[ids['dashboard:view']]});
 await page.goto(ui+'/account/administration/users');await page.locator('sky-data-table').waitFor();await page.getByRole('button',{name:/^Edit:/}).first().click();const dropdown=page.locator('md-outlined-select[label="Role"]').last();assert.equal(await dropdown.evaluate(el=>el.value),role.id);await dropdown.locator('md-select-option').filter({hasText:alt.name}).waitFor({state:'attached'});assert.ok(await dropdown.locator('md-select-option').evaluateAll((els,id)=>els.some(el=>el.value===id),alt.id));await dropdown.evaluate((el,id)=>{el.value=id;el.dispatchEvent(new Event('change',{bubbles:true}));},alt.id);await page.getByRole('button',{name:'Save Changes',exact:true}).click();await page.getByText('Changes saved.',{exact:true}).waitFor();const assigned=await db.userRole.findMany({where:{userId:user.id}});assert.deepEqual(assigned.map(x=>x.roleId),[alt.id]);assert.equal((await call(token,'/customers')).status,403);await focus(staffPage);await staffPage.waitForURL('**/account/dashboard');check('New roles appear in the single-role dropdown; switching removes previous access with an old token and redirects an open page');
 await staffPage.goto(ui+'/account/customers');await staffPage.waitForURL(/unauthorized|account\/dashboard/);check('A direct unauthorized page URL is denied');
 assert.deepEqual(await baseline(),original);assert.deepEqual(errors,[]);await page.screenshot({path:path.join(out,'rbac-user-assignment.png'),fullPage:true});check('All built-in roles, grants and user links remain unchanged');
 }catch(e){if(lastPage){console.log('UI diagnostics',JSON.stringify({url:lastPage.url(),checkboxes:await lastPage.locator('md-checkbox[aria-label*="Customers"]').evaluateAll(els=>els.map(el=>({label:el.getAttribute('aria-label'),checked:el.checked,visible:!!el.offsetWidth}))),selected:await lastPage.locator('button.admin-nav-item[aria-pressed="true"]').allTextContents()}));await lastPage.screenshot({path:path.join(out,'rbac-debug.png'),fullPage:true}).catch(()=>{});}console.error('FAIL',e.message);results.push('FAIL: '+e.message);process.exitCode=1;}
 finally{for(const id of fixtures.users){await db.user.update({where:{id},data:{status:'inactive',passwordHash:null}}).catch(()=>{});await db.refreshSession.updateMany({where:{userId:id,revokedAt:null},data:{revokedAt:new Date()}}).catch(()=>{});}for(const id of fixtures.roles)await db.role.update({where:{id},data:{isActive:false}}).catch(()=>{});for(const id of fixtures.customers)await db.customer.update({where:{id},data:{accountStatus:'Inactive'}}).catch(()=>{});if(browser)await browser.close();fs.writeFileSync(path.join(out,'rbac-live-results.json'),JSON.stringify({mode:'Running UI and isolated production API, real database, real password login for newly created fixture only; existing Super Admin signed fixture',results,fixtures,cleanup:'Verification roles/users/customers retained inactive; no records deleted and no built-in grants changed'},null,2));await db.$disconnect();}})();
