// Local real-record/UI/PDF verification; only these isolated synthetic IDs are removed.
const {chromium}=require('playwright');const {randomUUID}=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const jwt=require('jsonwebtoken');
require('dotenv').config({path:'apps/mera-driver-api/.env.local',quiet:true});const {PrismaClient}=require('../src/generated/prisma-client');const p=new PrismaClient();
const api=process.env.VERIFY_API||'http://localhost:3334',ui=process.env.VERIFY_UI||'http://localhost:4400',output=path.resolve('apps/mera-driver-api/verification/artifacts');const ids={full:randomUUID(),partial:randomUUID(),user:randomUUID()};let browser;
const sign=(sub,roles)=>jwt.sign({sub,roles,app:'mera-driver'},process.env.JWT_SECRET,{expiresIn:'20m'});
async function request(token,url,options={}){return fetch(api+url,{...options,headers:{Authorization:'Bearer '+token,...options.headers}});}
async function portal(token,url,width=1280){const context=await browser.newContext({viewport:{width,height:900}});await context.addInitScript(({token,origin})=>{if(location.origin===origin)localStorage.setItem('mera_driver_auth_token',token);},{token,origin:new URL(ui).origin});const page=await context.newPage();await page.goto(ui+url);return {context,page};}
async function download(page,name){const wait=page.waitForEvent('download',{timeout:60000});const button=page.getByRole('button',{name:'Download PDF',exact:true});await button.focus();const [file]=await Promise.all([wait,button.press('Enter')]);await file.saveAs(path.join(output,name+'.pdf'));assert.ok(file.suggestedFilename().endsWith('_Driver_Resume.pdf'));assert.equal(fs.readFileSync(path.join(output,name+'.pdf')).subarray(0,5).toString(),'%PDF-');return file.suggestedFilename();}
async function run(){assert.ok(['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL).hostname));fs.mkdirSync(output,{recursive:true});const baseline={drivers:await p.driver.count(),users:await p.user.count()};const admin=await p.user.findFirst({where:{roles:{some:{role:{isSuperAdmin:true}}}},include:{roles:{include:{role:true}}}});const adminToken=sign(admin.id,admin.roles.map(r=>r.role.key));
await p.$transaction(async tx=>{await tx.user.create({data:{id:ids.user,name:'Resume verification fixture'}});await tx.driver.create({data:{id:ids.full,userId:ids.user,firstName:'Resume Full',lastName:'Fixture',phone:'9876543210',email:'resume-fixture@example.org',city:'Pune',state:'Maharashtra',gender:'Male',experience:'5+ Years',driverType:'Car Driver',licenseDetails:'LMV',vehicleType:'Sedan, SUV',dlNo:'DL1420110012345',dlIssueDate:'2011-01-01',dlExpiryDate:'2099-01-01',education:'Graduate',language:'Hindi',languages:['English'],status:'Non-Verified',accountStatus:'Active',bankName:'PRIVATE_BANK',address:'PRIVATE_ADDRESS',dob:'1990-01-01',completedSubSteps:[10,11,12,13,20,21,30,31,32,40,41],onboardingStatus:'completed',completionPercentage:100}});await tx.driver.create({data:{id:ids.partial,firstName:'Resume Partial Fixture',completedSubSteps:[10],onboardingStatus:'in_progress',currentStep:1,currentSubStep:1,completionPercentage:9}});});
browser=await chromium.launch({headless:true,channel:'chromium'});const errors=[];const a=await portal(adminToken,`/account/drivers/${ids.full}/details`);a.page.on('pageerror',e=>errors.push(e.message));await a.page.getByRole('link',{name:'Resume Preview',exact:true}).click();await a.page.getByRole('button',{name:'Review / edit resume facts'}).click();await a.page.getByLabel('Professional summary (optional override)').fill('Car driver based in Pune with saved sedan and SUV experience. Available for local and outstation assignments.');
const entries=[{title:'Company Driver',employer:'Fixture Transit',start:'2018-01',end:'2020-12',responsibilities:'Transported staff on scheduled local routes.\nMaintained saved vehicle inspection records.'},{title:'Fleet Driver',employer:'Fixture Fleet',start:'2021-01',end:'2023-12',responsibilities:'Completed assigned intercity journeys.\nRecorded journey schedules and vehicle checks.'},{title:'Family Driver',employer:'Fixture Family',start:'2024-01',current:true,responsibilities:'Handled saved family travel assignments.\nPlanned agreed local and outstation routes.'}];
for(const [index,entry]of entries.entries()){await a.page.getByRole('button',{name:'Add employment',exact:true}).click();const group=a.page.locator('fieldset').nth(index);await group.getByLabel('Job title', {exact:true}).fill(entry.title);await group.getByLabel('Employer',{exact:true}).fill(entry.employer);await group.getByLabel('Location',{exact:true}).fill('Pune');await group.getByLabel('Start date',{exact:true}).fill(entry.start);if(entry.current)await group.getByLabel('Current employment').check();else await group.getByLabel('End date',{exact:true}).fill(entry.end);await group.getByLabel('Actual responsibilities').fill(entry.responsibilities);}
await a.page.getByLabel('Additional key skills').fill('Route planning\nVehicle care\nPassenger safety');await a.page.getByLabel('Manual',{exact:true}).check();await a.page.getByLabel('Automatic',{exact:true}).check();await a.page.getByLabel('Institution',{exact:true}).fill('Fixture College');await a.page.getByLabel('Education location').fill('Pune');await a.page.getByLabel('Year',{exact:true}).fill('2017');await a.page.getByLabel('Working availability').fill('Weekdays and weekends by arrangement');await a.page.getByLabel('Local',{exact:true}).check();await a.page.getByLabel('Outstation',{exact:true}).check();await a.page.getByLabel('Reason for this update').fill('Confirmed fixture employment and professional facts');
const saved=a.page.waitForResponse(r=>r.url().endsWith(`/drivers/${ids.full}/resume`)&&r.request().method()==='PATCH');await a.page.getByRole('button',{name:'Save facts & refresh preview',exact:true}).click();const response=await saved;assert.equal(response.status(),200);const snapshot=(await response.json()).data;assert.equal(snapshot.profile.workExperience.length,3);assert.equal(snapshot.data.name,'Resume Full Fixture');for(const forbidden of ['PRIVATE_BANK','PRIVATE_ADDRESS','DUMMY SAMPLE','undefined','1990-01-01'])assert.ok(!snapshot.html.includes(forbidden));assert.equal(await p.auditLog.count({where:{targetType:'Driver',targetId:ids.full,action:'driver.resume.update'}}),1);const record=await p.driver.findUnique({where:{id:ids.full}});assert.equal(record.status,'Non-Verified');assert.equal(record.completionPercentage,100);assert.equal(await p.moneyMovement.count({where:{driverId:ids.full}}),0);
await a.page.frameLocator('iframe[title="Driver resume preview"]').getByRole('heading',{name:'Work Experience',exact:true}).waitFor();await a.page.screenshot({path:path.join(output,'resume-full-preview.png'),fullPage:true});const fullFilename=await download(a.page,'professional-resume-full');await a.page.reload();await a.page.frameLocator('iframe[title="Driver resume preview"]').getByText('Fixture Family',{exact:false}).waitFor();
await a.page.setViewportSize({width:390,height:844});await a.page.waitForFunction(()=>{const frame=document.querySelector('iframe[title="Driver resume preview"]');return frame&&frame.clientHeight>=frame.contentDocument.body.scrollHeight;});assert.equal(await a.page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await a.page.waitForFunction(()=>document.querySelector('.admin-sidebar')?.getBoundingClientRect().right<=1);await a.page.screenshot({path:path.join(output,'resume-mobile-preview.png'),fullPage:true});
const partial=await portal(adminToken,`/account/drivers/${ids.partial}/resume`);await partial.page.getByText('Missing source fields').waitFor();await partial.page.screenshot({path:path.join(output,'resume-partial-preview.png'),fullPage:true});const partialFilename=await download(partial.page,'professional-resume-partial');
const driverToken=sign(ids.user,['driver']);const d=await portal(driverToken,'/driver/profile');await d.page.getByRole('link',{name:'My Resume',exact:true}).click();await d.page.frameLocator('iframe[title="Driver resume preview"]').getByRole('heading',{name:'Resume Full Fixture',exact:true}).waitFor();assert.equal(await d.page.getByRole('button',{name:'Review / edit resume facts'}).count(),0);await download(d.page,'professional-resume-own');
for(const [token,suffix]of [[driverToken,'resume'],[driverToken,'resume.pdf'],[sign(randomUUID(),['customer']),'resume'],[sign(randomUUID(),['kyc_verification']),'resume']])assert.equal((await request(token,`/drivers/${ids.partial}/${suffix}`)).status,403);
assert.equal((await fetch(api+`/drivers/${ids.full}/resume`)).status,401);assert.equal((await request(driverToken,`/drivers/me/resume?driverId=${ids.partial}`).then(r=>r.json())).data.data.name,'Resume Full Fixture');assert.equal((await request(adminToken,`/drivers/${ids.full}/resume.pdf?revision=${'0'.repeat(64)}`)).status,409);
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'professional-resume-snapshot.json'),JSON.stringify({full:snapshot,partial:(await request(adminToken,`/drivers/${ids.partial}/resume`).then(r=>r.json())).data},null,2));await browser.close();browser=null;await cleanup();assert.deepEqual({drivers:await p.driver.count(),users:await p.user.count()},baseline);fs.writeFileSync(path.join(output,'resume-results.json'),JSON.stringify({fullFilename,partialFilename,employmentEntries:3,previewAndPdfSameSnapshot:true,ownAndStaffAuthorization:true,mobileNoHorizontalOverflow:true,baseline,after:baseline,limitations:['Local signed test tokens; login itself not exercised','No Ramesh sample asset available']},null,2));console.log(JSON.stringify({resumeBrowser:'passed',employmentEntries:3,fullFilename,partialFilename,preservedCounts:baseline}));}
async function cleanup(){await p.$transaction(async tx=>{await tx.auditLog.deleteMany({where:{targetType:'Driver',targetId:{in:[ids.full,ids.partial]}}});await tx.driver.deleteMany({where:{id:{in:[ids.full,ids.partial]}}});await tx.user.deleteMany({where:{id:ids.user,name:'Resume verification fixture'}});});}
run().catch(async e=>{console.error(e.message);process.exitCode=1;if(browser)for(const c of browser.contexts())for(const page of c.pages())await page.screenshot({path:path.join(output,'resume-failure.png'),fullPage:true});}).finally(async()=>{if(browser)await browser.close();await cleanup();await p.$disconnect();});
