import { Component, HostListener, OnInit, OnDestroy, CUSTOM_ELEMENTS_SCHEMA, computed, inject, signal } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '@skylabs-monorepo/shared-auth/angular';
import { environment } from '../../../../environments/environment';
import { httpErrorMessage } from '../../../core/http-error';
import { AdminPage } from '../../../admin/admin-page/admin-page';

export interface DetailDocument {id:string;type:string;category:string;fileName:string|null;regNo?:string|null;mimeType?:string|null;sizeBytes?:number|null;version:number;createdAt:string;expiresAt:string|null;archivedAt:string|null;preview:string|null;review:{status:string;reason:string|null}|null}
export interface Details {approval?:{ready:boolean;reasons:string[];checklist:{key:string;field:string;tab:number;pill:number;status:string;label?:string;tabLabel?:string;pillLabel?:string;reason?:string|null}[]};review?:{checked:number;total:number;issues:number;status:string;profile?:{assignedReviewer:string};history:{id:string;label:string;status:string;reason:string|null;reviewerName:string;createdAt:string}[]};id:string;name:string;photo:string|null;city?:string|null;state?:string|null;phone?:string|null;email?:string|null;availability?:string;driverType?:string|null;experience?:string|null;source?:string|null;onboarding?:{status:string;percentage:number;completed:number;total:number;tab:string;pill:string};account:string;kyc:string;licenceValidity?:string;fee:string;feeRequired:boolean;dl?:{status:string;reason:string;history?:{id:string;action:string;createdAt:string;initiatorId:string|null;initiatorName?:string;summary:{status?:string;reason?:string;providerCalled?:boolean}}[]};reasons:string[];sections:{title:string;completed:boolean;fields:{key:string;label:string;value:unknown}[];documents:DetailDocument[]}[]}
interface Preview {url?:string;safe?:SafeResourceUrl;pdf?:boolean;error?:string}
@Component({selector:'md-driver-details',standalone:true,imports:[RouterLink,AdminPage],schemas:[CUSTOM_ELEMENTS_SCHEMA],templateUrl:'./driver-details.html',styleUrl:'./driver-details.css'})
export class DriverDetails implements OnInit, OnDestroy {
  private readonly http=inject(HttpClient); private readonly route=inject(ActivatedRoute);private readonly sanitizer=inject(DomSanitizer);
  readonly downloadMenu=signal(false);readonly approvalConfirmation=signal(false);readonly approving=signal(false);readonly photoFailed=signal(false);readonly auth=inject(AuthService);readonly details=signal<Details|null>(null);readonly error=signal('');readonly previews=signal<Record<string,Preview>>({});private destroyed=false;
  readonly photoUrl=signal('');readonly photoLoading=signal(false);
  readonly groups=computed(()=>{const groups=new Map<string,Details['sections']>();for(const section of this.details()?.sections??[]){const prefix=section.title.split(' · ')[0];const title=({'Personal Details':'Personal & Contact Details','Education & Health Details':'Education & Health Details','Documents Details':'Licence & Employment Details','Payment Details':'Payment & Bank Details'} as Record<string,string>)[prefix]??prefix;groups.set(title,[...(groups.get(title)??[]),section]);}return [...groups].map(([title,sections])=>({title,sections}));});
  readonly approvalGroups=computed(()=>{const groups=new Map<string,NonNullable<Details['approval']>['checklist']>();for(const check of this.details()?.approval?.checklist??[]){const title=check.tabLabel??'Required checks';groups.set(title,[...(groups.get(title)??[]),check]);}return [...groups].map(([title,checks])=>({title,checks,passed:checks.filter(c=>c.status==='Passed').length,pending:checks.filter(c=>c.status==='Pending').length,issues:checks.filter(c=>c.status==='Issue').length,stale:checks.filter(c=>c.status==='Review required after changes').length}));});
  readonly policyReasons=computed(()=>{const approval=this.details()?.approval;return (approval?.reasons??[]).filter(reason=>!approval?.checklist.some(c=>reason===`${c.tabLabel} / ${c.pillLabel} / ${c.label??c.field}: ${c.status}`));});
  requestApproval(){if(this.details()?.approval?.ready&&!this.approving())this.approvalConfirmation.set(true);}
  readonly documents=computed(()=>[...new Map((this.details()?.sections??[]).flatMap(s=>s.documents).map(doc=>[doc.id,doc])).values()]);
  readonly currentDocuments=computed(()=>this.documents().filter(doc=>!doc.archivedAt));readonly previousDocuments=computed(()=>this.documents().filter(doc=>doc.archivedAt));
  readonly documentGroups=computed(()=>[{title:'Current documents',documents:this.currentDocuments()},{title:'Previous version history',documents:this.previousDocuments()}].filter(group=>group.documents.length));
  percentage(){return Math.max(0,Math.min(100,this.details()?.onboarding?.percentage??Number(this.saved('completionPercentage')??0)));}
  async ngOnInit(){try{const id=this.route.snapshot.paramMap.get('id');const result=await firstValueFrom(this.http.get<{data:Details}>(`${environment.apiUrl}/drivers/${encodeURIComponent(id??'')}/details`));if(this.destroyed)return;this.details.set(result.data);await this.loadPhoto(result.data.photo);const documents=this.documents();let next=0;await Promise.all(Array.from({length:3},async()=>{while(next<documents.length&&!this.destroyed){const doc=documents[next++];if(!this.previews()[doc.id])await this.preview(doc);}}));}catch(error){this.error.set(await httpErrorMessage(error instanceof HttpErrorResponse ? error : {message:error instanceof Error?error.message:'Request failed'}));}}
  saved(key:string){return this.details()?.sections.flatMap(s=>s.fields).find(f=>f.key===key)?.value;}
  initials(){return (this.details()?.name??'Driver').trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();}
  subtitle(title:string){return title.split(' · ').slice(1).join(' · ')||title;}
  location(){return [this.details()?.city??this.saved('city'),this.details()?.state??this.saved('state')].filter(Boolean).join(', ')||'Location not provided';}
  badge(value:string){return ['Pass','Passed','Active','Verified','Paid','Waived','Online','Ready for trips','API verified'].includes(value)?'primary':['Inactive','Suspended','Rejected','Failed','Expired','Mismatch / Invalid','Invalid'].includes(value)?'error':'secondary';}
  private async loadPhoto(photo:string|null){if(!photo)return;if(/^data:image\/(png|jpeg|webp);base64,/.test(photo)){this.photoUrl.set(photo);return;}if(!photo.startsWith('/uploads/drivers/')){this.photoFailed.set(true);return;}this.photoLoading.set(true);try{const blob=await firstValueFrom(this.http.get(`${environment.apiUrl}${photo}`,{responseType:'blob'}));const header=new Uint8Array(await blob.slice(0,8).arrayBuffer());if(!(header[0]===137&&header[1]===80||header[0]===255&&header[1]===216||new TextDecoder().decode(header).startsWith('RIFF')))throw new Error('Profile photo is damaged');if(this.destroyed)return;const url=URL.createObjectURL(blob);this.photoUrl.set(url);const doc=this.documents().find(doc=>doc.preview===photo);if(doc)this.previews.update(p=>({...p,[doc.id]:{url}}));}catch{if(!this.destroyed)this.photoFailed.set(true);}finally{this.photoLoading.set(false);}}
  value(value:unknown):string {if(value==null||value===''||Array.isArray(value)&&!value.length)return 'Not provided';if(Array.isArray(value))return value.map(v=>this.value(v)).join(', ');if(typeof value==='object')return Object.entries(value).map(([k,v])=>`${k}: ${this.value(v)}`).join('; ');return String(value);}
  date(value:string|null){return value&&Number.isFinite(new Date(value).getTime())?new Date(value).toLocaleString():'Not provided';}
  private async preview(doc:DetailDocument){try{if(!doc.preview)throw new Error('Original file is missing');const blob=await firstValueFrom(this.http.get(`${environment.apiUrl}${doc.preview}`,{responseType:'blob'}));const header=new Uint8Array(await blob.slice(0,8).arrayBuffer());const pdf=new TextDecoder().decode(header).startsWith('%PDF-');const image=header[0]===137&&header[1]===80||header[0]===255&&header[1]===216||new TextDecoder().decode(header).startsWith('RIFF');if(this.destroyed)return;const url=URL.createObjectURL(blob);if(!pdf&&!image){this.previews.update(p=>({...p,[doc.id]:{url,error:'File is damaged or its preview format is unsupported'}}));return;}this.previews.update(p=>({...p,[doc.id]:{url,pdf,safe:this.sanitizer.bypassSecurityTrustResourceUrl(url)}}));}catch(error){const message=error instanceof HttpErrorResponse ? await httpErrorMessage(error) : error instanceof Error?error.message:'File unavailable';if(!this.destroyed)this.previews.update(p=>({...p,[doc.id]:{error:message}}));}}
  damaged(id:string){this.previews.update(p=>({...p,[id]:{...p[id],error:'Image is damaged or unavailable'}}));}
  @HostListener('window:focus')
  async refreshReadiness(){const id=this.details()?.id;if(!id||this.destroyed)return;try{const response=await firstValueFrom(this.http.get<{data:Details}>(`${environment.apiUrl}/drivers/${id}/details`));if(!this.destroyed&&this.details()?.id===id){const changedPhoto=this.details()?.photo!==response.data.photo;this.details.set(response.data);if(changedPhoto){this.photoFailed.set(false);this.photoUrl.set('');await this.loadPhoto(response.data.photo);}const missing=this.documents().filter(doc=>!this.previews()[doc.id]);let next=0;await Promise.all(Array.from({length:Math.min(3,missing.length)},async()=>{while(next<missing.length&&!this.destroyed)await this.preview(missing[next++]);}));}}catch(error){if(!this.destroyed)this.error.set(await httpErrorMessage(error as HttpErrorResponse));}}
  async approveKyc(){if(this.approving()||!this.details()?.approval?.ready)return;this.approving.set(true);try{const data=this.details();if(!data)return;await firstValueFrom(this.http.post(`${environment.apiUrl}/drivers/${data.id}/kyc-approval`,{}));const response=await firstValueFrom(this.http.get<{data:Details}>(`${environment.apiUrl}/drivers/${data.id}/details`));this.details.set(response.data);this.error.set('');}catch(error){this.error.set(await httpErrorMessage(error instanceof HttpErrorResponse?error:{message:error instanceof Error?error.message:'Approval failed'}));await this.refreshReadiness();}finally{this.approving.set(false);this.approvalConfirmation.set(false);}}
  async download(kind:'resume'|'profile'){try{const data=this.details();if(!data)return;const blob=await firstValueFrom(this.http.get(`${environment.apiUrl}/drivers/${data.id}/${kind}.pdf`,{responseType:'blob'}));const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=kind==='resume'?`${data.name.normalize('NFKD').replace(/[^\p{L}\p{N}]+/gu,'_').slice(0,80)||'Driver'}_Driver_Resume.pdf`:`driver-full-report-${data.id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(error){this.error.set(await httpErrorMessage(error instanceof HttpErrorResponse ? error : {message:error instanceof Error?error.message:'Request failed'}));}}
  ngOnDestroy(){this.destroyed=true;new Set([this.photoUrl(),...Object.values(this.previews()).map(p=>p.url)]).forEach(url=>{if(url?.startsWith('blob:'))URL.revokeObjectURL(url);});}
}
