import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting, TestRequest } from '@angular/common/http/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { provideSharedAuth } from '@skylabs-monorepo/shared-auth/angular';
import { DriverDetails } from './driver-details';
describe('read-only Driver Details',()=>{
  beforeEach(async()=>{await TestBed.configureTestingModule({imports:[DriverDetails],providers:[provideRouter([]),{provide:ActivatedRoute,useValue:{snapshot:{paramMap:new Map([['id','driver']])}}},provideHttpClient(),provideHttpClientTesting(),provideSharedAuth({appPrefix:'test_md',apiBaseUrl:'http://localhost/api'})]}).compileComponents();});
  afterEach(()=>{TestBed.inject(HttpTestingController).verify();TestBed.resetTestingModule();});
  it('renders continuous sections, saved false/zero values, missing fields and distinct blocking statuses without checklist or tabs',async()=>{
    const fixture=TestBed.createComponent(DriverDetails);fixture.detectChanges();TestBed.inject(HttpTestingController).expectOne(r=>r.url.endsWith('/drivers/driver/details')).flush({data:{id:'driver',name:'Ravi',photo:null,account:'Active',kyc:'Non-Verified',fee:'Unpaid',feeRequired:true,reasons:['Required registration fee is not settled'],sections:[{title:'Personal Details · Identity',completed:false,fields:[{key:'firstName',label:'First name',value:'Ravi'},{key:'age',label:'Age',value:null},{key:'online',label:'Online',value:false},{key:'amount',label:'Amount',value:0}],documents:[]},{title:'Payment Details · Account Details',completed:false,fields:[{key:'bank',label:'Bank name',value:'Saved bank'}],documents:[]}]}});await fixture.whenStable();fixture.detectChanges();const el=fixture.nativeElement as HTMLElement;expect(el.textContent).toContain('Saved bank');expect(el.textContent).toContain('Not provided');expect(el.textContent).toContain('Required registration fee is not settled');expect(el.querySelector('md-pill-review')).toBeNull();expect(el.querySelector('md-tabs')).toBeNull();expect(fixture.componentInstance.value(false)).toBe('false');expect(fixture.componentInstance.value(0)).toBe('0');fixture.destroy();
  });
  it('shows the real HTTP error without attributing every failure to permissions',async()=>{const fixture=TestBed.createComponent(DriverDetails);fixture.detectChanges();TestBed.inject(HttpTestingController).expectOne(r=>r.url.endsWith('/details')).flush({error:{message:'Driver not found'}},{status:404,statusText:'Not Found'});await vi.waitFor(()=>expect(fixture.componentInstance.error()).toContain('Driver not found'));fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Driver not found');fixture.destroy();});
  it('shows actual header contacts, compact independent statuses, progress and missing-photo initials with permission-safe actions',async()=>{
    const fixture=TestBed.createComponent(DriverDetails);vi.spyOn(fixture.componentInstance.auth,'can').mockReturnValue(false);fixture.detectChanges();TestBed.inject(HttpTestingController).expectOne(r=>r.url.endsWith('/details')).flush({data:{id:'driver',name:'Actual Driver',photo:null,city:'Pune',state:'Maharashtra',phone:'9876543210',email:'fixture@example.org',availability:'Offline',account:'Active',kyc:'Non-Verified',fee:'Unpaid',feeRequired:true,reasons:['KYC approval is required'],onboarding:{status:'in_progress',percentage:45,completed:5,total:11,tab:'Education & Health Details',pill:'Health & Medical Specifications'},sections:[]}});await fixture.whenStable();fixture.detectChanges();const element=fixture.nativeElement as HTMLElement;expect(element.textContent).toContain('Profile photo missing');expect(element.querySelector('.initials')?.textContent).toBe('AD');expect(element.textContent).toContain('Pune, Maharashtra');expect(element.textContent).toContain('fixture@example.org');expect(element.textContent).toContain('Health & Medical Specifications');expect(element.querySelectorAll('.status-card')).toHaveLength(4);expect(element.querySelectorAll('.blockers')).toHaveLength(1);expect(element.textContent).not.toContain('Edit Driver');expect(element.textContent).not.toContain('Download Full Report');expect(element.textContent).toContain('Resume Preview');fixture.destroy();
  });
  it('replaces a damaged saved image with initials and a clear state instead of a broken image',async()=>{
    const fixture=TestBed.createComponent(DriverDetails);fixture.detectChanges();TestBed.inject(HttpTestingController).expectOne(r=>r.url.endsWith('/details')).flush({data:{id:'driver',name:'Actual Driver',photo:'data:image/png;base64,YmFk',account:'Active',kyc:'Non-Verified',fee:'Unpaid',reasons:[],sections:[]}});await fixture.whenStable();fixture.detectChanges();fixture.nativeElement.querySelector('.photo').dispatchEvent(new Event('error'));fixture.detectChanges();expect(fixture.nativeElement.querySelector('.photo')).toBeNull();expect(fixture.nativeElement.textContent).toContain('Profile photo missing');expect(fixture.nativeElement.querySelector('.initials').textContent).toBe('AD');fixture.destroy();
  });
  it('fetches the actual photo through the authenticated file URL and shows only an ephemeral blob in the header',async()=>{
    const url=vi.spyOn(URL,'createObjectURL').mockReturnValue('blob:profile-photo');const fixture=TestBed.createComponent(DriverDetails);fixture.detectChanges();const http=TestBed.inject(HttpTestingController);http.expectOne(r=>r.url.endsWith('/details')).flush({data:{id:'driver',name:'Actual Driver',photo:'/uploads/drivers/driver/photo.png',account:'Active',kyc:'Non-Verified',fee:'Unpaid',reasons:[],sections:[]}});let request:TestRequest|undefined;await vi.waitFor(()=>{request??=http.match(r=>r.url.endsWith('/uploads/drivers/driver/photo.png'))[0];expect(request).toBeDefined();});const photo=new Blob(['photo fixture'],{type:'image/png'});vi.spyOn(photo,'slice').mockReturnValue({arrayBuffer:async()=>new Uint8Array([137,80,78,71]).buffer} as Blob);request!.flush(photo);await vi.waitFor(()=>expect(fixture.componentInstance.photoUrl()).toBe('blob:profile-photo'));await fixture.whenStable();fixture.detectChanges();expect(fixture.nativeElement.querySelector('.photo')?.getAttribute('src')).toBe('blob:profile-photo');expect(fixture.componentInstance.photoFailed()).toBe(false);fixture.destroy();url.mockRestore();
  });
  it('isolates missing-original failures and retains the saved fields and version metadata',async()=>{
    const fixture=TestBed.createComponent(DriverDetails);fixture.detectChanges();const http=TestBed.inject(HttpTestingController);
    http.expectOne(r=>r.url.endsWith('/details')).flush({data:{id:'driver',name:'Ravi',photo:null,account:'Active',kyc:'Non-Verified',fee:'Unpaid',reasons:[],sections:[{title:'Documents',completed:false,fields:[{key:'dlNo',label:'Saved licence',value:'Saved value'}],documents:[{id:'old',type:'Licence',category:'personal',fileName:'missing.pdf',version:1,createdAt:'2026-09-01',archivedAt:'2026-10-01',preview:'/uploads/drivers/driver/missing.pdf',review:{status:'Issue',reason:'Replace unreadable scan'}}]}]}});
    let preview:TestRequest|undefined;
    await vi.waitFor(()=>{preview??=http.match(r=>r.url.endsWith('/missing.pdf'))[0];expect(preview).toBeDefined();});
    preview!.flush(new Blob([JSON.stringify({error:{message:'Original not found'}})],{type:'application/json'}),{status:404,statusText:'Not Found'});
    await vi.waitFor(()=>expect(fixture.componentInstance.previews()['old']?.error).toContain('HTTP 404: Original not found'));
    fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Saved value');expect(fixture.nativeElement.textContent).toContain('Previous version history');expect(fixture.nativeElement.textContent).toContain('Replace unreadable scan');
    fixture.destroy();
  });
  it('groups current checklist metadata dynamically and keeps offline trip blocking separate from approved KYC',async()=>{const f=TestBed.createComponent(DriverDetails);f.detectChanges();const checks=['Passed','Pending','Issue','Review required after changes'].map((status,index)=>({key:'field:'+index,field:'field'+index,label:'Readable field '+index,tab:1,pill:0,tabLabel:'Personal Details',pillLabel:'Identity',status}));TestBed.inject(HttpTestingController).expectOne(r=>r.url.endsWith('/details')).flush({data:{id:'driver',name:'Saved Driver',photo:null,account:'Active',kyc:'Verified',fee:'Paid',feeRequired:false,availability:'Offline',reasons:['Driver is offline'],approval:{ready:false,reasons:[],checklist:checks},sections:[{title:'Personal Details \u00b7 Identity',completed:true,fields:[],documents:[]},{title:'Personal Details \u00b7 Contact',completed:true,fields:[],documents:[]}]}});await f.whenStable();f.detectChanges();expect(f.componentInstance.groups()).toHaveLength(1);expect(f.componentInstance.approvalGroups()[0]).toMatchObject({passed:1,pending:1,issues:1,stale:1});expect(f.nativeElement.textContent).toContain('KYC Approved');expect(f.nativeElement.querySelector('.blockers').textContent).toContain('Driver is offline');expect(f.nativeElement.querySelector('.blockers').textContent).not.toContain('payment');f.componentInstance.requestApproval();expect(f.componentInstance.approvalConfirmation()).toBe(false);f.destroy();});
});
