import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { AuthService } from '@skylabs-monorepo/shared-auth/angular';
import { ResumePreview, ResumeSnapshot } from './resume-preview';

const snapshot:ResumeSnapshot={html:'<html><body><h1>Actual Driver</h1><p>Saved facts</p></body></html>',revision:'a'.repeat(64),filename:'Actual_Driver_Resume.pdf',missing:['Education institution'],data:{name:'Actual Driver'},profile:{summary:'',workExperience:[],keySkills:[],transmissionSkills:[],education:{institution:'',location:'',year:''},availability:'',servicePreferences:[],sharePhone:true,shareEmail:true}};
describe('professional resume preview',()=>{
  async function setup(id:string|null,edit=true){await TestBed.configureTestingModule({imports:[ResumePreview],providers:[provideRouter([]),provideHttpClient(),provideHttpClientTesting(),{provide:ActivatedRoute,useValue:{snapshot:{paramMap:new Map(id?[['id',id]]:[])}}},{provide:AuthService,useValue:{can:(_menu:string,action:string)=>action!=='edit'||edit}}]}).compileComponents();const fixture=TestBed.createComponent(ResumePreview);fixture.detectChanges();TestBed.inject(HttpTestingController).expectOne(r=>r.url.endsWith(`/drivers/${id??'me'}/resume`)).flush({data:snapshot});await fixture.whenStable();fixture.detectChanges();return fixture;}
  afterEach(()=>{TestBed.inject(HttpTestingController).verify();TestBed.resetTestingModule();});
  it('uses the backend HTML snapshot in a script-disabled preview and shows missing source fields outside it',async()=>{const fixture=await setup('driver');const frame=fixture.nativeElement.querySelector('iframe');expect(frame.getAttribute('sandbox')).toBe('allow-same-origin');expect(frame.getAttribute('srcdoc')).toContain('Saved facts');expect(fixture.nativeElement.textContent).toContain('Education institution: Not provided');expect(fixture.nativeElement.textContent).toContain('Download PDF');fixture.destroy();});
  it('uses the own route and exposes no staff editor to a driver',async()=>{const fixture=await setup(null);expect(fixture.componentInstance.base).toMatch(/\/drivers\/me$/);expect(fixture.componentInstance.canEdit()).toBe(false);expect(fixture.nativeElement.textContent).not.toContain('Review / edit resume facts');fixture.destroy();});
  it('saves actual structured employment with a revision and audited reason',async()=>{const fixture=await setup('driver');const component=fixture.componentInstance;component.addExperience();component.profile.workExperience[0]={jobTitle:'Driver',employer:'Saved Employer',location:'Pune',startDate:'2020-01',endDate:'',current:true,responsibilities:[]};component.responsibilityTexts[0]='Saved responsibility';component.reason='Confirmed facts';const promise=component.save();const request=TestBed.inject(HttpTestingController).expectOne(r=>r.method==='PATCH');expect(request.request.body).toMatchObject({revision:snapshot.revision,reason:'Confirmed facts',profile:{workExperience:[{employer:'Saved Employer',current:true,responsibilities:['Saved responsibility']}]}});expect(request.request.body.status).toBeUndefined();request.flush({data:{...snapshot,revision:'b'.repeat(64)}});await promise;expect(component.snapshot()?.revision).toBe('b'.repeat(64));fixture.destroy();});
  it('reports stale snapshot HTTP errors instead of claiming a permission failure',async()=>{const fixture=await setup('driver');const download=fixture.componentInstance.download();const req=TestBed.inject(HttpTestingController).expectOne(r=>r.url.endsWith('/resume.pdf'));expect(req.request.params.get('revision')).toBe(snapshot.revision);req.flush(new Blob([JSON.stringify({error:{message:'Driver resume changed. Reload the preview before downloading.'}})],{type:'application/json'}),{status:409,statusText:'Conflict'});await download;expect(fixture.componentInstance.error()).toContain('HTTP 409: Driver resume changed');fixture.destroy();});
});
