import { beforeEach, describe, expect, it, vi } from 'vitest';
import { mockPrisma,resetPrismaMock } from '../test-utils/prisma-mock';
vi.mock('../lib/prisma',()=>({prisma:mockPrisma}));
import { addDriverDocument,deleteDriverDocument } from './driver.service';
import { pillItems } from './driver-pill.service';
beforeEach(()=>{resetPrismaMock();mockPrisma.driver.findUnique.mockResolvedValue({id:'d',documents:[]});});
describe('document replacement history',()=>{
 it('links the current protected profile-photo version to Driver.avatar in the existing upload transaction',async()=>{mockPrisma.driverDocument.findFirst.mockResolvedValue({version:1});mockPrisma.driverDocument.create.mockResolvedValue({id:'photo',version:2,filePath:'drivers/d/new-photo.png'});await addDriverDocument({driverId:'d',category:'personal',type:'Profile Photo',filePath:'drivers/d/new-photo.png',mimeType:'image/png'});expect(mockPrisma.driver.update).toHaveBeenCalledWith({where:{id:'d'},data:{status:'Non-Verified',avatar:'drivers/d/new-photo.png'}});expect(mockPrisma.driverDocument.updateMany).toHaveBeenCalled();expect(mockPrisma.driverDocument.delete).not.toHaveBeenCalled();});
 it.each([{filePath:'drivers/d/photo.pdf',mimeType:'application/pdf'},{filePath:'drivers/other/photo.png',mimeType:'image/png'}])('rejects invalid profile-photo metadata without modifying avatar: %j',async input=>{await expect(addDriverDocument({driverId:'d',category:'personal',type:'Profile Photo',...input})).rejects.toMatchObject({code:'PROFILE_PHOTO_INVALID'});expect(mockPrisma.driver.update).not.toHaveBeenCalled();});
 it('archives previous uploads, creates the next version and revokes approval without deleting decisions',async()=>{mockPrisma.driverDocument.findFirst.mockResolvedValue({version:2});mockPrisma.driverDocument.create.mockResolvedValue({id:'new',version:3});await addDriverDocument({driverId:'d',category:'personal',type:'Licence',fileName:'new.pdf'});expect(mockPrisma.driverDocument.updateMany).toHaveBeenCalledWith({where:{driverId:'d',category:'personal',type:'Licence',archivedAt:null},data:{archivedAt:expect.any(Date)}});expect(mockPrisma.driverDocument.create).toHaveBeenCalledWith({data:expect.objectContaining({version:3,fileName:'new.pdf'})});expect(mockPrisma.driver.update).toHaveBeenCalledWith({where:{id:'d'},data:{status:'Non-Verified'}});expect(mockPrisma.driverDocument.delete).not.toHaveBeenCalled();expect(mockPrisma.driverKycDecision.deleteMany).not.toHaveBeenCalled();});
 it('retains archived versions in storage but checks only the current submission',()=>{const previous={id:'old',type:'Licence',category:'personal',filePath:'old.pdf',fileName:'old.pdf',regNo:null,archivedAt:new Date()};const next={...previous,id:'new',filePath:'new.pdf',archivedAt:null};const items=pillItems({documents:[previous,next]}).flatMap(p=>p.items).filter(i=>i.key.startsWith('document:'));expect(items.map(i=>i.key)).toEqual(['document:new']);});
 it('cannot withdraw another driver’s document',async()=>{mockPrisma.driverDocument.findFirst.mockResolvedValue(null);await expect(deleteDriverDocument('d','other')).rejects.toMatchObject({status:404});expect(mockPrisma.driverDocument.update).not.toHaveBeenCalled();});
});
