import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import { mockPrisma, resetPrismaMock } from '../test-utils/prisma-mock';
vi.mock('../lib/prisma',()=>({prisma:mockPrisma}));
import { submissionHash, dlReviewState, dlVerificationPreflight } from './driver-dl.service';
const driver={id:'d',userId:'owner',assignedVerifierId:'reviewer',dlNo:'UP53 20260001705',dob:'2004-04-24'};
beforeEach(()=>{resetPrismaMock();mockPrisma.driver.findFirst.mockResolvedValue(driver);mockPrisma.auditLog.findMany.mockResolvedValue([]);vi.stubEnv('IDSPAY_DL_API_ID','');vi.stubGlobal('fetch',vi.fn());});
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
describe('Explicit assigned reviewer verification, historical records retained',()=>{
 it('restricts checks to the assignment unless existing administrative policy explicitly allows access',async()=>{mockPrisma.driver.findFirst.mockResolvedValue(null);await expect(dlVerificationPreflight('d','owner')).rejects.toMatchObject({status:404});expect(mockPrisma.driver.findFirst).toHaveBeenCalledWith({where:{id:'d',assignedVerifierId:'owner'}});await expect(dlVerificationPreflight('d','admin',false,{administrative:true})).rejects.toMatchObject({status:404});expect(mockPrisma.driver.findFirst).toHaveBeenLastCalledWith({where:{id:'d'}});expect(fetch).not.toHaveBeenCalled();});
 it('inline repeated normalized inputs reuse the same persisted blocked check without retry or approval',async()=>{const consent={action:'driver.dl.consent',after:{submissionHash:submissionHash(driver),consent:true}};mockPrisma.auditLog.findMany.mockResolvedValue([consent]);const first=await dlVerificationPreflight('d','reviewer',false);const calls=mockPrisma.auditLog.create.mock.calls.length;mockPrisma.auditLog.findMany.mockResolvedValue([{action:'driver.dl.preflight',after:first},consent]);expect(await dlVerificationPreflight('d','reviewer',false)).toEqual(first);expect(mockPrisma.auditLog.create.mock.calls.length).toBe(calls);expect(mockPrisma.driver.update).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();});
 it('restores only matching saved DL state with checked timestamp and no invented validity',async()=>{const consent={action:'driver.dl.consent',after:{submissionHash:submissionHash(driver),consent:true}};mockPrisma.auditLog.findMany.mockResolvedValue([consent]);const attempt=await dlVerificationPreflight('d','reviewer',false);const checkedAt=new Date();mockPrisma.auditLog.findMany.mockResolvedValue([{action:'driver.dl.preflight',after:attempt,createdAt:checkedAt},consent]);expect(await dlReviewState('d',driver)).toMatchObject({status:'Provider failed',checkedAt,providerCalled:false,validFrom:null,validTo:null,inputs:{dlNo:driver.dlNo,dob:driver.dob}});expect((await dlReviewState('d',{...driver,dlNo:'UP5320260001706'})).status).toBe('Not checked');});
 it('records a missing-config preflight, requires deliberate retry, and calls the confirmed provider only on explicit retry',async()=>{const consent={action:'driver.dl.consent',after:{submissionHash:submissionHash(driver),consent:true}};mockPrisma.auditLog.findMany.mockResolvedValue([consent]);const first=await dlVerificationPreflight('d','reviewer');expect(first).toMatchObject({status:'Provider failed',reason:'IDSPAY_NOT_CONFIGURED',providerCalled:false});mockPrisma.auditLog.findMany.mockResolvedValue([consent,{action:'driver.dl.preflight',after:first}]);expect(await dlVerificationPreflight('d','reviewer')).toEqual(first);vi.stubEnv('IDSPAY_DL_API_ID','fixture');vi.stubEnv('IDSPAY_DL_API_KEY','fixture');vi.stubEnv('IDSPAY_DL_TOKEN_ID','fixture');vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({result_code:103,http_response_code:200})} as Response);expect(await dlVerificationPreflight('d','reviewer',true)).toMatchObject({status:'Invalid / no record found',providerCalled:true});expect(fetch).toHaveBeenCalledTimes(1);});
});

it('supersedes only obsolete disabled-contract preflights, saves restricted real-format results and caches unchanged inputs',async()=>{
 const consent={action:'driver.dl.consent',after:{submissionHash:submissionHash(driver),consent:true}};
 mockPrisma.auditLog.findMany.mockResolvedValue([consent,{action:'driver.dl.preflight',after:{...consent.after,status:'Manual review required',providerCalled:false,reason:'IDSPAY_REQUEST_DETAILS_MISSING'}}]);
 vi.stubEnv('IDSPAY_DL_API_ID','fixture');vi.stubEnv('IDSPAY_DL_API_KEY','fixture-key');vi.stubEnv('IDSPAY_DL_TOKEN_ID','fixture-token');
 vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({result_code:103,message:'No record found, Invalid DL number',http_response_code:200,request_id:'safe-reference'})} as Response);
 const result=await dlVerificationPreflight('d','reviewer');expect(result).toMatchObject({status:'Invalid / no record found',providerCalled:true,providerReference:'safe-reference'});
 expect(JSON.stringify(result)).not.toContain('fixture-key');expect(JSON.stringify(result)).not.toContain('fixture-token');expect(mockPrisma.driver.update).not.toHaveBeenCalled();
 mockPrisma.auditLog.findMany.mockResolvedValue([{action:'driver.dl.verification',after:result,createdAt:new Date()},consent]);expect(await dlVerificationPreflight('d','reviewer')).toEqual(result);expect(fetch).toHaveBeenCalledTimes(1);
 expect((await dlReviewState('d',{...driver,dob:'2004-04-25'})).status).toBe('Not checked');
});

it('persists and restores a synthetic confirmed-format success without changing human KYC',async()=>{
 const consent={action:'driver.dl.consent',after:{submissionHash:submissionHash(driver),consent:true}};mockPrisma.auditLog.findMany.mockResolvedValue([consent]);
 vi.stubEnv('IDSPAY_DL_API_ID','fixture');vi.stubEnv('IDSPAY_DL_API_KEY','fixture');vi.stubEnv('IDSPAY_DL_TOKEN_ID','fixture');
 vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({status:{code:200,type:'success'},data:{dl_number:'UP5320260001705',dob:'24-04-2004',details_of_driving_licence:{status:'Active',name:'Synthetic fixture',date_of_issue:'01-01-2026'},dl_validity:{non_transport:{from:'01-01-2026',to:'09-08-2040'},transport:{from:'NA',to:'NA'}},badge_details:[{class_of_vehicle:['LMV']}]}})} as Response);
 const result=await dlVerificationPreflight('d','reviewer');expect(result).toMatchObject({status:'API verified',identityMatch:true,providerCalled:true,validTo:'2040-08-09'});expect(mockPrisma.driver.update).not.toHaveBeenCalled();expect(mockPrisma.driverKycCheck.update).not.toHaveBeenCalled();
 mockPrisma.auditLog.findMany.mockResolvedValue([{id:'attempt',action:'driver.dl.verification',after:result,createdAt:new Date()},consent]);expect(await dlReviewState('d',driver)).toMatchObject({status:'API verified',identityMatch:true,validTo:'2040-08-09'});
});


it('allows an assigned reviewer to verify without a linked User, phone, or consent and never fabricates agreement',async()=>{mockPrisma.driver.findFirst.mockResolvedValue({...driver,userId:null,phone:null});vi.stubEnv('IDSPAY_DL_API_ID','fixture');vi.stubEnv('IDSPAY_DL_API_KEY','fixture');vi.stubEnv('IDSPAY_DL_TOKEN_ID','fixture');vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({result_code:103,http_response_code:200})} as Response);expect(await dlVerificationPreflight('d','reviewer')).toMatchObject({status:'Invalid / no record found',providerCalled:true});expect(fetch).toHaveBeenCalledTimes(1);expect(mockPrisma.driver.findFirst).toHaveBeenCalledWith({where:{id:'d',assignedVerifierId:'reviewer'}});const audit=mockPrisma.auditLog.create.mock.calls[0][0].data;expect(audit).toMatchObject({actorUserId:'reviewer',action:'driver.dl.verification',targetId:'d'});expect(audit.after).not.toHaveProperty('consent');expect(mockPrisma.user.create).not.toHaveBeenCalled();expect(mockPrisma.driver.update).not.toHaveBeenCalled();expect(mockPrisma.driverKycCheck.update).not.toHaveBeenCalled();});
it('rejects missing/malformed saved DL and DOB before the provider request',async()=>{for(const [change,code] of [[{dlNo:null},'DL_NUMBER_INVALID'],[{dob:null},'DL_DOB_INVALID'],[{dob:'2027-02-29'},'DL_DOB_INVALID'],[{dlNo:'!invalid'},'DL_NUMBER_INVALID']] as const){mockPrisma.driver.findFirst.mockResolvedValue({...driver,...change});await expect(dlVerificationPreflight('d','reviewer')).rejects.toMatchObject({status:422,code});}expect(fetch).not.toHaveBeenCalled();expect(mockPrisma.auditLog.create).not.toHaveBeenCalled();});
it('preserves historical consent exactly as history without presenting consent as readiness',async()=>{const historic={id:'historic',actorUserId:'old-owner',action:'driver.dl.consent',after:{consent:true,submissionHash:'old'},createdAt:new Date()};mockPrisma.auditLog.findMany.mockResolvedValue([historic]);const state=await dlReviewState('d',driver);expect(state.history).toContainEqual(expect.objectContaining({id:'historic',action:historic.action,summary:expect.objectContaining({consent:true})}));expect(state).not.toHaveProperty('consented');expect(state.reason).toBe('Verify the saved driving licence.');expect(mockPrisma.auditLog.update).not.toHaveBeenCalled();expect(mockPrisma.auditLog.deleteMany).not.toHaveBeenCalled();});
it('reports specific saved identity mismatch, expired validity, and provider authentication failure separately',async()=>{vi.stubEnv('IDSPAY_DL_API_ID','fixture');vi.stubEnv('IDSPAY_DL_API_KEY','fixture');vi.stubEnv('IDSPAY_DL_TOKEN_ID','fixture');const data={dl_number:driver.dlNo,dob:'25-04-2004',details_of_driving_licence:{status:'Active',name:'Synthetic fixture'},dl_validity:{non_transport:{from:'01-01-2020',to:'09-08-2099'},transport:{from:'NA',to:'NA'}},badge_details:[{class_of_vehicle:['LMV']}]};vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({status:{code:200,type:'success'},data})} as Response);const mismatch=await dlVerificationPreflight('d','reviewer');mockPrisma.auditLog.findMany.mockResolvedValue([{action:'driver.dl.verification',after:mismatch,createdAt:new Date()}]);expect(await dlReviewState('d',driver)).toMatchObject({status:'Mismatch/Invalid',reason:'The returned date of birth does not match the saved DOB.'});mockPrisma.auditLog.findMany.mockResolvedValue([]);vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({status:{code:200,type:'success'},data:{...data,dob:'24-04-2004',dl_validity:{non_transport:{from:'01-01-2020',to:'01-01-2021'},transport:{from:'NA',to:'NA'}}}})} as Response);expect(await dlVerificationPreflight('d','reviewer',true)).toMatchObject({status:'Expired'});vi.mocked(fetch).mockResolvedValue({ok:false,status:401} as Response);expect(await dlVerificationPreflight('d','reviewer',true)).toMatchObject({status:'Provider failed',reason:'IDSPAY_AUTHENTICATION_FAILED'});});
it('restores staff name/time only for current evidence and ignores changed inputs without touching history',async()=>{const after={submissionHash:submissionHash(driver),status:'API verified',providerCalled:true,trustedAssessment:true,identityMatch:true,validTo:'2099-08-09'};mockPrisma.auditLog.findMany.mockResolvedValue([{id:'saved',actorUserId:'reviewer',action:'driver.dl.verification',after,createdAt:new Date()}]);mockPrisma.user.findUnique.mockResolvedValue({name:'Saved Reviewer'});expect(await dlReviewState('d',driver)).toMatchObject({checkedByName:'Saved Reviewer',status:'API verified'});expect((await dlReviewState('d',{...driver,userId:null})).status).toBe('API verified');expect((await dlReviewState('d',{...driver,dob:'2004-04-25'})).status).toBe('Not checked');expect(mockPrisma.auditLog.deleteMany).not.toHaveBeenCalled();});
it('coalesces a retry already completed after a concurrent request began',async()=>{mockPrisma.auditLog.findMany.mockResolvedValue([{action:'driver.dl.verification',after:{submissionHash:submissionHash(driver),status:'Invalid / no record found',providerCalled:true},createdAt:new Date(Date.now()+1000)}]);expect(await dlVerificationPreflight('d','reviewer',true)).toMatchObject({providerCalled:true});expect(fetch).not.toHaveBeenCalled();expect(mockPrisma.$queryRaw).toHaveBeenCalled();});
it('keeps retired consent OTP challenges out of normal login',async()=>{const {requestOtp,verifyOtp}=await import('./otp.service');await expect(requestOtp('dl-consent:legacy','login')).rejects.toMatchObject({code:'OTP_PURPOSE_RESTRICTED'});await expect(verifyOtp('dl-consent:legacy','login','123456')).rejects.toMatchObject({code:'OTP_PURPOSE_RESTRICTED'});expect(mockPrisma.user.create).not.toHaveBeenCalled();expect(mockPrisma.otpChallenge.findFirst).not.toHaveBeenCalled();});

it('timestamps paid attempts after response completion so overlapping deliberate retries coalesce',async()=>{vi.stubEnv('IDSPAY_DL_API_ID','fixture');vi.stubEnv('IDSPAY_DL_API_KEY','fixture');vi.stubEnv('IDSPAY_DL_TOKEN_ID','fixture');let respondedAt=0;vi.mocked(fetch).mockImplementation(async()=>{await new Promise(resolve=>setTimeout(resolve,5));respondedAt=Date.now();return {ok:true,status:200,json:async()=>({result_code:103,http_response_code:200})} as Response;});await dlVerificationPreflight('d','reviewer',true);const audit=mockPrisma.auditLog.create.mock.calls[0][0].data;expect(audit.createdAt.getTime()).toBeGreaterThanOrEqual(respondedAt);});
