import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import { searchLocation } from './location-search.service';
beforeEach(()=>{vi.stubEnv('GOOGLE_MAPS_SERVER_KEY','fixture-server-only');});
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
describe('bounded server-side address lookup',()=>{
  it('fails clearly without configuration, without calling a provider',async()=>{vi.stubEnv('GOOGLE_MAPS_SERVER_KEY','');const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(searchLocation('Pune')).rejects.toMatchObject({code:'LOCATION_NOT_CONFIGURED'});expect(fetch).not.toHaveBeenCalled();});
  it('uses the documented GET contract and returns only validated location data',async()=>{const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({status:'OK',results:[{formatted_address:'Pune, India',place_id:'place',geometry:{location:{lat:18.5,lng:73.8}},address_components:[{types:['locality'],long_name:'Pune'}]}]})});vi.stubGlobal('fetch',fetch);expect(await searchLocation('Pune, India')).toEqual([{name:'Pune, India',address:'Pune, India',placeId:'place',lat:18.5,lng:73.8,city:'Pune',state:undefined}]);const [url,options]=fetch.mock.calls[0];expect(url.pathname).toBe('/maps/api/geocode/json');expect(url.searchParams.get('address')).toBe('Pune, India');expect(options.signal).toBeInstanceOf(AbortSignal);});
  it.each(['REQUEST_DENIED','OVER_QUERY_LIMIT','UNKNOWN_ERROR'])('does not accept HTTP 200 with %s',async status=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({status})}));await expect(searchLocation('Pune')).rejects.toMatchObject({code:'LOCATION_RESPONSE_INVALID'});});
  it('does not retry a failed or timed-out request',async()=>{const fetch=vi.fn().mockRejectedValue(new Error('timeout'));vi.stubGlobal('fetch',fetch);await expect(searchLocation('Pune')).rejects.toMatchObject({code:'LOCATION_PROVIDER_UNAVAILABLE'});expect(fetch).toHaveBeenCalledTimes(1);});
  it('returns no matches for ZERO_RESULTS and skips damaged coordinates',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({status:'ZERO_RESULTS'})}));expect(await searchLocation('Pune')).toEqual([]);vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({status:'OK',results:[{geometry:{location:{lat:999,lng:0}}}]})}));expect(await searchLocation('Pune')).toEqual([]);});
});
