import { beforeEach, describe, expect, it, vi } from 'vitest';
import { mockPrisma, resetPrismaMock } from '../test-utils/prisma-mock';
vi.mock('../lib/prisma',()=>({prisma:mockPrisma}));
import { sweepExpiredOffers, offerDeadline, eligibilityReasons, feeState, assignTrip, transitionTrip, quoteBooking, bookCustomer, customerTrip } from './trip-workflow.service';
import { bookingBalances, recordMovement } from './accounts.service';
import type { Driver, Booking, MoneyMovement } from '../generated/prisma-client';
const driver={id:'d',accountStatus:'Active',completedSubSteps:[10,11,12,13,20,21,30,31,32,40],status:'Verified',dlNo:'DL123',dlExpiryDate:'2099-01-01',online:true,city:'Pune',driverType:'Automatic',registrationFeeRequired:true,registrationFeePaise:20000} as Driver;
const booking={id:'b',driverId:'d',status:'completed',farePaise:100000,commissionBps:1500,commissionPaise:15000,driverSharePaise:85000,city:'Pune',startsAt:new Date('2090-01-01'),endsAt:new Date('2090-01-02')} as Booking;
const movement=(kind:string,amountPaise:number)=>({id:kind,bookingId:'b',driverId:'d',kind,amountPaise} as MoneyMovement);
beforeEach(()=>{resetPrismaMock();vi.unstubAllEnvs();mockPrisma.paymentIntent.findMany.mockResolvedValue([]);});
describe('backend eligibility',()=>{
 it('requires a settled fee only when compulsory',()=>{expect(eligibilityReasons(driver,'Unpaid')).toContain('Required registration fee is not settled');expect(eligibilityReasons({...driver,registrationFeeRequired:false},'Unpaid')).toEqual([]);});
 it.each([['accountStatus','Inactive','Account is not active'],['status','Non-Verified','Final KYC approval is required'],['online',false,'Driver is offline'],['dlExpiryDate','2000-01-01','A valid reviewed driving licence is required']] as const)('blocks %s', (key,value,reason)=>{expect(eligibilityReasons({...driver,[key]:value},'Paid')).toContain(reason);});
 it('blocks city, skill and schedule conflicts',()=>{expect(eligibilityReasons(driver,'Paid',{...booking,city:'Delhi',requiredSkill:'Manual'},1)).toEqual(['City does not match','Required skill does not match','A confirmed trip overlaps this schedule']);});
 it('matches each actual multi-select driver type without partial-word matches',()=>{expect(eligibilityReasons({...driver,driverType:'Car Driver, Ambulance Driver'},'Paid',{...booking,requiredSkill:' ambulance driver '})).toEqual([]);expect(eligibilityReasons({...driver,driverType:'Car Driver, Ambulance Driver'},'Paid',{...booking,requiredSkill:'Driver'})).toContain('Required skill does not match');});
 it('never treats unconfirmed API verification as valid',()=>{vi.stubEnv('DRIVER_DL_POLICY','api');expect(eligibilityReasons(driver,'Paid').join()).toContain('IDSPay verification is unavailable');});
 it('excludes the finance-only fee pill from profile eligibility',()=>expect(eligibilityReasons(driver,'Waived')).toEqual([]));
 it('reports refunded fee separately and never infers payment from profile amount',()=>{expect(feeState(driver,[])).toBe('Unpaid');expect(feeState(driver,[movement('registration_payment',20000)])).toBe('Paid');expect(feeState(driver,[movement('registration_payment',20000),movement('registration_refund',20000)])).toBe('Refunded');});
});
describe('Accounts earned amounts',()=>{
 it('never labels waived funds as a customer collection',async()=>{await expect(recordMovement('actor',{reference:'waived-payment',bookingId:'b',kind:'booking_payment',amountPaise:100000,method:'waiver',reason:'No funds received'})).rejects.toMatchObject({code:'METHOD_INVALID'});expect(mockPrisma.moneyMovement.create).not.toHaveBeenCalled();});
 it('stores the actual outstanding amount of a full registration waiver',async()=>{mockPrisma.moneyMovement.findUnique.mockResolvedValue(null);mockPrisma.driver.findUnique.mockResolvedValue(driver);mockPrisma.moneyMovement.findMany.mockResolvedValue([movement('registration_payment',10000)]);mockPrisma.moneyMovement.create.mockImplementation(async args=>({id:'waiver',...args.data}));const result=await recordMovement('actor',{reference:'full-waiver',driverId:'d',kind:'registration_waiver',amountPaise:0,method:'waiver',reason:'Approved remaining fee exemption'});expect(result.amountPaise).toBe(10000);});
 it('separates 1000 collected, 150 commission and 850 driver earning',()=>expect(bookingBalances(booking,[movement('booking_payment',100000)])).toMatchObject({collected:100000,commission:15000,earned:85000,payable:85000,paid:0}));
 it.each(['requested','confirmed','cancelled'])('does not earn commission on %s',status=>expect(bookingBalances({...booking,status},[movement('booking_payment',100000)])).toMatchObject({commission:0,earned:0,payable:0}));
 it('does not earn unsettled commission',()=>expect(bookingBalances(booking,[movement('booking_payment',50000)])).toMatchObject({commission:0,earned:0,paymentStatus:'partial'}));
 it('reduces payable by actual payouts',()=>expect(bookingBalances(booking,[movement('booking_payment',100000),movement('driver_payout',85000)])).toMatchObject({payable:0,paid:85000,payoutStatus:'paid'}));
 it('restores payable after recovery and reverses it after a full refund',()=>{const history=[movement('booking_payment',100000),movement('driver_payout',85000),movement('driver_recovery',85000)];expect(bookingBalances(booking,history)).toMatchObject({payable:85000,recovered:85000,payoutStatus:'pending'});expect(bookingBalances(booking,[...history,movement('booking_refund',100000)])).toMatchObject({payable:0,commission:0,earned:0,paymentStatus:'refunded'});});
 it('rejects recovery beyond the actual payout',async()=>{mockPrisma.moneyMovement.findUnique.mockResolvedValue(null);mockPrisma.booking.findUnique.mockResolvedValue(booking);mockPrisma.moneyMovement.findMany.mockResolvedValue([movement('driver_payout',85000)]);await expect(recordMovement('actor',{reference:'recovery',bookingId:'b',driverId:'d',kind:'driver_recovery',amountPaise:85001,method:'bank_transfer',reason:'Actual recovered transfer'})).rejects.toMatchObject({code:'RECOVERY_INVALID'});expect(mockPrisma.moneyMovement.create).not.toHaveBeenCalled();});
 it('reverses earning when refunded below the settlement threshold',()=>expect(bookingBalances(booking,[movement('booking_payment',100000),movement('booking_refund',100000)])).toMatchObject({commission:0,earned:0,refunded:100000}));
 it('handles replay idempotently, but rejects mismatched references',async()=>{const prior={...movement('booking_payment',100000),reference:'ref'};mockPrisma.moneyMovement.findUnique.mockResolvedValue(prior);const input={reference:'ref',bookingId:'b',driverId:'d',kind:'booking_payment',amountPaise:100000,method:'cash',reason:'Verified cash receipt'};expect(await recordMovement('actor',input)).toBe(prior);expect(mockPrisma.moneyMovement.create).not.toHaveBeenCalled();await expect(recordMovement('actor',{...input,amountPaise:1})).rejects.toMatchObject({code:'REFERENCE_CONFLICT'});});
 it('rejects excessive refunds and unpaid payouts',async()=>{mockPrisma.moneyMovement.findUnique.mockResolvedValue(null);mockPrisma.booking.findUnique.mockResolvedValue(booking);mockPrisma.moneyMovement.findMany.mockResolvedValue([]);await expect(recordMovement('actor',{reference:'ref',bookingId:'b',driverId:'d',kind:'driver_payout',amountPaise:1,method:'upi',reason:'Payout'})).rejects.toMatchObject({code:'PAYOUT_INVALID'});await expect(recordMovement('actor',{reference:'ref',bookingId:'b',kind:'booking_refund',amountPaise:1,method:'upi',reason:'Refund'})).rejects.toMatchObject({code:'REFUND_INVALID'});});
});
describe('trusted trip transitions',()=>{
 it('rejects accepting an already assigned booking',async()=>{mockPrisma.booking.findUniqueOrThrow.mockResolvedValue({...booking,status:'confirmed'});await expect(assignTrip('b','d','u','Accept','offer')).rejects.toMatchObject({code:'TRIP_UNAVAILABLE'});expect(mockPrisma.booking.update).not.toHaveBeenCalled();});
 it('hides another owner’s booking',async()=>{mockPrisma.booking.findFirst.mockResolvedValue(null);await expect(transitionTrip('b','u',{status:'completed'},{driverId:'d2'})).rejects.toMatchObject({status:404});expect(mockPrisma.booking.findFirst).toHaveBeenCalledWith({where:{id:'b',driverId:'d2'}});});
 it('requires the real customer OTP before starting, and counts the failed attempt',async()=>{mockPrisma.booking.findFirst.mockResolvedValue({...booking,status:'arrived',otp:'123456',otpExpiresAt:new Date('2099-01-01'),otpAttempts:0});await expect(transitionTrip('b','u',{status:'in_progress',otp:'000000'},{driverId:'d'})).rejects.toMatchObject({code:'OTP_INVALID'});expect(mockPrisma.booking.update).toHaveBeenCalledWith({where:{id:'b'},data:{otpAttempts:{increment:1}}});});
 it('rejects an expired trip OTP even if the code happens to match',async()=>{mockPrisma.booking.findFirst.mockResolvedValue({...booking,status:'arrived',otp:'123456',otpExpiresAt:new Date('2000-01-01'),otpAttempts:0});await expect(transitionTrip('b','u',{status:'in_progress',otp:'123456'},{driverId:'d'})).rejects.toMatchObject({code:'OTP_EXPIRED'});});
 it('locks out trip-start verification after too many failed attempts',async()=>{mockPrisma.booking.findFirst.mockResolvedValue({...booking,status:'arrived',otp:'123456',otpExpiresAt:new Date('2099-01-01'),otpAttempts:5});await expect(transitionTrip('b','u',{status:'in_progress',otp:'000000'},{driverId:'d'})).rejects.toMatchObject({code:'OTP_LOCKED'});});
 it('does not allow the customer to complete a driver trip',async()=>{mockPrisma.booking.findFirst.mockResolvedValue({...booking,status:'in_progress'});await expect(transitionTrip('b','u',{status:'completed'},{customerId:'c'})).rejects.toMatchObject({code:'TRANSITION_INVALID'});});
 it('blocks pricing when commission policy is absent',async()=>{mockPrisma.fareRule.findMany.mockResolvedValue([{effectiveFrom:'2020-01-01'}]);vi.stubEnv('BOOKING_COMMISSION_BPS','');await expect(quoteBooking({city:'Pune',service:'Hourly',vehicleCategory:'Car',pickupAddress:'A',dropAddress:'B',startsAt:'2090-01-01',durationMinutes:60,distanceKm:10})).rejects.toMatchObject({code:'COMMISSION_UNCONFIGURED'});});
});

it.each(['cash','razorpay'] as const)('creates a backend-priced %s booking without recording collection',async paymentMode=>{
 mockPrisma.fareRule.findMany.mockResolvedValue([{id:'fare',effectiveFrom:'2020-01-01',commissionBps:1500,baseFare:1000,perKmRate:0,perMinRate:0,driverAllowance:0,surgeMultiplier:1,minFare:1000,createdAt:new Date(),updatedAt:new Date()}]);
 mockPrisma.customer.findUniqueOrThrow.mockResolvedValue({id:'c',firstName:'Customer'});
 mockPrisma.booking.create.mockResolvedValue({id:'b'});mockPrisma.booking.findUniqueOrThrow.mockResolvedValue({id:'b',status:'requested',driverId:null,offers:[],startsAt:new Date('2090-01-01'),endsAt:new Date('2090-01-02')});mockPrisma.driver.findMany.mockResolvedValue([]);mockPrisma.booking.findFirst.mockResolvedValue({id:'b',customerId:'c',driverId:null});
 await bookCustomer('c','actor',{city:'Pune',service:'Hourly',vehicleCategory:'Car',pickupAddress:'A',dropAddress:'B',startsAt:'2090-01-01',durationMinutes:60,distanceKm:0,paymentMode});
 expect(mockPrisma.booking.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({farePaise:100000,paymentMode,paymentStatus:'unpaid'})}));expect(mockPrisma.moneyMovement.create).not.toHaveBeenCalled();
});

describe('COD collector and settlement accounting',()=>{
 it('keeps confirmed driver cash separate from platform receipt and payout',()=>{expect(bookingBalances({...booking,paymentMode:'cash'},[movement('driver_cod_collection',100000)])).toMatchObject({collected:0,customerCollected:100000,commission:15000,earned:85000,driverRetained:85000,commissionReceivable:15000,payable:0,paid:0,paymentStatus:'paid',payoutStatus:'driver_cash_held'});});
 it('clears commission receivable once, without adding a second commission earning',()=>{expect(bookingBalances(booking,[movement('driver_cod_collection',100000),movement('commission_settlement',15000)])).toMatchObject({commission:15000,commissionReceivable:0,driverRetained:85000,payable:0,paid:0,payoutStatus:'settled_by_cod'});});
 it('allocates mixed collections without paying the driver more than available platform funds',()=>{expect(bookingBalances(booking,[movement('booking_payment',60000),movement('driver_cod_collection',40000)])).toMatchObject({collected:60000,driverRetained:40000,commissionReceivable:0,payable:45000});});
 it('does not create earnings for unconfirmed COD or unfinished trips',()=>{expect(bookingBalances(booking,[])).toMatchObject({collected:0,earned:0,payable:0,commission:0});expect(bookingBalances({...booking,status:'confirmed'},[movement('driver_cod_collection',100000)])).toMatchObject({commission:0,earned:0,payable:0});});
 it('rejects duplicate collection beyond the unpaid amount',async()=>{mockPrisma.moneyMovement.findUnique.mockResolvedValue(null);mockPrisma.booking.findUnique.mockResolvedValue({...booking,paymentMode:'cash'});mockPrisma.moneyMovement.findMany.mockResolvedValue([movement('driver_cod_collection',100000)]);await expect(recordMovement('actor',{reference:'extra',bookingId:'b',driverId:'d',kind:'driver_cod_collection',amountPaise:1,method:'cash',reason:'Actual cash'})).rejects.toMatchObject({code:'COD_COLLECTION_INVALID'});});
 it('rejects COD collection attached to another driver',async()=>{mockPrisma.moneyMovement.findUnique.mockResolvedValue(null);mockPrisma.booking.findUnique.mockResolvedValue({...booking,paymentMode:'cash'});mockPrisma.moneyMovement.findMany.mockResolvedValue([]);await expect(recordMovement('actor',{reference:'wrong',bookingId:'b',driverId:'other',kind:'driver_cod_collection',amountPaise:100000,method:'cash',reason:'Actual cash'})).rejects.toMatchObject({code:'DRIVER_MISMATCH'});});
 it('requires collected commission before refunding it',async()=>{mockPrisma.moneyMovement.findUnique.mockResolvedValue(null);mockPrisma.booking.findUnique.mockResolvedValue(booking);mockPrisma.moneyMovement.findMany.mockResolvedValue([]);await expect(recordMovement('actor',{reference:'refund',bookingId:'b',driverId:'d',kind:'commission_refund',amountPaise:15000,method:'bank_transfer',reason:'Actual transfer'})).rejects.toMatchObject({code:'COMMISSION_REFUND_INVALID'});});
 it('restores COD receivable after returning a confirmed commission settlement',()=>{expect(bookingBalances(booking,[movement('driver_cod_collection',100000),movement('commission_settlement',15000),movement('commission_refund',15000)])).toMatchObject({commissionReceivable:15000,commissionSettled:0,commission:15000});});
});

it('does not allow a manual receipt to mark a gateway booking paid',async()=>{mockPrisma.moneyMovement.findUnique.mockResolvedValue(null);mockPrisma.booking.findUnique.mockResolvedValue({...booking,paymentMode:'razorpay'});await expect(recordMovement('actor',{reference:'manual-gateway',bookingId:'b',kind:'booking_payment',amountPaise:100000,method:'cash',reason:'Manual attempt'})).rejects.toMatchObject({code:'GATEWAY_VERIFICATION_REQUIRED'});expect(mockPrisma.moneyMovement.create).not.toHaveBeenCalled();});

it('enforces saved service skills alongside customer preferences, never replacing the saved requirement',async()=>{
 mockPrisma.fareRule.findMany.mockResolvedValue([{id:'fare',requiredDriverSkill:'Car Driver',effectiveFrom:'2020-01-01',commissionBps:1500,baseFare:1000,perKmRate:0,perMinRate:0,driverAllowance:0,surgeMultiplier:1,minFare:1000,createdAt:new Date(),updatedAt:new Date()}]);
 const quote=await quoteBooking({city:'Pune',service:'Hourly',vehicleCategory:'Car',pickupAddress:'A',dropAddress:'B',startsAt:'2090-01-01',durationMinutes:60,distanceKm:0,requiredSkill:'Automatic'});expect(quote.requiredSkill).toBe('Car Driver,Automatic');expect(eligibilityReasons({...driver,driverType:'Automatic'},'Paid',{...booking,requiredSkill:quote.requiredSkill})).toContain('Required skill does not match');expect(eligibilityReasons({...driver,driverType:'Car Driver, Automatic'},'Paid',{...booking,requiredSkill:quote.requiredSkill})).toEqual([]);
});

it('returns only the pending preferred driver name before assignment, without exposing offers or KYC',async()=>{mockPrisma.booking.findFirst.mockResolvedValue({id:'b',customerId:'c',driverId:null,driver:null,offers:[{driver:{id:'d',firstName:'Saved',lastName:'Driver'}}]});const result=await customerTrip('c','b');expect(result.waitingFor).toEqual({id:'d',firstName:'Saved',lastName:'Driver'});expect(result.driver).toBeNull();expect(result).not.toHaveProperty('offers');expect(mockPrisma.booking.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:{id:'b',customerId:'c'}}));});
it('never presents multiple automatic requests as an assigned or preferred driver',async()=>{mockPrisma.booking.findFirst.mockResolvedValue({id:'b',driverId:null,offers:[{driver:{id:'d1'}},{driver:{id:'d2'}}]});expect((await customerTrip('c','b')).waitingFor).toBeNull();});

describe('saved work preferences and configured offer timeout',()=>{
 it('resolves Same State from the actual address and Other States from saved choices',()=>{expect(eligibilityReasons({...driver,city:'Mumbai',state:'Maharashtra',workLocation:'Same State'},'Paid',booking)).toEqual([]);expect(eligibilityReasons({...driver,workLocation:'Other States',workStates:['Delhi']},'Paid',booking).join()).toContain('selected work states');expect(eligibilityReasons({...driver,workLocation:'Other States',workStates:['Maharashtra']},'Paid',booking)).toEqual([]);});
 it('requires only configured job/vehicle requirements and retains legacy city matching',()=>{const trip={...booking,vehicleCategory:'Sedan',pricingSnapshot:{requiredDriverJobType:'Part Time',requiredDriverJobChoice:'Office Work'}};expect(eligibilityReasons({...driver,vehicleType:'Sedan, SUV',jobType:'Full Time, Part Time',jobChoices:['Office Work']},'Paid',trip)).toEqual([]);expect(eligibilityReasons({...driver,vehicleType:'SUV',jobType:'Full Time',jobChoices:[]},'Paid',trip)).toEqual(['Required job type does not match','Required job choice does not match','Vehicle choice does not match']);});
 it('does not invent an offer expiry and accepts only an explicit valid timeout',()=>{vi.stubEnv('TRIP_OFFER_TIMEOUT_SECONDS','');expect(offerDeadline()).toBeNull();vi.stubEnv('TRIP_OFFER_TIMEOUT_SECONDS','120');expect(offerDeadline(new Date('2026-01-01'))!.toISOString()).toBe('2026-01-01T00:02:00.000Z');vi.stubEnv('TRIP_OFFER_TIMEOUT_SECONDS','invalid');expect(()=>offerDeadline()).toThrow('TRIP_OFFER_TIMEOUT_SECONDS');});
});

describe('offer expiry serializes with acceptance',()=>{
 it('does not expire or notify a booking already confirmed by a concurrent winner',async()=>{mockPrisma.tripOffer.findMany.mockResolvedValue([{bookingId:'b'}]);mockPrisma.booking.findUnique.mockResolvedValue({...booking,status:'confirmed',driverId:'d'});await sweepExpiredOffers();expect(mockPrisma.tripOffer.updateMany).not.toHaveBeenCalled();expect(mockPrisma.tripEvent.create).not.toHaveBeenCalled();expect(mockPrisma.portalMessage.create).not.toHaveBeenCalled();});
 it('records a dispatch return only when a pending expired offer was actually closed',async()=>{mockPrisma.tripOffer.findMany.mockResolvedValue([{bookingId:'b'}]);mockPrisma.booking.findUnique.mockResolvedValue({...booking,status:'requested',driverId:null,customer:{userId:'customer-user'}});mockPrisma.tripOffer.updateMany.mockResolvedValue({count:0});await sweepExpiredOffers();expect(mockPrisma.tripEvent.create).not.toHaveBeenCalled();mockPrisma.tripOffer.updateMany.mockResolvedValue({count:1});await sweepExpiredOffers();expect(mockPrisma.tripEvent.create).toHaveBeenCalledWith({data:expect.objectContaining({bookingId:'b',status:'requested'})});expect(mockPrisma.portalMessage.create).toHaveBeenCalledTimes(1);});
});
