import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { provideRouter } from '@angular/router';
import { DriverDocuments } from './documents';
import { vi } from 'vitest';
describe('driver portal document uploads',()=>{
 let component:any;let http:HttpTestingController;
 const saved={id:'saved',category:'health',type:'Medical Certificate',fileName:'saved.pdf',regNo:'ABC',archivedAt:null};
 beforeEach(async()=>{TestBed.resetTestingModule();await TestBed.configureTestingModule({imports:[DriverDocuments],providers:[provideRouter([]),provideHttpClient(),provideHttpClientTesting()]}).compileComponents();const fixture=TestBed.createComponent(DriverDocuments);component=fixture.componentInstance;http=TestBed.inject(HttpTestingController);fixture.detectChanges();expect(component.loading()).toBe(true);expect(component.mastersLoading()).toBe(true);http.expectOne(r=>r.url.endsWith('/masters/onboarding-options')).flush({data:{'health-docs':[{id:'medical',name:'Medical Certificate',status:'Active'},{id:'insurance',name:'Insurance',status:'Active'}]}});http.expectOne(r=>r.url.endsWith('/me/documents')).flush({data:[saved,{...saved,id:'history',archivedAt:'2026-01-01'}]});component.changeCategory('health');});
 afterEach(()=>{http.verify();vi.restoreAllMocks();TestBed.resetTestingModule();});
 it('excludes active saved types and retains every history item',()=>{expect(component.docType()).toBe('');expect(component.options().map((o:any)=>o.id)).toEqual(['insurance']);expect(component.docsFor('health')).toHaveLength(2);});
 it('preselects an explicit replacement and cancel leaves the saved file unchanged',()=>{component.replace(saved);expect(component.docType()).toBe('medical');expect(component.options().map((o:any)=>o.id)).toContain('medical');component.cancelReplacement();expect(component.docType()).toBe('');expect(component.documents()[0].fileName).toBe('saved.pdf');});
 it('retains a failed replacement draft and sends the existing document ID',async()=>{component.replace(saved);component.file=new File(['replacement'],'new.pdf');component.upload();const request=http.expectOne(r=>r.method==='POST');expect(request.request.body.get('replaceDocumentId')).toBe('saved');expect(request.request.body.get('typeKey')).toBe('medical');request.flush({error:{message:'Saved document changed'}},{status:409,statusText:'Conflict'});await vi.waitFor(()=>expect(component.error()).toContain('Saved document changed'));expect(component.replacing().id).toBe('saved');expect(component.file.name).toBe('new.pdf');expect(component.documents()[0].fileName).toBe('saved.pdf');});
 it('keeps a failed withdrawal reserved',async()=>{vi.spyOn(window,'confirm').mockReturnValue(true);component.remove(saved);http.expectOne(r=>r.method==='DELETE').flush({error:{message:'Withdrawal denied'}},{status:403,statusText:'Forbidden'});await vi.waitFor(()=>expect(component.deleting()).toBeNull());expect(component.options().map((o:any)=>o.id)).not.toContain('medical');expect(component.documents()[0].fileName).toBe('saved.pdf');});
 it('clears the selected file without clearing its reserved document type',()=>{component.replace(saved);component.file=new File(['draft'],'draft.pdf');component.clearFile();expect(component.docType()).toBe('medical');expect(component.replacing().id).toBe('saved');expect(component.file).toBeNull();expect(component.documents()[0].fileName).toBe('saved.pdf');});
 it('loads an archived original through the existing authenticated file service and releases its URL',async()=>{vi.spyOn(URL,'createObjectURL').mockReturnValue('blob:archived');const revoke=vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});const doc={...saved,id:'history',filePath:'drivers/own/saved.pdf',archivedAt:'2026-01-01'};const pending=component.preview(doc);const request=http.expectOne(r=>r.url.endsWith('/uploads/drivers/own/saved.pdf'));expect(request.request.responseType).toBe('blob');const blob=new Blob(['%PDF-test'],{type:'application/pdf'});vi.spyOn(blob,'slice').mockReturnValue({arrayBuffer:async()=>new TextEncoder().encode('%PDF-test').buffer} as Blob);request.flush(blob);await pending;expect(component.previews().history.pdf).toBe(true);expect((vi.mocked(URL.createObjectURL).mock.calls[0][0] as Blob).type).toBe('application/pdf');expect(component.previews().history.url).toBe('blob:archived');component.ngOnDestroy();expect(revoke).toHaveBeenCalledWith('blob:archived');});
 it('keeps a denied file preview unavailable without changing the saved document',async()=>{const doc={...saved,filePath:'drivers/own/saved.pdf'};const pending=component.preview(doc);http.expectOne(r=>r.url.endsWith('/uploads/drivers/own/saved.pdf')).flush(new Blob(['Denied'],{type:'application/json'}),{status:404,statusText:'Not Found'});await pending;expect(component.previews().saved.url).toBeUndefined();expect(component.previews().saved.error).toContain('unavailable');expect(component.documents()[0].fileName).toBe('saved.pdf');});

});
