import { Component, CUSTOM_ELEMENTS_SCHEMA, DestroyRef, effect, inject, signal } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { combineLatest } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { AuthService } from '@skylabs-monorepo/shared-auth/angular';
import { AdminPage } from '../../../admin/admin-page/admin-page';
import { environment } from '../../../../environments/environment';
import { httpErrorMessage } from '../../../core/http-error';

type RecordData=Record<string,any>;
interface AccountsData {metrics?:RecordData;totals:RecordData;bookings:RecordData[];drivers:RecordData[];movements:RecordData[];pendingActions:RecordData[];pendingFees?:RecordData[];pendingIntents?:RecordData[];meta:{total:number};dateRule:string;activity?:RecordData[]}
@Component({selector:'md-accounts',imports:[AdminPage,FormsModule,DatePipe,RouterLink],schemas:[CUSTOM_ELEMENTS_SCHEMA],templateUrl:'./accounts.html',styles:[`:host{display:block}.metric-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.metric{font:inherit;text-align:left;color:inherit;cursor:pointer;border:1px solid var(--md-sys-color-outline-variant);border-radius:12px;padding:20px;background:var(--md-sys-color-surface-container-low)}.metric strong{display:block;font-size:24px;margin:10px 0}.actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin:16px 0}label{display:grid;gap:6px}input,select{font:inherit;box-sizing:border-box;max-width:100%;padding:10px;border:1px solid var(--md-sys-color-outline);border-radius:8px;background:var(--md-sys-color-surface);color:inherit}.error{color:var(--md-sys-color-error)}.activity-row{display:flex;gap:12px;align-items:center;justify-content:space-between;padding:12px 0;border-bottom:1px solid var(--md-sys-color-outline-variant)}.activity-row p{margin:4px 0}md-dialog [slot=content]{display:grid;gap:16px;min-width:min(480px,calc(100vw - 80px))}.fields{display:grid;gap:12px}.account-card{margin-top:16px}small{font-size:14px}details{padding:12px 0}`]})
export class Accounts {
  readonly Math=Math;
  readonly auth=inject(AuthService);private readonly http=inject(HttpClient);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly destroy=inject(DestroyRef);readonly base=environment.apiUrl+'/workflow/accounts';
  readonly section=signal('Overview');readonly data=signal<AccountsData|null>(null);readonly loading=signal(false);readonly error=signal('');readonly success=signal('');readonly showFilters=signal(false);readonly page=signal(1);readonly pageSize=signal(25);readonly search=signal('');readonly sort=signal('createdAt');readonly direction=signal<'asc'|'desc'>('desc');
  filters={from:'',to:'',city:'',service:'',paymentStatus:''};private listSequence=0;private contextSequence=0;private accountScope:string|undefined;private routeInitialized=false;
  readonly context=signal<RecordData|null>(null);readonly contextLoading=signal(false);readonly contextError=signal('');readonly contextId=signal('');readonly contextKind=signal<'booking'|'driver'>('booking');readonly dialogOpen=signal(false);readonly submitting=signal(false);readonly operation=signal('');readonly confirming=signal(false);private requestKey='';
  form={amount:0,method:'cash',reference:'',reason:''};policy={amount:0,required:false,reason:''};readonly savingPolicy=signal(false);readonly policyError=signal('');
  readonly fares=signal<RecordData[]>([]);readonly jobMasters=signal<RecordData>({});commissionPolicy={fareId:'',rate:0,requiredDriverSkill:'',requiredDriverJobType:'',requiredDriverJobChoice:'',reason:''};readonly savingCommission=signal(false);readonly commissionError=signal('');
  readonly titles:Record<string,string>={'overview':'Overview','booking-payments':'Booking Payments','registration-fees':'Registration Fees','commissions':'Commissions','driver-payouts':'Driver Payouts','refunds-adjustments':'Refunds & Adjustments','reports':'Reports'};
  constructor(){
    effect(()=>{const session=this.auth.bootstrap?.();const account=session?.user.id;const scope=account?JSON.stringify([account,session?.permissions,session?.roles?.map(role=>role.key),session?.driver?.id,session?.customer?.id]):undefined;if(this.accountScope!==scope){this.accountScope=scope;++this.listSequence;++this.contextSequence;this.data.set(null);this.context.set(null);this.contextId.set('');this.dialogOpen.set(false);this.form={amount:0,method:'cash',reference:'',reason:''};this.policy={amount:0,required:false,reason:''};this.fares.set([]);this.jobMasters.set({});this.commissionPolicy={fareId:'',rate:0,requiredDriverSkill:'',requiredDriverJobType:'',requiredDriverJobChoice:'',reason:''};this.operation.set('');this.confirming.set(false);this.contextError.set('');this.policyError.set('');this.commissionError.set('');this.success.set('');this.error.set('');this.filters={from:'',to:'',city:'',service:'',paymentStatus:''};this.search.set('');this.page.set(1);if(account&&this.routeInitialized)this.load();}});
    combineLatest([this.route.data,this.route.queryParamMap]).pipe(takeUntilDestroyed(this.destroy)).subscribe(([route,query])=>{this.section.set(route['section']??'Overview');for(const key of Object.keys(this.filters) as (keyof typeof this.filters)[])this.filters[key]=query.get(key)??'';this.page.set(1);this.search.set(query.get('search')??'');this.routeInitialized=true;this.load();if(query.get('driverId'))this.openRecord('driver',query.get('driverId')!);else if(query.get('bookingId'))this.openRecord('booking',query.get('bookingId')!);if(this.section()==='Commissions'&&this.auth.can('payments.overview','view'))this.loadCommissionPolicy();});
  }
  canWrite(){return this.auth.can('payments.overview','create')&&this.auth.can('payments.overview','edit');}
  loadCommissionPolicy(){this.http.get<{data:RecordData[]}>(this.base+'/pricing').subscribe({next:r=>{this.fares.set(r.data);if(!this.commissionPolicy.fareId&&r.data[0])this.selectCommissionRule(r.data[0]['id']);},error:async e=>this.commissionError.set(await httpErrorMessage(e))});if(this.auth.can('payments.overview','edit'))this.http.get<{data:RecordData}>(environment.apiUrl+'/masters/onboarding-options').subscribe({next:r=>this.jobMasters.set(r.data),error:async e=>this.commissionError.set(await httpErrorMessage(e))});}
  selectCommissionRule(id:string){const fare=this.fares().find(row=>row['id']===id);this.commissionPolicy={fareId:id,rate:(fare?.['commissionBps']??0)/100,requiredDriverSkill:fare?.['requiredDriverSkill']??'',requiredDriverJobType:fare?.['requiredDriverJobType']??'',requiredDriverJobChoice:fare?.['requiredDriverJobChoice']??'',reason:''};}
  saveCommissionPolicy(){if(!this.auth.can('payments.overview','edit')||this.savingCommission()||!this.commissionPolicy.fareId||!this.commissionPolicy.reason.trim())return;this.savingCommission.set(true);this.commissionError.set('');this.http.patch(`${this.base}/pricing/${this.commissionPolicy.fareId}/commission`,{commissionBps:Math.round(this.commissionPolicy.rate*100),requiredDriverSkill:this.commissionPolicy.requiredDriverSkill||null,requiredDriverJobType:this.commissionPolicy.requiredDriverJobType||null,requiredDriverJobChoice:this.commissionPolicy.requiredDriverJobChoice||null,reason:this.commissionPolicy.reason.trim()}).subscribe({next:()=>{this.savingCommission.set(false);this.success.set('Commission policy saved for new bookings.');this.loadCommissionPolicy();},error:async e=>{this.savingCommission.set(false);this.commissionError.set(await httpErrorMessage(e));}});}
  money(value:number|undefined){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format((value??0)/100);}
  period(){return this.section()==='Booking Payments'||this.section()==='Registration Fees'?'posted':this.section()==='Commissions'?'earned':this.section()==='Driver Payouts'?'current':'created';}
  load(){const sequence=++this.listSequence;this.loading.set(true);this.error.set('');this.data.set(null);let params=new HttpParams().set('section',this.section()).set('page',this.page()).set('pageSize',this.pageSize()).set('search',this.search()).set('sort',this.sort()).set('direction',this.direction()).set('period',this.period());for(const[key,value]of Object.entries(this.filters))if(value)params=params.set(key,value);this.http.get<{data:AccountsData}>(this.base,{params}).subscribe({next:r=>{if(sequence!==this.listSequence)return;this.data.set(r.data);this.loading.set(false);},error:async e=>{const message=await httpErrorMessage(e);if(sequence===this.listSequence){this.loading.set(false);this.error.set(message);}}});}
  params(event:Event){const d=(event as CustomEvent).detail;this.page.set(d.page??1);this.pageSize.set(d.pageSize??25);this.search.set(d.search??'');if(d.sortKey){const allowed:Record<string,string>={fare:'farePaise',payment:'status',amount:'registrationFeePaise',feeStatus:'feeStatus',commission:'commission',earned:'earned',due:'payable'};if(allowed[d.sortKey])this.sort.set(allowed[d.sortKey]);this.direction.set(d.sortDir==='asc'?'asc':'desc');}this.load();}
  apply(){this.page.set(1);this.load();}clear(){this.filters={from:'',to:'',city:'',service:'',paymentStatus:''};this.apply();}
  go(path:string,context:Record<string,string>={},current=false){const filters=current?{city:this.filters.city,service:this.filters.service}:this.filters;void this.router.navigate(['/account/accounts',path],{queryParams:{...filters,...context}});}
  goCard(card:RecordData){const params=card['path']==='registration-fees'?{from:this.filters.from,to:this.filters.to,city:this.filters.city}:card['path']==='driver-payouts'?{city:this.filters.city,service:this.filters.service}:{...this.filters};void this.router.navigate(['/account/accounts',card['path']],{queryParams:params});}
  cards(){const m=this.data()?.metrics;if(!m||!this.auth.can('payments.overview','view'))return [];return [{label:'Platform Collections',value:m['platformCollections'],period:m['postedPeriod'],path:'booking-payments'},{label:'Registration Fees Received',value:m['registrationFeesReceived'],period:m['postedPeriod'],path:'registration-fees'},{label:'Earned Commission',value:m['earnedCommission'],period:m['earnedPeriod'],path:'commissions'},{label:'Driver Payout Due',value:m['driverPayoutDue'],period:'Outstanding as of '+new Date(m['balanceAsOf']).toLocaleString('en-IN'),path:'driver-payouts'}].filter(card=>typeof card.value==='number');}
  columns(){return JSON.stringify(this.section()==='Registration Fees'?[{key:'identity',label:'Driver'},{key:'feeStatus',sortable:true,label:'Status'},{key:'amount',sortable:true,label:'Fee'},{key:'received',label:'Received (net)'},{key:'remaining',label:'Balance due'}]:this.section()==='Driver Payouts'?[{key:'identity',label:'Booking / Driver'},{key:'earned',sortable:true,label:'Earned share'},{key:'retained',label:'Driver-held cash'},{key:'paid',label:'Completed payouts'},{key:'due',sortable:true,label:'Payout due'}]:this.section()==='Commissions'?[{key:'identity',label:'Booking / Customer'},{key:'commission',sortable:true,label:'Earned commission'},{key:'settled',label:'COD commission collected'},{key:'receivable',label:'COD commission due'}]:[{key:'identity',label:'Booking / Customer'},{key:'fare',sortable:true,label:'Fare'},{key:'collected',label:'Platform receipts'},{key:'cod',label:'Driver COD receipts'},{key:'payment',sortable:true,label:'Payment status'}]);}
  rows(){const fee=this.section()==='Registration Fees';return JSON.stringify((fee?this.data()?.drivers:this.data()?.bookings??[])?.map(row=>({...row,identity:fee?`${row['firstName']} ${row['lastName']??''}`:`${row['bookingCode']} · ${this.section()==='Driver Payouts'?row['driverName']??'Unassigned':row['customerName']}`,amount:this.money(row['registrationFeePaise']),received:this.money((row['paidPaise']??0)-(row['refundedPaise']??0)),remaining:this.money(Math.max(0,(row['registrationFeePaise']??0)-(row['paidPaise']??0)+(row['refundedPaise']??0)-(row['waivedPaise']??0))),fare:this.money(row['farePaise']),collected:this.money(row['collected']),cod:this.money(row['driverCollected']),payment:row['paymentStatus'],earned:this.money(row['earned']),retained:this.money(row['driverRetained']),paid:this.money(row['paid']),due:this.money(row['payable']),commission:this.money(row['commission']),settled:this.money(row['commissionSettled']),receivable:this.money(row['commissionReceivable'])}))??[]);}
  actions(){return JSON.stringify([{icon:'visibility',label:({'Registration Fees':'Manage Fee','Commissions':'View Commission','Driver Payouts':'View Settlement'} as Record<string,string>)[this.section()]??'View Receipt',event:'view'},...(this.canWrite()?[{icon:'payments',label:({'Registration Fees':'Record Fee Receipt','Commissions':'Record Collection','Driver Payouts':'Record Completed Payout','Refunds & Adjustments':'Review Adjustment'} as Record<string,string>)[this.section()]??'Record Payment',event:'record'}]:[])]);}
  rowAction(event:Event){const d=(event as CustomEvent).detail;this.openRecord(this.section()==='Registration Fees'?'driver':'booking',d.row.id,d.action==='record');}
  openRecord(kind:'booking'|'driver',id:string,record=false){const sequence=++this.contextSequence;this.contextId.set(id);this.contextKind.set(kind);this.dialogOpen.set(true);this.context.set(null);this.operation.set('');this.contextLoading.set(true);this.contextError.set('');this.policyError.set('');this.confirming.set(false);this.form={amount:0,method:'cash',reference:'',reason:''};this.requestKey=crypto.randomUUID();this.http.get<{data:RecordData}>(`${this.base}/${kind==='driver'?'drivers/'+id+'/fee':'bookings/'+id}`).subscribe({next:r=>{if(sequence!==this.contextSequence)return;this.context.set(r.data);this.contextLoading.set(false);this.policy={amount:(r.data['registrationFeePaise']??0)/100,required:r.data['registrationFeeRequired']??false,reason:''};if(record)this.chooseOperation(this.allowedOperations()[0]??'');},error:async e=>{const message=await httpErrorMessage(e);if(sequence===this.contextSequence){this.contextLoading.set(false);this.contextError.set(message);}}});}
  retryContext(){if(this.contextId())this.openRecord(this.contextKind(),this.contextId());}
  close(){if(this.submitting()||this.savingPolicy())return;this.dialogOpen.set(false);this.context.set(null);this.contextId.set('');++this.contextSequence;this.operation.set('');this.confirming.set(false);this.contextError.set('');}
  cancel(event:Event){if(this.submitting()||this.savingPolicy())event.preventDefault();else this.close();}
  name(){const r=this.context();return r?(this.contextKind()==='driver'?`${r['firstName']} ${r['lastName']??''}`:`${r['bookingCode']} · ${r['customerName']}`):'';}
  label(kind:string){return ({booking_payment:'Record Payment',driver_cod_collection:'Record Driver COD Receipt',commission_settlement:'Record Commission Collection',driver_payout:'Record Completed Payout',booking_refund:'Record Customer Refund',driver_cod_refund:'Record Driver COD Refund',commission_refund:'Record Commission Refund',driver_recovery:'Record Driver Recovery',registration_payment:'Record Fee Receipt',registration_refund:'Record Fee Refund',registration_waiver:'Waive Outstanding Fee'} as Record<string,string>)[kind]??kind;}
  allowedOperations(){if(!this.canWrite()||!this.context())return [];const r=this.context()!;if(this.contextKind()==='driver')return [...((r['remainingPaise']??0)>0?['registration_payment']:[]),...((r['netReceivedPaise']??0)>0?['registration_refund']:[]),...((r['remainingPaise']??0)>0&&!(r['receipts']??[]).some((m:RecordData)=>m['kind']==='registration_waiver')?['registration_waiver']:[])];if(r['farePaise']==null)return [];if(this.section()==='Commissions')return r['commissionReceivable']>0?['commission_settlement']:[];if(this.section()==='Driver Payouts')return r['payable']>0?['driver_payout']:[];if(this.section()==='Refunds & Adjustments')return [...(r['collected']>r['refunded']?['booking_refund']:[]),...(r['driverCollected']>r['driverRefunded']?['driver_cod_refund']:[]),...(r['commissionSettled']>0?['commission_refund']:[]),...(r['paid']>r['recovered']?['driver_recovery']:[])];return [...(r['paymentMode']!=='razorpay'&&r['farePaise']>r['customerCollected']?['booking_payment']:[]),...(r['paymentMode']==='cash'&&r['driverId']&&r['farePaise']>r['customerCollected']?['driver_cod_collection']:[])];}
  chooseOperation(kind:string){if(!this.allowedOperations().includes(kind))return;this.operation.set(kind);this.confirming.set(false);this.requestKey=crypto.randomUUID();const r=this.context()!;this.form.amount=(kind==='registration_payment'||kind==='registration_waiver'?r['remainingPaise']:kind==='registration_refund'?r['netReceivedPaise']:kind==='driver_payout'?r['payable']:kind==='commission_settlement'?r['commissionReceivable']:kind==='commission_refund'?r['commissionSettled']:kind==='booking_refund'?r['collected']-r['refunded']:kind==='driver_cod_refund'?r['driverCollected']-r['driverRefunded']:kind==='driver_recovery'?r['paid']-r['recovered']:r['farePaise']-r['customerCollected'])/100;this.form.method=kind==='registration_waiver'?'waiver':kind==='driver_cod_collection'?'cash':['driver_payout','commission_settlement'].includes(kind)?'bank_transfer':'cash';}
  submit(){if(!this.canWrite()||!this.allowedOperations().includes(this.operation())||this.submitting()||!this.confirming()||!this.form.reason.trim()||(!this.form.reference.trim()&&this.contextKind()!=='driver')||this.form.amount<=0){this.contextError.set('Enter the amount, transaction reference and audit reason, and confirm the actual receipt or completed transfer.');return;}const r=this.context()!,sequence=this.contextSequence;this.submitting.set(true);this.contextError.set('');this.http.post(this.base+'/movements',{kind:this.operation(),...(this.contextKind()==='driver'?{driverId:r['id']}:{bookingId:r['id'],...(r['driverId']?{driverId:r['driverId']}:{})}),amountPaise:Math.round(this.form.amount*100),reference:this.form.reference.trim()||'registration-receipt:'+this.requestKey,method:this.form.method,reason:this.form.reason.trim(),confirmed:true}).subscribe({next:()=>{if(sequence!==this.contextSequence)return;this.submitting.set(false);this.close();this.success.set('Confirmed financial record saved.');this.load();},error:async e=>{const message=await httpErrorMessage(e);if(sequence===this.contextSequence){this.submitting.set(false);this.refreshFailedContext(message);}}});}
  refreshFailedContext(message:string){const id=this.contextId();if(!id){this.contextError.set(message);return;}const sequence=++this.contextSequence;this.contextError.set(message);this.http.get<{data:RecordData}>(`${this.base}/${this.contextKind()==='driver'?'drivers/'+id+'/fee':'bookings/'+id}`).subscribe({next:r=>{if(sequence===this.contextSequence)this.context.set(r.data);},error:async e=>{if(sequence===this.contextSequence)this.contextError.set(message+' Record refresh failed: '+await httpErrorMessage(e));}});}
  savePolicy(){if(!this.auth.can('payments.overview','edit')||this.savingPolicy()||!this.policy.reason.trim())return;const r=this.context()!,sequence=this.contextSequence;this.savingPolicy.set(true);this.policyError.set('');this.http.patch(`${this.base}/drivers/${r['id']}/fee-policy`,{registrationFeePaise:Math.round(this.policy.amount*100),registrationFeeRequired:this.policy.required,reason:this.policy.reason.trim()}).subscribe({next:()=>{if(sequence!==this.contextSequence)return;this.savingPolicy.set(false);this.success.set('Fee policy saved. No payment was recorded.');this.openRecord('driver',r['id']);this.load();},error:async e=>{if(sequence===this.contextSequence){this.savingPolicy.set(false);this.policyError.set(await httpErrorMessage(e));}}});}
  attention(b:RecordData){this.go(b['commissionReceivable']>0?'commissions':b['payable']>0?'driver-payouts':'booking-payments',{bookingId:b['id']},true);}
  viewMovement(m:RecordData){this.go(m['kind'].startsWith('registration_')?'registration-fees':m['kind'].startsWith('commission_')?'commissions':m['kind']==='driver_payout'?'driver-payouts':m['kind'].includes('refund')||m['kind']==='driver_recovery'?'refunds-adjustments':'booking-payments',m['bookingId']?{bookingId:m['bookingId']}:{driverId:m['driverId']},true);}
  holder(m:RecordData){return m['kind'].startsWith('driver_cod')?'Driver':m['kind']==='driver_payout'?'Completed transfer to driver':'Platform';}
  intentName(intent:RecordData){return intent['booking']?`${intent['booking']['bookingCode']} · ${intent['booking']['customerName']}`:`${intent['driver']?.['firstName']??'Driver'} ${intent['driver']?.['lastName']??''}`.trim();}
  openIntent(intent:RecordData){if(intent['booking']?.['id'])this.go('booking-payments',{bookingId:intent['booking']['id']});else if(intent['driver']?.['id'])this.go('registration-fees',{driverId:intent['driver']['id']});}
  confirmationLabel(){return this.operation()==='registration_waiver'?'I confirm this authorized fee waiver':'I confirm this money was actually received or the transfer completed';}
  download(){if(!this.auth.can('payments.overview','export'))return;let params=new HttpParams();for(const[key,value]of Object.entries(this.filters))if(value)params=params.set(key,value);this.http.get(this.base+'/report.csv',{params,responseType:'blob'}).subscribe({next:blob=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='accounts-report.csv';a.click();URL.revokeObjectURL(url);},error:async e=>this.error.set(await httpErrorMessage(e))});}
}
