import { Component, CUSTOM_ELEMENTS_SCHEMA, signal, inject, OnInit, computed } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AdminPage } from '../../../admin/admin-page/admin-page';

interface ReportRecord {
  id?: number;
  report_uid: string;
  report_type: string;
  report_name: string;
  generated_by: number;
  generated_by_name?: string;
  date_from?: string;
  date_to?: string;
  filters?: string;
  file_path?: string;
  file_format?: string;
  status: string;
  generated_at?: string;
}

@Component({
  selector: 'md-account-reports',
  standalone: true,
  imports: [AdminPage],
  templateUrl: './reports.html',
  styleUrl: '../masters/masters.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class Reports implements OnInit {
  private readonly http = inject(HttpClient);

  // --- All Reports Repository ---
  readonly allReports = signal<ReportRecord[]>([]);

  // --- Search, Filter, Sort & Pagination Signals ---
  readonly searchQuery = signal<string>('');
  readonly statusFilter = signal<string>('all');
  readonly sortKey = signal<string>('report_uid');
  readonly sortDir = signal<'asc' | 'desc' | ''>('desc');
  readonly page = signal<number>(1);
  readonly pageSize = signal<number>(10);

  // --- View Switcher (Page vs Form) ---
  readonly showAddForm = signal<boolean>(false);
  readonly editingReportId = signal<number | null>(null);

  // --- Form Input Signals ---
  readonly inputReportUid = signal<string>('');
  readonly inputReportName = signal<string>('');
  readonly inputReportType = signal<string>('Trip');
  readonly inputGeneratedBy = signal<string>('');
  readonly inputDateFrom = signal<string>('');
  readonly inputDateTo = signal<string>('');
  readonly inputFilters = signal<string>('');
  readonly inputFilePath = signal<string>('');
  readonly inputFileFormat = signal<string>('PDF');
  readonly inputStatus = signal<string>('Generating');
  readonly inputGeneratedAt = signal<string>('');

  protected readonly content = signal({
    title: 'Report Registry',
    subtitle: 'Generate, schedule and download operations reports.',
    cardTitle: 'Create New Report',
    btnRegister: 'Save Report',
    errorEmptyFields: 'Report UID, Report Name, Report Type, Generated By ID, and Status are required.'
  });

  // --- Table Columns ---
  readonly tableColumns = JSON.stringify([
    { key: 'report_uid', label: 'Report UID', sortable: true },
    { key: 'report_name', label: 'Report Name', sortable: true },
    { key: 'report_type', label: 'Type', sortable: true },
    { key: 'generated_by_name', label: 'Generated By', sortable: true },
    { key: 'file_format', label: 'Format', sortable: true },
    { key: 'generated_at', label: 'Generated At', sortable: true },
    { key: 'status', label: 'Status', type: 'status', statusMap: { 
        'Completed': 'success', 
        'Generating': 'warning', 
        'Failed': 'error'
      } 
    },
    { key: 'generated_by', label: 'User ID', sortable: true, hidden: true },
    { key: 'date_from', label: 'Start Date', sortable: true, hidden: true },
    { key: 'date_to', label: 'End Date', sortable: true, hidden: true },
    { key: 'filters', label: 'Filters (JSON)', sortable: false, hidden: true },
    { key: 'file_path', label: 'File Path', sortable: false, hidden: true }
  ]);

  readonly tableFilterOptions = JSON.stringify([
    { value: 'all', label: 'All Statuses' },
    { value: 'Completed', label: 'Completed' },
    { value: 'Generating', label: 'Generating' },
    { value: 'Failed', label: 'Failed' }
  ]);

  readonly tableActions = JSON.stringify([
    { icon: 'visibility', label: 'View Details', event: '__view_detail__' },
    { icon: 'edit', label: 'Edit', event: 'edit_report' },
    { icon: 'delete', label: 'Delete', event: 'delete_report', variant: 'danger' }
  ]);

  // --- Filtered Dataset ---
  readonly processedReports = computed(() => {
    let list = this.allReports().map(r => {
      const userMap: Record<number, string> = {
        101: 'Admin User',
        102: 'Super Admin'
      };
      return {
        generated_by_name: r.generated_by_name || userMap[r.generated_by] || `User #${r.generated_by}`,
        ...r
      };
    });

    // 1. Search Query Filter
    const query = this.searchQuery().toLowerCase().trim();
    if (query) {
      list = list.filter(r =>
        r.report_uid.toLowerCase().includes(query) ||
        r.report_name.toLowerCase().includes(query) ||
        r.report_type.toLowerCase().includes(query) ||
        r.generated_by_name.toLowerCase().includes(query)
      );
    }

    // 2. Dropdown Filter
    const filter = this.statusFilter();
    if (filter !== 'all') {
      list = list.filter(r => r.status === filter);
    }

    // 3. Sort
    const key = this.sortKey();
    const dir = this.sortDir();
    if (key && dir) {
      list = [...list].sort((a: any, b: any) => {
        const valA = String(a[key] ?? '').toLowerCase();
        const valB = String(b[key] ?? '').toLowerCase();
        return dir === 'asc' ? valA.localeCompare(valB) : valB.localeCompare(valA);
      });
    }

    return list;
  });

  // --- Paginated Rows ---
  readonly tableRowsString = computed(() => {
    const list = this.processedReports();
    const start = (this.page() - 1) * this.pageSize();
    const paginated = list.slice(start, start + this.pageSize());
    return JSON.stringify(paginated);
  });

  readonly totalReports = computed(() => this.processedReports().length);

  ngOnInit(): void {
    this.http.get<ReportRecord[]>('data/reports.json').subscribe({
      next: (data) => {
        this.allReports.set(data || []);
      },
      error: (err) => {
        console.error('Failed to load mock reports JSON', err);
      }
    });
  }

  // --- Add/Edit Report Log ---
  addReport(): void {
    const report_uid = this.inputReportUid().trim();
    const report_name = this.inputReportName().trim();
    const report_type = this.inputReportType();
    const generated_by = Number(this.inputGeneratedBy().trim());
    const status = this.inputStatus();

    if (!report_uid || !report_name || !report_type || isNaN(generated_by) || !status) {
      alert(this.content().errorEmptyFields);
      return;
    }

    const newRecord: ReportRecord = {
      id: this.editingReportId() || Date.now(),
      report_uid,
      report_name,
      report_type,
      generated_by,
      date_from: this.inputDateFrom() || undefined,
      date_to: this.inputDateTo() || undefined,
      filters: this.inputFilters().trim() || undefined,
      file_path: this.inputFilePath().trim() || undefined,
      file_format: this.inputFileFormat(),
      status,
      generated_at: this.inputGeneratedAt() || undefined
    };

    const editingId = this.editingReportId();
    if (editingId !== null) {
      this.allReports.update(list => list.map(r => r.id === editingId ? newRecord : r));
    } else {
      this.allReports.update(list => [newRecord, ...list]);
    }

    this.resetForm();
    this.showAddForm.set(false);
  }

  resetForm(): void {
    this.editingReportId.set(null);
    this.inputReportUid.set('');
    this.inputReportName.set('');
    this.inputReportType.set('Trip');
    this.inputGeneratedBy.set('');
    this.inputDateFrom.set('');
    this.inputDateTo.set('');
    this.inputFilters.set('');
    this.inputFilePath.set('');
    this.inputFileFormat.set('PDF');
    this.inputStatus.set('Generating');
    this.inputGeneratedAt.set('');
  }

  onParamsChange(event: Event): void {
    const detail = (event as CustomEvent).detail;
    this.page.set(detail.page);
    this.pageSize.set(detail.pageSize);
    this.sortKey.set(detail.sortKey);
    this.sortDir.set(detail.sortDir);
    this.searchQuery.set(detail.search);
    this.statusFilter.set(detail.filter || 'all');
  }

  onRowSelect(event: Event): void {
    const detail = (event as CustomEvent).detail;
    console.log('Selected Reports:', detail.selected);
  }

  onRowAction(event: Event): void {
    const detail = (event as CustomEvent).detail;
    const action = detail.action;
    const row = detail.row;

    if (action === 'edit_report') {
      this.editingReportId.set(row.id);
      this.inputReportUid.set(row.report_uid || '');
      this.inputReportName.set(row.report_name || '');
      this.inputReportType.set(row.report_type || 'Trip');
      this.inputGeneratedBy.set(String(row.generated_by || ''));
      this.inputDateFrom.set(row.date_from || '');
      this.inputDateTo.set(row.date_to || '');
      this.inputFilters.set(row.filters || '');
      this.inputFilePath.set(row.file_path || '');
      this.inputFileFormat.set(row.file_format || 'PDF');
      this.inputStatus.set(row.status || 'Generating');
      this.inputGeneratedAt.set(row.generated_at || '');

      this.showAddForm.set(true);
    } else if (action === 'delete_report') {
      if (confirm(`Are you sure you want to delete report log "${row.report_uid}"?`)) {
        this.allReports.update(list => list.filter(r => r.id !== row.id));
      }
    }
  }

  openAddReportForm(): void {
    this.showAddForm.set(true);
  }

  closeAddReportForm(): void {
    this.showAddForm.set(false);
    this.resetForm();
  }

  onInputChange(field: string, event: Event): void {
    const val = (event.target as any).value || '';
    switch(field) {
      case 'report_uid': this.inputReportUid.set(val); break;
      case 'report_name': this.inputReportName.set(val); break;
      case 'report_type': this.inputReportType.set(val); break;
      case 'generated_by': this.inputGeneratedBy.set(val); break;
      case 'date_from': this.inputDateFrom.set(val); break;
      case 'date_to': this.inputDateTo.set(val); break;
      case 'filters': this.inputFilters.set(val); break;
      case 'file_path': this.inputFilePath.set(val); break;
      case 'file_format': this.inputFileFormat.set(val); break;
      case 'status': this.inputStatus.set(val); break;
      case 'generated_at': this.inputGeneratedAt.set(val); break;
    }
  }
}
